import type { TrancheTeachingSeed } from "./foundations-git-tranche";

export interface AiTeachingSeed extends TrancheTeachingSeed {
  readonly checkpoint: string;
}

/**
 * Source-bounded AI teaching claims. These are deliberately conservative:
 * every benchmark, metric, model output, explanation, and control remains
 * bounded evidence rather than a claim of intelligence, safety, or fitness.
 */
export const AI_TRANCHE_SEEDS = {
  "ai.foundations.scope": {
    model: "AI is an umbrella for computational techniques that perform bounded tasks associated with perception, prediction, reasoning, search, generation, or action; capability claims require an operational task, comparison, and evidence.",
    boundary: "Fixed automation can be complex without learning, learned systems can still be narrow, fluent output does not prove understanding, and one benchmark cannot establish general intelligence or deployment fitness.",
    scenarioA: "A rules engine always applies authored thresholds, while a classifier estimates a label from fitted examples; both are evaluated against their declared decision task rather than a marketing label.",
    scenarioB: "A chatbot writes plausible explanations on a benchmark but fails changed instructions and unsupported facts, so the claim is narrowed to the tested conditions.",
    misconception: "Any system that adapts output, uses a neural network, or speaks fluently has demonstrated broad human-like intelligence.",
    correction: "State an operational capability claim with task, population, conditions, baseline, metric, uncertainty, and failure evidence; do not infer general intelligence from technique or fluency.",
    checkpoint: "operational capability claim",
  },
  "ai.foundations.problem-characteristics": {
    model: "An AI task is constrained by what is observable, how actions change the environment, whether outcomes are deterministic, how time evolves, whether states/actions are discrete, how many agents act, and what uncertainty remains.",
    boundary: "These properties can differ between simulation and deployment, partial observability can be hidden by convenient datasets, other agents change dynamics, and a useful abstraction deliberately omits details.",
    scenarioA: "A static grid puzzle is discrete, deterministic, fully observable, and single-agent under its rules, supporting exact state-space search.",
    scenarioB: "A road-driving task is dynamic, partially observable, continuous, stochastic, and multi-agent, so the grid assumptions cannot justify the same guarantees.",
    misconception: "Once a task is called classification, search, or robotics, its environment properties and appropriate solution family are already determined.",
    correction: "Characterize observability, determinism, dynamics, discreteness, agency, and uncertainty for the actual deployment context before choosing or evaluating a method.",
    checkpoint: "actual deployment context",
  },
  "ai.foundations.agents": {
    model: "An agent receives percepts, maintains any needed state, chooses actions, and is evaluated against an explicit performance measure or utility under bounded information and resources.",
    boundary: "A goal does not specify every trade-off, a utility encodes value choices, rationality is relative to information and constraints, and optimizing a proxy can exploit gaps in the intended objective.",
    scenarioA: "A cleaning agent observes location and dirt state, can move or clean, and is scored on cleanliness, energy, collisions, and time rather than only number of actions.",
    scenarioB: "An agent rewarded only for items collected blocks other users to capture every item, revealing that the reward omitted cooperation and safety constraints.",
    misconception: "A rational agent always finds the objectively best action, and a numeric reward is a neutral statement of the real goal.",
    correction: "Specify percepts, state, actions, constraints, stakeholders, and a bounded performance measure; treat utility and reward as contestable proxy choices.",
    checkpoint: "contestable proxy choices",
  },
  "ai.foundations.history-limits": {
    model: "AI has developed through interacting symbolic, search, probabilistic, statistical, and neural traditions, with progress and setbacks shaped by compute, data, evaluation, funding, and gaps between demos and robust capability.",
    boundary: "Historical periods overlap, methods combine, labels shift, benchmark gains can coexist with brittle transfer, and simplified boom-winter narratives omit institutions, labor, harms, and prior work.",
    scenarioA: "A modern system combines neural representations, search, hand-authored constraints, and probabilistic scoring rather than belonging to one pure historical camp.",
    scenarioB: "A benchmark record is announced as a solved domain, but changed data and real workflows expose distribution, cost, and safety failures.",
    misconception: "AI history is a straight sequence in which neural networks replaced symbolic and statistical methods and each benchmark record proves general progress.",
    correction: "Place claims in overlapping technical and social context, identify the evaluation boundary, and distinguish benchmark improvement from general or deployment capability.",
    checkpoint: "evaluation boundary",
  },
  "ai.search.state-space": {
    model: "A state-space problem defines sufficient states, legal successor actions, a start state, a goal test, and path costs so solutions correspond to valid paths in an implicit graph.",
    boundary: "Omitted state can make successors invalid, duplicate states create cycles, action cost may not equal step count, the representation changes search complexity, and a found path still needs domain validation.",
    scenarioA: "A grid state includes current cell, obstacles remain fixed, successors are legal adjacent moves, the goal tests one cell, and every move has unit cost.",
    scenarioB: "A key-and-door puzzle adds held keys to the state because location alone cannot determine which moves are legal.",
    misconception: "A search state only needs the agent's current position; history, resources, or permissions never affect future legal actions.",
    correction: "Encode every fact needed to determine successors, goal status, and future cost while merging histories only when they are behaviorally equivalent.",
    checkpoint: "behaviorally equivalent",
  },
  "ai.search.uninformed": {
    model: "DFS, BFS, iterative deepening, and uniform-cost search differ in frontier order, duplicate handling, completeness, optimality conditions, time, and memory; selection follows graph and cost assumptions.",
    boundary: "BFS is optimal only for equal step costs, DFS can follow infinite/deep branches, uniform-cost needs nonnegative costs, graph search needs a cost-aware visited policy, and practical memory can dominate.",
    scenarioA: "BFS finds a minimum-step route in a finite unweighted graph using a queue and a visited set marked when enqueued.",
    scenarioB: "A longer route has lower total cost, so uniform-cost search replaces BFS and updates a state when a cheaper path is discovered.",
    misconception: "BFS always finds the cheapest path and a state should be permanently marked visited the first time any search encounters it.",
    correction: "Match the frontier and duplicate policy to depth and path-cost assumptions; BFS minimizes steps under equal costs, while uniform-cost search minimizes nonnegative accumulated cost.",
    checkpoint: "minimizes steps",
  },
  "ai.search.heuristics": {
    model: "A heuristic estimates remaining cost; greedy best-first prioritizes that estimate alone, while A* prioritizes accumulated cost plus estimate and inherits optimality only under stated admissibility or consistency conditions.",
    boundary: "An admissible heuristic can still expand many states, inconsistency can require reopening, tie-breaking changes work not guaranteed cost, scaling must match costs, and an empirical estimate is not automatically admissible.",
    scenarioA: "Manhattan distance is used on a four-direction unit grid without teleportation and never exceeds the true remaining path cost.",
    scenarioB: "Adding a multiplier greater than one expands fewer nodes on examples but removes the standard admissibility guarantee, so the trade-off is reported honestly.",
    misconception: "A heuristic that often predicts accurately is admissible, and A* always returns an optimal path regardless of heuristic or duplicate handling.",
    correction: "Prove or bound the heuristic against true remaining cost and implement the required reopen/duplicate policy; report optimality only under those conditions.",
    checkpoint: "true remaining cost",
  },
  "ai.search.adversarial": {
    model: "Minimax backs terminal or cutoff utility through alternating maximizing and minimizing choices, while alpha-beta skips branches that cannot change the backed-up decision under the same ordering and evaluation assumptions.",
    boundary: "Depth cutoffs require a heuristic evaluation, real opponents need not minimize the modeled utility, chance nodes require another model, move order affects pruning not minimax value, and utility design embeds preferences.",
    scenarioA: "A depth-two zero-sum tree alternates max and min layers, backs leaf values, and selects the root action with the highest worst-case result.",
    scenarioB: "Alpha-beta visits a strong move first and prunes a sibling branch only after its bound cannot improve the ancestor decision.",
    misconception: "Alpha-beta changes the minimax answer to a faster approximation and can prune any branch whose first leaf looks poor.",
    correction: "Alpha-beta preserves the minimax value when bounds and alternating roles are correct; prune only after the branch cannot affect an ancestor choice.",
    checkpoint: "preserves the minimax value",
  },
  "ai.knowledge.symbolic": {
    model: "A symbolic knowledge base uses explicit constants, predicates, relations, facts, rules, and queries whose meaning depends on the declared domain and closed- or open-world assumptions.",
    boundary: "Natural-language ambiguity is not removed automatically, absence can mean false or unknown, inconsistent rules can derive conflicts, names need identity assumptions, and symbolic truth does not prove the world is modeled completely.",
    scenarioA: "Facts parent(ana,bo) and a rule parent(x,y) -> ancestor(x,y) support one bounded ancestor query under named assumptions.",
    scenarioB: "The database lacks vaccinated(bo); an open-world policy returns unknown rather than concluding not vaccinated.",
    misconception: "If a fact is not stored in a symbolic knowledge base, it is false in every reasoning system.",
    correction: "Declare the vocabulary, domain, identity, and open- or closed-world policy; distinguish explicit negation, contradiction, and missing knowledge.",
    checkpoint: "missing knowledge",
  },
  "ai.knowledge.inference": {
    model: "Inference applies sound rule steps to premises: forward chaining derives reachable consequences, backward reasoning reduces a query to supporting subgoals, and results can be entailed, contradicted, or unknown.",
    boundary: "Soundness differs from completeness, cyclic rules need termination control, inconsistent premises may derive both sides, absence is not contradiction, and a proof is relative to the encoded rules.",
    scenarioA: "From bird(tweety) and bird(x) -> animal(x), forward chaining derives animal(tweety) with a recorded two-premise proof path.",
    scenarioB: "Neither safe(route) nor not-safe(route) is derivable, so the query remains unknown instead of being labeled false.",
    misconception: "A conclusion that cannot be proved is contradicted, and adding more rules can never create inconsistency.",
    correction: "Track proof support and classify entailed, contradicted, both, or unknown according to the logic and consistency policy; lack of proof alone is not negation.",
    checkpoint: "lack of proof",
  },
  "ai.uncertainty.bayes": {
    model: "Bayes' rule updates a prior using likelihood of observed evidence and normalizes across alternatives, making base rates and evidence reliability explicit.",
    boundary: "A posterior is conditional on model assumptions, likelihood is not the posterior, dependent evidence cannot be multiplied as independent, low base rates can dominate, and estimated inputs carry uncertainty.",
    scenarioA: "A rare condition with a sensitive test still has a modest positive posterior because false positives among the large unaffected population are included.",
    scenarioB: "Two correlated symptoms are not multiplied as independent evidence; the model either represents their dependency or reports the simplifying assumption.",
    misconception: "A test that is 95 percent accurate means a positive result gives a 95 percent probability of the condition.",
    correction: "Compute the posterior from prior, likelihood, and evidence normalization; sensitivity or headline accuracy alone is not the probability after a positive result.",
    checkpoint: "evidence normalization",
  },
  "ai.uncertainty.graphical": {
    model: "A Bayesian network is a directed acyclic factorization of a joint distribution in which graph structure encodes conditional independences under the modeled probability assumptions.",
    boundary: "An edge does not by itself establish causation, missing edges assert conditional independence only relative to the graph, latent variables can distort interpretation, and parameters need valid normalized distributions.",
    scenarioA: "Rain and sprinkler both point to wet grass, so they become dependent after observing the common effect even if they were marginally independent in the model.",
    scenarioB: "A learned arrow between advertising and sales is reported as probabilistic dependency, not causal effect, because intervention and confounding evidence are absent.",
    misconception: "Every directed edge in a Bayesian network proves that changing the parent will cause the child to change.",
    correction: "Read the graph as a probabilistic factorization and conditional-independence claim; causal interpretation requires additional assumptions and evidence.",
    checkpoint: "probabilistic factorization",
  },
  "ai.planning.actions": {
    model: "A classical planning action has preconditions defining applicability and effects defining the successor state; a plan is valid when each action applies in sequence and the final state satisfies the goal.",
    boundary: "Frame assumptions must preserve unaffected facts, real actions can be stochastic or durative, resource conflicts need representation, a valid plan may be costly or unsafe, and omitted effects invalidate simulation.",
    scenarioA: "pick-up(key) requires at(key) and empty-hand, removes at(key), and adds holding(key); the validator simulates every step before testing the door-open goal.",
    scenarioB: "Two individually applicable actions compete for one battery resource, so the state adds remaining energy before the plan is judged valid.",
    misconception: "A list of actions is a valid plan whenever its final action mentions the goal, regardless of intermediate preconditions.",
    correction: "Simulate actions from the initial state, require every precondition when used, apply complete effects, and test the explicit goal after the full sequence.",
    checkpoint: "every precondition",
  },
  "ai.planning.constraints": {
    model: "A constraint-satisfaction problem declares variables, finite domains, and constraints; propagation removes unsupported values and backtracking explores remaining assignments with reversible state.",
    boundary: "Local consistency does not guarantee a solution, heuristics change work not solution validity, copying/restoration errors corrupt search, global constraints can propagate more strongly, and unsatisfiable needs evidence.",
    scenarioA: "A map-coloring solver chooses an unassigned region, removes neighbor colors, backtracks on an empty domain, and validates every edge in the final assignment.",
    scenarioB: "Minimum-remaining-values reduces explored nodes on one puzzle but is reported as a heuristic rather than a completeness requirement.",
    misconception: "If arc or forward consistency leaves every domain nonempty, a complete satisfying assignment is guaranteed.",
    correction: "Use propagation to prune unsupported values, then retain complete backtracking and validate every constraint on a returned assignment.",
    checkpoint: "complete backtracking",
  },
  "ai.decision.utility": {
    model: "Expected utility compares actions by summing each modeled outcome's utility weighted by its probability, exposing value judgments, uncertainty, and sensitivity to assumptions.",
    boundary: "Utility is stakeholder-dependent, probabilities can be poorly estimated, rare severe harms can dominate, expected value can hide distribution and fairness, and constraints may rule out an otherwise high score.",
    scenarioA: "Two treatments are compared using benefit, side-effect utility, and calibrated scenario probabilities, followed by a sensitivity range for the uncertain harm rate.",
    scenarioB: "An action with slightly higher expected utility is rejected because it violates an explicit safety constraint for one affected group.",
    misconception: "The action with the largest expected monetary value is objectively rational for every stakeholder and ethical context.",
    correction: "Make outcome utilities, probabilities, stakeholders, constraints, and sensitivity explicit; expected utility supports a bounded choice rather than neutralizing values.",
    checkpoint: "sensitivity explicit",
  },
  "ai.decision.sequential": {
    model: "A sequential decision model defines states, actions, transitions, rewards, and a policy over time; exploration gathers information while exploitation uses current estimates.",
    boundary: "The Markov assumption may fail, reward is a proxy, delayed effects complicate credit, offline data limits exploration, unsafe actions need hard constraints, and simulated performance may not transfer.",
    scenarioA: "A small grid MDP penalizes each step, rewards a goal, and blocks hazardous cells while a policy is evaluated over repeated episodes.",
    scenarioB: "A recommender maximizes clicks and learns sensational content, so retention, harm, diversity, and user control are added as measures and constraints rather than assumed from reward.",
    misconception: "A reinforcement-learning agent discovers the true objective automatically from experience, so reward design is only a technical detail.",
    correction: "Treat reward as a proxy chosen by people, test reward-hacking and distribution shift, and enforce safety or rights constraints outside a single optimized score.",
    checkpoint: "reward as a proxy",
  },
  "ai.data.problem-target": {
    model: "An ML problem statement defines the prediction unit, target and observation time, decision user, action enabled, baseline, error costs, population, non-goals, and measurable success before model choice.",
    boundary: "A measurable label can still be a harmful proxy, historical decisions can contaminate targets, prediction may not improve the decision, metrics can conflict, and deployment prevalence can differ from training.",
    scenarioA: "A support triage project predicts whether a ticket needs specialist review at intake, compares a rules baseline, and measures missed urgent cases plus reviewer workload.",
    scenarioB: "Past approval is rejected as a creditworthiness target because it encodes prior policy and cannot establish the desired outcome fairly.",
    misconception: "Choosing an available target column and maximizing its test accuracy is enough to define a useful ML problem.",
    correction: "Specify target timing, decision context, population, baseline, error costs, non-goals, and stop criteria; reject labels that do not represent the intended outcome.",
    checkpoint: "target timing",
  },
  "ai.data.quality": {
    model: "Data quality assessment examines provenance, collection process, consent/authority, sampling, missingness, duplicates, measurement error, label uncertainty, representation, time, and linkage to the deployment population.",
    boundary: "Cleaning cannot recover absent populations, missingness can be informative, majority labels can be wrong, deduplication can leak across splits, and a large dataset can still be systematically biased.",
    scenarioA: "A report groups missing labels by site and month, measures duplicate entities before splitting, samples label disagreements, and names populations absent from collection.",
    scenarioB: "Dropping every incomplete row removes a subgroup with lower device connectivity, changing both representation and the decision target.",
    misconception: "Removing nulls and duplicates makes a dataset unbiased and representative, especially when the remaining row count is large.",
    correction: "Report provenance and measurement processes plus who or what is missing or mismeasured; cleaning changes data but cannot establish representativeness.",
    checkpoint: "cannot establish representativeness",
  },
  "ai.data.features": {
    model: "Feature preprocessing converts raw fields into meaningful numeric representations, with learned imputation, scaling, encoding, and selection fitted only on training data and replayed unchanged on later data.",
    boundary: "Scaling needs vary by model, categories can be unseen, timestamps can leak future information, high-cardinality encoding can memorize, and a pipeline prevents procedural leakage but not a conceptually leaked feature.",
    scenarioA: "A ColumnTransformer imputes/scales numeric columns and one-hot encodes categories inside a pipeline fitted during cross-validation folds.",
    scenarioB: "A feature containing final resolution time is removed because no pipeline can make information unavailable at prediction time legitimate.",
    misconception: "It is safe to fit a scaler or category vocabulary on the full dataset because preprocessing does not use the target directly.",
    correction: "Fit every data-derived preprocessing step on the training partition or fold only, and exclude features unavailable at the real prediction time.",
    checkpoint: "training partition or fold only",
  },
  "ai.data.splits-leakage": {
    model: "Train data fits parameters, validation or cross-validation guides choices, and a held-out test estimates the frozen procedure; splits must reflect future deployment units, groups, time, and duplication structure.",
    boundary: "Random rows can leak people or future time, repeated test inspection turns test into validation, preprocessing can leak, a small test has uncertainty, and distribution shift can make any historical estimate optimistic.",
    scenarioA: "All records for one patient stay in one split and the newest time period is held out when deployment predicts future visits.",
    scenarioB: "Near-duplicate documents are grouped before splitting so retrieval or classification cannot score by memorizing another copy.",
    misconception: "Any random 80/20 split prevents leakage as long as the target column is removed from model inputs.",
    correction: "Split by the deployment unit and time structure before fitting preprocessing or tuning, and reserve the test set for the frozen final procedure.",
    checkpoint: "deployment unit",
  },
  "ai.supervised.regression": {
    model: "Regression estimates a continuous target from examples and is evaluated against simple baselines using metrics whose scale and loss shape match the decision, plus residual analysis across relevant slices.",
    boundary: "Low average error can hide subgroup or tail failures, extrapolation is fragile, correlation is not causation, squared loss emphasizes large errors, and target noise limits attainable performance.",
    scenarioA: "A median baseline and linear model are compared with MAE, while residuals are plotted by target range and region before any deployment claim.",
    scenarioB: "A lower RMSE model is rejected for one decision because its rare underestimates exceed a safety tolerance despite better average fit.",
    misconception: "A positive R-squared or lower RMSE proves accurate predictions for every case and explains which features cause the target.",
    correction: "Compare a baseline with decision-relevant error metrics, uncertainty, residual patterns, and slices; predictive association does not establish causation.",
    checkpoint: "predictive association",
  },
  "ai.supervised.classification": {
    model: "Classification produces labels or scores for categorical outcomes; thresholds convert scores to actions and must be chosen from prevalence, calibration, error costs, capacity, and group conditions rather than accuracy alone.",
    boundary: "Scores may be uncalibrated, class imbalance makes accuracy misleading, one threshold creates trade-offs, labels can be noisy, and post-deployment prevalence changes predictive values.",
    scenarioA: "A fraud model is compared with an always-negative baseline using precision, recall, confusion counts, review capacity, and threshold curves.",
    scenarioB: "A high AUC does not justify a production threshold until probability calibration and false-positive burden are checked on the deployment population.",
    misconception: "The class with the highest model score is a probability-certain answer, and accuracy is sufficient even for a rare positive class.",
    correction: "Separate labels, scores, and calibrated probabilities; choose and monitor thresholds using prevalence, error costs, capacity, and slice-specific confusion evidence.",
    checkpoint: "slice-specific confusion evidence",
  },
  "ai.supervised.models": {
    model: "Linear, nearest-neighbor, and tree models encode different assumptions about boundaries, scaling, locality, interactions, sample size, interpretability, and prediction cost; comparison holds data and metrics constant.",
    boundary: "No family is universally best, preprocessing changes comparisons, hyperparameter searches add selection bias, tree importance can mislead, and a more complex model must beat relevant baselines with uncertainty.",
    scenarioA: "Logistic regression, scaled k-nearest neighbors, and a depth-bounded tree use the same grouped folds and primary metric, with latency and slice errors reported.",
    scenarioB: "K-nearest neighbors degrades when irrelevant unscaled dimensions dominate distance, while a tree overfits small leaves unless complexity is controlled.",
    misconception: "A tree is always interpretable, nearest neighbors needs no training choices, and the model with the best validation score is objectively superior.",
    correction: "Compare model families under one split, preprocessing, metric, uncertainty, and operational-cost plan, then justify assumptions and remaining failure patterns.",
    checkpoint: "one split",
  },
  "ai.supervised.generalization": {
    model: "Generalization is performance on relevant unseen data; underfitting reflects insufficient useful fit, overfitting reflects adaptation to sample noise, and regularization or data changes trade bias and variance.",
    boundary: "Train-validation gaps are diagnostic but not unique causes, more data may preserve bias, regularization parameters must avoid test tuning, distribution shift differs from variance, and one split gives noisy evidence.",
    scenarioA: "Training and cross-validation curves show both errors high for an overly simple model, motivating features or capacity rather than stronger regularization.",
    scenarioB: "Near-zero train error with unstable validation performance leads to simpler capacity and repeated grouped folds while the test stays untouched.",
    misconception: "A large train-validation gap always means the model needs more data, and the test set can be checked repeatedly to choose regularization.",
    correction: "Diagnose underfit, variance, leakage, and shift with learning/validation evidence; tune without the test set and report variability across valid splits.",
    checkpoint: "without the test set",
  },
  "ai.unsupervised.clustering": {
    model: "Clustering groups examples according to a chosen representation, distance or density model, and algorithm parameters; quality is relative to the intended exploratory or operational use rather than hidden true labels by default.",
    boundary: "Scaling changes distances, k-means favors centroid-shaped groups, density methods depend on neighborhood parameters, hierarchical cuts are choices, and visually separated clusters may be unstable or meaningless.",
    scenarioA: "Numeric features are scaled, a k-means result is compared across k and seeds, and clusters are described by original features without treating numbers as discovered human categories.",
    scenarioB: "A density method marks sparse points as noise under one radius but changes sharply under another, so sensitivity and domain review are reported.",
    misconception: "A clustering algorithm discovers the natural categories already present in data, and a high silhouette score proves those categories are real.",
    correction: "Treat clusters as representation- and parameter-dependent summaries; test stability, sensitivity, usefulness, and harms before assigning real-world meaning.",
    checkpoint: "parameter-dependent summaries",
  },
  "ai.unsupervised.dimensionality": {
    model: "Dimensionality reduction maps data into fewer coordinates to preserve a stated property such as linear variance, neighborhood, or reconstruction, inevitably losing other information.",
    boundary: "Components may be hard to interpret, scaling matters, nonlinear visualizations distort distances, separated points need not be classes, fit must avoid leakage, and projection cannot recover omitted context.",
    scenarioA: "PCA is fitted on standardized training features, explained variance and reconstruction loss are reported, and downstream evaluation uses the same fitted transform.",
    scenarioB: "A two-dimensional visualization shows apparent islands that move with parameters, so it is used for exploration rather than evidence of distinct populations.",
    misconception: "A two-dimensional projection preserves all important structure, and visually separated groups prove the original data contains discrete classes.",
    correction: "Name the property the projection preserves, quantify retained and lost information, fit it within the evaluation split, and avoid turning visual separation into a class claim.",
    checkpoint: "retained and lost information",
  },
  "ai.unsupervised.anomaly": {
    model: "Anomaly detection scores observations as unusual relative to a defined reference population and representation; thresholds convert scores into alerts whose value depends on prevalence, review cost, and consequences.",
    boundary: "Rare is not harmful, harmful can be common, contaminated training shifts the reference, tail estimates are unstable, labels are scarce, and feedback from reviewed alerts changes future data.",
    scenarioA: "A robust univariate baseline flags large median absolute deviations, then reports alert rate and reviewer-confirmed precision instead of calling every outlier fraud.",
    scenarioB: "A new seasonal pattern triggers many alerts, so monitoring distinguishes distribution drift from individual harmful events.",
    misconception: "An outlier score is a probability of fraud or danger, and a stricter threshold always improves the detector.",
    correction: "Define unusual relative to a reference and evaluate thresholded alerts with prevalence, review capacity, false alarms, misses, drift, and domain confirmation.",
    checkpoint: "domain confirmation",
  },
  "ai.unsupervised.recommendation": {
    model: "Recommendation ranks items using popularity, content, collaborative signals, or combinations, and must account for exposure because observed interactions reflect what users were shown as well as preference.",
    boundary: "Offline held-out clicks are biased by past policy, cold-start differs, optimizing engagement can narrow or harm, popularity amplifies incumbents, and user welfare is not one metric.",
    scenarioA: "A personalized ranker is compared with recent-popularity and random baselines using time splits, catalog coverage, repeat rate, and user controls.",
    scenarioB: "Items never exposed have no clicks, so the system does not treat zero interaction as proof of dislike and documents counterfactual limits.",
    misconception: "Historical clicks are unbiased preference labels and a higher offline click metric proves the recommender benefits users.",
    correction: "Model exposure and policy effects, compare simple baselines, and evaluate relevance together with coverage, diversity, control, feedback loops, and stakeholder harms.",
    checkpoint: "policy effects",
  },
  "ai.neural.units-layers": {
    model: "A feed-forward neural unit computes a weighted sum plus bias and applies an activation; layers compose these transformations into representations and outputs with explicit shapes.",
    boundary: "Weights are learned parameters not explanations, nonlinear activations enable more than one linear map, shape errors can broadcast silently, output activation depends on task, and a tiny trace does not explain large networks.",
    scenarioA: "Two inputs feed two hidden ReLU units and one linear output; every weighted sum, activation, and tensor shape is calculated by hand.",
    scenarioB: "Removing all nonlinear activations collapses stacked dense layers into one affine transformation despite additional parameters.",
    misconception: "Each hidden unit learns one human-readable concept and adding more linear layers always creates nonlinear decision boundaries.",
    correction: "Trace weighted sums, biases, activations, and shapes exactly; composed representations need not map to one human concept, and nonlinearity changes expressiveness.",
    checkpoint: "activations, and shapes",
  },
  "ai.neural.training": {
    model: "Neural training evaluates a loss on examples, computes gradients of that loss with respect to parameters, and applies an optimizer update whose scale depends on learning rate, features, batches, and objective.",
    boundary: "A gradient is local, lower training loss need not improve validation, learning rate can diverge or stall, stochastic batches add variance, nonconvex optimization lacks a global guarantee, and labels/objectives encode choices.",
    scenarioA: "For one scalar linear prediction, the learner computes squared loss, its gradient, and one parameter update, then verifies the new loss numerically.",
    scenarioB: "A learning rate ten times larger overshoots and increases loss, showing that gradient direction alone does not choose a safe step size.",
    misconception: "Gradient descent always moves directly to the global best model and any positive learning rate eventually converges.",
    correction: "Treat gradients as local loss sensitivity and validate update scale, data, objective, and generalization; convergence and global optimality are not automatic.",
    checkpoint: "local loss sensitivity",
  },
  "ai.neural.regularization": {
    model: "Neural experiments separate training, validation, and test evidence; regularization, early stopping, augmentation, architecture, and seeded repetitions control or measure generalization without tuning on the test.",
    boundary: "Seeds do not remove nondeterminism, early stopping uses validation repeatedly, augmentation can change labels, regularization can underfit, hardware/library behavior varies, and one run hides variability.",
    scenarioA: "Three seeded runs compare a baseline with weight decay using the same validation policy, report mean and range, and evaluate the frozen choice once on test.",
    scenarioB: "Test accuracy is not monitored each epoch because that would adapt model selection to the held-out set.",
    misconception: "Setting one random seed makes neural training exactly reproducible and checking the test after every epoch is harmless monitoring.",
    correction: "Record environment and seeds, repeat controlled runs, use validation for choices, reserve test for the frozen procedure, and report remaining variability.",
    checkpoint: "remaining variability",
  },
  "ai.neural.architectures": {
    model: "Convolution emphasizes local shared patterns, recurrence carries sequential state, and attention forms content-dependent interactions; architecture choice follows data structure, task, scale, latency, and evidence.",
    boundary: "These families overlap and combine, attention has substantial context cost, position needs representation, convolution does not ensure invariance, recurrence can lose long dependencies, and scale does not guarantee understanding.",
    scenarioA: "A small image task starts with convolutional locality and compares a simple baseline before considering a large attention model.",
    scenarioB: "A long-document attention design states finite context, quadratic-like interaction cost for standard full attention, and a retrieval or chunking trade-off.",
    misconception: "Transformers and attention are universally superior, understand sequence meaning, and remove context or compute limits.",
    correction: "Match structural inductive bias and compute to the task, compare baselines, and state finite context, data, latency, and transfer limitations.",
    checkpoint: "finite context",
  },
  "ai.applications.nlp": {
    model: "NLP tasks include tokenization, representation, classification, extraction, retrieval, translation, and generation; evaluation must match the task, language varieties, stakeholders, and error costs.",
    boundary: "Tokens are model units not words, benchmark language coverage is limited, automatic overlap metrics miss meaning and harms, dialect performance varies, generated text can be unsupported, and annotations encode policy.",
    scenarioA: "A support classifier reports per-language and dialect confusion metrics against a keyword baseline and sends uncertain high-cost cases to review.",
    scenarioB: "A translation system with a good average score mistranslates negation in one domain, so targeted human evaluation blocks deployment there.",
    misconception: "One English benchmark or text-overlap metric establishes that an NLP system understands language and works for all dialects.",
    correction: "Frame the exact language task and population, evaluate task-specific errors and coverage slices, and include qualified human review where metrics miss meaning or harm.",
    checkpoint: "coverage slices",
  },
  "ai.applications.vision": {
    model: "Computer vision maps sensed pixel arrays through representations to tasks such as classification, detection, or segmentation; labels and evaluation are conditional on capture conditions and decision policy.",
    boundary: "Pixels omit physical context, lighting/viewpoint/sensor changes shift data, labels can be subjective, aggregate accuracy hides slices, adversarial or accidental artifacts can dominate, and perception is not causal understanding.",
    scenarioA: "A defect detector is tested by camera, lighting, angle, product type, and defect size, with missed-critical-defect rate prioritized over headline accuracy.",
    scenarioB: "A model keys on a background marker correlated with class in training, so occlusion and changed-background tests expose shortcut learning.",
    misconception: "High test accuracy proves a vision model recognizes the intended object features and will remain reliable under ordinary camera changes.",
    correction: "Evaluate sensing conditions, shortcuts, subgroup and rare-case slices, calibration, and operational failure costs; pixel prediction does not prove intended perception.",
    checkpoint: "sensing conditions",
  },
  "ai.applications.robotics": {
    model: "A robotic system links sensing, state estimation, planning, control, and actuation in a physical feedback loop with explicit safe states, limits, human roles, and fallback behavior.",
    boundary: "Simulation omits friction and rare events, sensors fail, latency destabilizes control, plans can be valid but unsafe, physical actions are not instantly reversible, and learning must remain inside safety constraints.",
    scenarioA: "A mobile robot slows on uncertain localization, stops on sensor disagreement, and requires human clearance before leaving a mapped area.",
    scenarioB: "A simulation policy scores well but collides after wheel slip, so hardware testing proceeds through bounded speed and emergency-stop stages.",
    misconception: "A planner or learned policy that succeeds in simulation can control a real robot safely once sensors are connected.",
    correction: "Validate the complete perception-to-actuation loop under bounded physical tests, enforce independent safety limits, and define stop, fallback, and human escalation paths.",
    checkpoint: "independent safety limits",
  },
  "ai.applications.multimodal": {
    model: "A multimodal system aligns and combines information from text, image, audio, or other channels, while each modality and their joint interaction require separate provenance, missingness, quality, and error evaluation.",
    boundary: "One modality can dominate, timestamps or identities can misalign, generated cross-modal claims can be unsupported, missing channels change behavior, accessibility differs, and more modalities do not guarantee truth.",
    scenarioA: "A document assistant links each extracted claim to both page image region and recognized text, then tests OCR, layout, and joint-answer errors separately.",
    scenarioB: "Audio is missing for one population, so the fallback is evaluated as its own system rather than silently substituting a lower-quality path.",
    misconception: "Combining text and images lets each modality verify the other automatically, making hallucination and provenance less important.",
    correction: "Track alignment and provenance per modality, test modality-specific, missing-modality, and joint failures, and never treat cross-modal agreement as automatic verification.",
    checkpoint: "missing-modality",
  },
  "ai.generative.language-model": {
    model: "A language model represents text as tokens and estimates a conditional distribution for the next token from finite context; decoding repeatedly samples or selects from those distributions.",
    boundary: "Tokenization is model-specific, context is finite, probabilities are not truth scores, training data is not a queryable citation database, decoding changes variability, and fluent continuation does not prove reasoning or understanding.",
    scenarioA: "A toy bigram table assigns different next-token probabilities after one context token and greedy versus sampled decoding produces different valid continuations.",
    scenarioB: "The model confidently states an unsupported date because plausible token continuation is not evidence retrieval or source verification.",
    misconception: "An LLM retrieves the most relevant stored sentence and its next-token probability measures whether the resulting claim is true.",
    correction: "Interpret generation as conditional token prediction within finite context; verify factual claims against authorized sources and do not treat model probability as truth.",
    checkpoint: "conditional token prediction",
  },
  "ai.generative.prompt-output": {
    model: "A prompt-plus-validator workflow defines task, authorized context, constraints, untrusted-data boundaries, and an output schema, then treats every generated field as untrusted until deterministic validation and policy checks pass.",
    boundary: "Prompt wording cannot guarantee compliance, schema validity does not make content factual or safe, adversarial context can inject instructions, retries can add cost or inconsistency, and some decisions require human review.",
    scenarioA: "A model is asked for bounded JSON, the application parses exact fields, rejects extras and invalid ranges, and separately verifies cited identifiers.",
    scenarioB: "Retrieved text says to ignore prior rules; it remains quoted data and cannot alter tool permissions or output policy.",
    misconception: "A detailed system prompt or JSON mode guarantees correct, safe, schema-compliant output without application validation.",
    correction: "Separate instructions from untrusted context and validate syntax, schema, semantics, authorization, and citations outside the model before use.",
    checkpoint: "outside the model",
  },
  "ai.generative.embeddings-rag": {
    model: "Retrieval-augmented generation indexes versioned source chunks, retrieves candidates for a query, supplies bounded passages to generation, and evaluates retrieval relevance plus answer grounding as separate stages.",
    boundary: "Embeddings encode similarity not truth, chunking loses context, relevant passages can be missed, retrieved text can be stale or malicious, context limits apply, and generation can ignore or distort evidence.",
    scenarioA: "A small corpus returns top passages with document/version/locator metadata, and the answer must cite only claims supported by those exact passages.",
    scenarioB: "The correct document is absent from top-k, so the failure is recorded as retrieval miss rather than blamed solely on generation.",
    misconception: "RAG prevents hallucination because embeddings retrieve true facts and the model must follow whatever appears in retrieved context.",
    correction: "Treat retrieval and generation as fallible, keep source provenance and authorization, resist instructions inside content, and score retrieval coverage separately from grounded answering.",
    checkpoint: "retrieval coverage separately",
  },
  "ai.generative.api-safety": {
    model: "A safe model/tool integration keeps credentials server-side, minimizes disclosed data, binds calls to user intent and authorization, validates typed tool arguments, restricts destinations and side effects, and audits outcomes.",
    boundary: "Model output is untrusted, prompt injection can arrive through any data channel, provider changes alter disclosure, retries can duplicate effects, allowlists can be bypassed by weak parsing, and human approval has usability limits.",
    scenarioA: "A mocked scheduling tool accepts one typed date and approved calendar id, rejects unknown fields and external URLs, and requires confirmation before mutation.",
    scenarioB: "A document tells the agent to reveal its API key; content remains data, the key is never in model context, and no reveal tool exists.",
    misconception: "A trusted provider or system prompt makes tool arguments safe, so the application can execute model-produced JSON directly.",
    correction: "Keep secrets and authority outside model context, parse and authorize every tool call deterministically, bind side effects to confirmation and idempotency, and audit the result.",
    checkpoint: "authorize every tool call",
  },
  "ai.evaluation.metrics": {
    model: "Evaluation chooses metrics, thresholds, baselines, slices, and uncertainty from the task and decision costs; a metric summarizes selected errors rather than establishing overall quality.",
    boundary: "Metrics trade off, averages hide tails and groups, generated-output metrics are partial, threshold tuning can overfit, confidence intervals rely on sampling assumptions, and benchmark contamination inflates evidence.",
    scenarioA: "A rare-event classifier table includes prevalence, confusion counts, precision, recall, threshold, baseline, and bootstrap interval rather than accuracy alone.",
    scenarioB: "A generation system has overlap and human groundedness results with disagreements reported, because neither measure alone captures correctness and usefulness.",
    misconception: "The model with the highest single benchmark score is best, and a metric improvement proves practical significance for every user.",
    correction: "Predeclare decision-relevant metrics and baselines, report thresholds, uncertainty, slices, and failure examples, and limit claims to the evaluated population and conditions.",
    checkpoint: "limit claims",
  },
  "ai.evaluation.robustness": {
    model: "Robustness evaluation defines plausible shifts, malformed inputs, rare conditions, abuse cases, adversarial manipulations, and monitoring triggers, then measures degradation and safe failure rather than one in-distribution score.",
    boundary: "No finite test proves robustness, adversaries adapt, synthetic perturbations may be unrealistic, drift labels arrive late, monitoring can miss silent harms, and recovery controls need exercises.",
    scenarioA: "A text classifier is stressed with empty, long, misspelled, multilingual, duplicated, and prompt-like inputs, with explicit reject behavior and slice deltas.",
    scenarioB: "After a source/version change, a monitoring trigger detects calibration drift and routes decisions to review while retraining evidence is gathered.",
    misconception: "Passing a standard adversarial test suite certifies robustness against future shifts and attacks.",
    correction: "Maintain a living threat- and shift-based stress matrix, quantify degradation, define safe fallback and monitoring triggers, and update tests after incidents.",
    checkpoint: "living threat- and shift-based stress matrix",
  },
  "ai.evaluation.fairness-explain": {
    model: "Fairness analysis selects relevant groups, outcomes, error rates, allocation effects, and stakeholder values; explanations describe bounded model behavior for a named audience and are validated for fidelity and usefulness.",
    boundary: "Fairness criteria can conflict, protected attributes can have proxies, small slices have uncertainty, equal metrics do not erase structural harm, feature importance is not causation, and plausible explanations can be unfaithful.",
    scenarioA: "An approval model reports selection, false-negative, and calibration slices with confidence ranges, then documents an unresolved trade-off and appeal path.",
    scenarioB: "A local feature attribution is described as sensitivity around one prediction, not proof that changing the feature will cause a changed real-world outcome.",
    misconception: "Removing protected attributes makes a model fair, and an explanation chart proves why the real-world outcome happened.",
    correction: "Audit outcomes and errors with relevant groups and proxy risks, state fairness trade-offs, and label explanations by scope, audience, fidelity, and causal limits.",
    checkpoint: "causal limits",
  },
  "ai.risk.lifecycle": {
    model: "NIST AI RMF organizes continuous risk work through Govern, Map, Measure, and Manage: assign accountability, understand context, assess prioritized risks, apply controls, monitor, respond, and document residual risk.",
    boundary: "The functions are not a one-time checklist or ordered certification, risk tolerance is contextual, measurement can be incomplete, third parties share responsibility, and controls need owners and evidence.",
    scenarioA: "A risk register names affected stakeholders, owner, scenario, likelihood/impact evidence, preventive and detective controls, residual risk, monitor, and stop criterion.",
    scenarioB: "A model metric remains strong but a new incident crosses an impact stop threshold, so use pauses under the governance policy.",
    misconception: "Completing an AI RMF checklist certifies an AI system as safe and transfers responsibility to the framework.",
    correction: "Use Govern, Map, Measure, and Manage as continuous context-specific functions with accountable owners, evidence, controls, residual risk, and stop decisions.",
    checkpoint: "continuous context-specific functions",
  },
  "ai.project.design": {
    model: "An AI project card defines users and affected non-users, decision context, target or task, data authority, baseline, metrics, slices, risks, non-goals, oversight, acceptance thresholds, and stop criteria before fitting.",
    boundary: "A technical prototype may not improve the decision, available data may be unauthorized or unrepresentative, acceptance metrics can conflict, scope can expand silently, and project cancellation is a valid outcome.",
    scenarioA: "A ticket-routing card names intake-time prediction, reviewer workload baseline, urgent-miss tolerance, excluded decisions, data retention, appeal, and a stop rule for subgroup harm.",
    scenarioB: "The team declines a model when a deterministic queue rule meets the outcome with lower privacy and operational risk.",
    misconception: "A project plan should start with the most promising model and add users, metrics, and risks after a prototype demonstrates accuracy.",
    correction: "Define the decision, stakeholders, data authority, baseline, evidence plan, non-goals, risks, acceptance, and stop criteria before model fitting.",
    checkpoint: "before model fitting",
  },
  "ai.project.reproducibility": {
    model: "A reproducible AI pipeline records code, environment, data and split versions, preprocessing, configuration, seeds, fit artifacts, evaluation outputs, and commands while separating fit, evaluation, and reporting.",
    boundary: "Hardware and parallel libraries can remain nondeterministic, external data changes, seeds do not capture every source, cached state can hide steps, and exact repeatability differs from independently consistent results.",
    scenarioA: "A clean environment rebuilds a pinned pipeline from a data checksum and split manifest, reproduces metrics within a declared tolerance, and stores the report with artifact hashes.",
    scenarioB: "Two GPU runs differ slightly despite one seed, so versions, deterministic settings, and variation are recorded rather than claiming bitwise identity.",
    misconception: "Setting random_state once is sufficient to reproduce any ML experiment on another machine.",
    correction: "Version code, environment, data, split, configuration, and artifacts, record all controllable seeds, and report remaining platform or algorithmic nondeterminism.",
    checkpoint: "data, split, configuration",
  },
  "ai.project.model-card": {
    model: "A model card links intended use, exclusions, users, data, training/evaluation procedure, metrics and slices, limitations, ethical/risk considerations, monitoring, human oversight, and escalation to recorded evidence.",
    boundary: "Documentation can become stale, aggregate metrics hide failures, intended use does not prevent misuse, proprietary gaps reduce review, human oversight needs authority and capacity, and a card is not certification.",
    scenarioA: "Every performance claim cites a versioned evaluation table and date, while known unsupported languages and prohibited high-stakes uses appear prominently.",
    scenarioB: "A new deployment population falls outside evaluated scope, so the card blocks reuse pending mapping and testing instead of inheriting old claims.",
    misconception: "Publishing a model card makes a model transparent, fair, and safe even when evidence is incomplete or deployment changes.",
    correction: "Keep model-card claims traceable to versioned evidence, name exclusions and uncertainty, and connect oversight, monitoring, escalation, and update ownership.",
    checkpoint: "traceable to versioned evidence",
  },
  "ai.project.capstone": {
    model: "An AI foundations capstone implements a modest bounded system, compares a simple baseline, preserves data/source provenance, evaluates normal and stress cases, documents limitations and risks, and supports reproducible review.",
    boundary: "A demo is not deployment evidence, external model output is nondeterministic, test data may be small, RAG and agents add separate failure surfaces, automation may not be justified, and unfinished risks must remain visible.",
    scenarioA: "A local search or retrieval prototype includes a deterministic baseline, versioned corpus, held-out queries, failure taxonomy, risk register, model card, and exact reproduction commands.",
    scenarioB: "The capstone reports that evidence is insufficient for autonomous action and keeps a human confirmation step rather than overstating completion.",
    misconception: "A polished AI demo with a strong average score is a complete capstone and can be described as production-ready.",
    correction: "Deliver bounded implementation plus baseline, reproducibility, provenance, evaluation slices, stress failures, oversight, risk controls, and claims limited to the recorded evidence.",
    checkpoint: "claims limited",
  },
} as const satisfies Readonly<Record<string, AiTeachingSeed>>;
