import type { TrancheTeachingSeed } from "./foundations-git-tranche";

export interface LanguageTeachingSeed extends TrancheTeachingSeed {
  /** Exact substring of correction used for a deterministic fill-gap item. */
  readonly checkpoint: string;
}

export const C_CPP_TRANCHE_SEEDS = {
  "c.toolchain.program": {
    model: "A hosted C program starts through a conforming main definition, returns an integer termination status, and receives arguments only through a declared supported main signature.",
    boundary: "Freestanding implementations can define a different entry environment, and operating systems interpret status values beyond portable success and failure conventions differently.",
    scenarioA: "A minimal hosted program declares int main(void), prints one line, and returns zero after successful completion.",
    scenarioB: "A command-line program validates argc before reading argv[1] and returns a nonzero status when the required argument is absent.",
    misconception: "C programs may use void main because ignoring a result is equivalent to returning a valid termination status.",
    correction: "For a portable hosted program, define int main(void) or a supported argument form and return an integer status; void main is not a portable hosted definition.",
    checkpoint: "int main(void)",
  },
  "c.toolchain.phases": {
    model: "C source passes through preprocessing, translation to object code, and linking with required definitions before the operating environment can load an executable.",
    boundary: "Toolchains can combine phases, perform link-time optimization, or emit intermediate forms, but preprocessing and translation rules still determine observable program meaning.",
    scenarioA: "A macro and include directive are handled before the compiler checks expressions and emits an object file, then the linker resolves printf from the C library.",
    scenarioB: "Each source file compiles successfully, but the final link fails because one declared function has no definition in any linked object.",
    misconception: "If every .c file compiles without error, the complete program must already be executable.",
    correction: "Successful compilation produces translation-unit objects; the linker must still resolve every required external definition before an executable exists.",
    checkpoint: "linker",
  },
  "c.toolchain.diagnostics": {
    model: "A diagnostic identifies a violated syntax or constraint or a tool-detected risk; its phase, primary location, severity, and first causal message guide repair.",
    boundary: "Warnings are tool-configurable, one cause can cascade into many messages, and no diagnostic is required for every undefined or incorrect behavior.",
    scenarioA: "A missing semicolon causes a parser diagnostic near the following token, so the learner inspects the preceding statement before changing unrelated code.",
    scenarioB: "Strict warnings report an implicit narrowing or suspicious comparison even though object code could be emitted, prompting an explicit correctness review.",
    misconception: "A program with no compiler warnings is guaranteed to be defined, correct, and portable.",
    correction: "Treat clean diagnostics as bounded tool evidence, not proof; compile with strict warnings and still test behavior, contracts, portability, and undefined-behavior risks.",
    checkpoint: "strict warnings",
  },
  "c.toolchain.headers": {
    model: "A header exposes declarations, types, and macros shared by translation units, while non-inline external definitions normally belong in exactly one source file.",
    boundary: "Header inclusion is textual, macro state and order matter, and incorrect tentative or external definitions can create duplicate symbols or inconsistent declarations.",
    scenarioA: "A project header declares int total(const int *values, size_t count) and each caller includes it while one .c file defines the function.",
    scenarioB: "An include guard prevents repeated declarations when two headers include the same shared type header through different paths.",
    misconception: "Including a header automatically links a library implementation and makes every declared function definition available.",
    correction: "A header supplies compile-time declarations; the matching object or library definition must also be linked, and declarations must remain compatible.",
    checkpoint: "compile-time declarations",
  },
  "c.types.scalar": {
    model: "C scalar types include integer, real floating, complex where supported, Boolean, enumeration, and pointer types, each with implementation-defined representation and operation rules.",
    boundary: "Widths, signed representation details, plain char signedness, floating formats, alignment, and pointer representation vary by implementation despite minimum standard guarantees.",
    scenarioA: "An object count uses size_t because it represents object sizes and array bounds rather than assuming unsigned int has the same range.",
    scenarioB: "A byte read through unsigned char preserves all possible object-representation byte values without negative plain-char surprises.",
    misconception: "C guarantees int is exactly 32 bits and plain char is always signed on every supported system.",
    correction: "Use limits and fixed-width types only when their documented guarantees fit; sizeof and the implementation headers describe actual scalar ranges and widths.",
    checkpoint: "sizeof",
  },
  "c.types.literals-format": {
    model: "Literal spelling and suffix select a candidate type, while formatted input and output require a conversion specification compatible with the actual argument pointer or promoted value type.",
    boundary: "Integer literal bases change candidate lists, variadic arguments undergo promotions, and mismatched printf or scanf specifications can produce undefined behavior.",
    scenarioA: "A size_t value is printed with %zu rather than guessing that it has the same type as unsigned long on every target.",
    scenarioB: "A uint64_t value uses the matching PRIu64 macro from inttypes.h when portable fixed-width formatting is required.",
    misconception: "Any integer can safely be printed with %d because printf converts numeric argument types automatically.",
    correction: "Match each format conversion to the promoted argument type; use %zu for size_t and standard format macros where fixed-width types require them.",
    checkpoint: "%zu",
  },
  "c.types.operators": {
    model: "C operators form expressions according to precedence, associativity, operand types, value computations, side effects, and sequencing rules.",
    boundary: "Precedence does not specify every evaluation order, signed overflow is undefined, and modifying and reading one scalar without required sequencing can be undefined.",
    scenarioA: "The expression a + b * c groups multiplication first, while parentheses communicate and enforce a different intended grouping.",
    scenarioB: "A condition ready && use_value() avoids the function call when ready is zero because logical AND sequences and short-circuits its right operand.",
    misconception: "Higher precedence means an operand is always evaluated earlier in time than every lower-precedence operand.",
    correction: "Use precedence to determine grouping, not general evaluation order; rely only on documented sequencing and avoid multiple unsequenced accesses with side effects.",
    checkpoint: "grouping",
  },
  "c.types.conversions": {
    model: "C applies integer promotions and usual arithmetic conversions before many operations, then assignment or casts can convert the result to a destination type.",
    boundary: "Signed-to-unsigned conversion is modulo the unsigned range, narrowing can lose information, and out-of-range floating or pointer conversions have separate rules.",
    scenarioA: "Comparing negative int -1 with unsigned int 1 can convert the negative operand to a large unsigned value and reverse a beginner's expected ordering.",
    scenarioB: "Dividing two int operands truncates before assignment to double, while converting one operand to double requests floating division.",
    misconception: "The destination variable's type controls how the entire right-hand expression is evaluated from the beginning.",
    correction: "Trace integer promotions and usual arithmetic conversions first, then apply the final assignment conversion; cast before an operation only when that semantic change is intended.",
    checkpoint: "integer promotions",
  },
  "c.control.selection": {
    model: "C selection uses scalar conditions where zero is false and nonzero is true, with if/else binding and switch case labels determining one control path.",
    boundary: "Floating comparisons, fallthrough, duplicate or unreachable cases, dangling else layout, and side effects in conditions can make branches surprising.",
    scenarioA: "An if/else-if chain handles negative, zero, and positive values in mutually exclusive branches and tests both boundaries.",
    scenarioB: "A switch groups two case labels intentionally and uses break to prevent execution from falling into the next unrelated action.",
    misconception: "Every switch case stops automatically when its statements finish, even without break or another control transfer.",
    correction: "A switch continues into following labels unless control transfers; use break or an explicit documented fallthrough when that behavior is intended.",
    checkpoint: "break",
  },
  "c.control.loops": {
    model: "C for, while, and do loops repeatedly evaluate defined control expressions, and correct loops maintain an invariant while making progress toward termination.",
    boundary: "Unsigned countdown, one-past array bounds, continue paths, mutation of control state, and empty input commonly break progress or coverage.",
    scenarioA: "A zero-based for loop visits indexes 0 through count - 1 using i < count and performs zero iterations when count is zero.",
    scenarioB: "A do loop reads at least one menu choice before testing whether the user selected quit, matching the required first interaction.",
    misconception: "The condition i <= count is the normal way to visit every element of an array with count elements.",
    correction: "For zero-based count elements, iterate while i < count; count itself is one past the last valid index.",
    checkpoint: "i < count",
  },
  "c.control.jump": {
    model: "break exits the nearest loop or switch, continue advances the nearest loop to its next iteration step, return leaves a function, and goto transfers within one function.",
    boundary: "Transfers can skip initialization or cleanup logic, nested constructs change the nearest target, and goto cannot enter scopes incompatibly with variably modified objects.",
    scenarioA: "A nested search uses a flag or helper return because break exits only the inner loop rather than both loop levels.",
    scenarioB: "A single cleanup label releases resources acquired along several failure paths before the function returns one status.",
    misconception: "break exits the current function and continue restarts the complete program from its first statement.",
    correction: "break targets the nearest loop or switch, continue targets the nearest loop, and return is the transfer that exits the current function.",
    checkpoint: "return",
  },
  "c.control.input": {
    model: "Robust C input checks each function's return result, distinguishes token from line input, bounds every destination, and handles leftover or invalid characters deliberately.",
    boundary: "scanf conversion failure can leave input unread, fgets retains a newline when space permits, EOF differs from an empty line, and locale can affect conversions.",
    scenarioA: "A line is read with fgets into a bounded array, its newline is handled, and strtol validates complete numeric conversion and range.",
    scenarioB: "A scanf call checks that exactly one integer conversion succeeded before using the destination object.",
    misconception: "scanf with %s or %d always writes a usable value, so its return result and destination width can be ignored.",
    correction: "Check the input function's return value before reading destinations and provide explicit bounds such as fgets capacity or a width-limited string conversion.",
    checkpoint: "return value",
  },
  "c.functions.prototype": {
    model: "A function prototype declares return and parameter types so calls can be checked and arguments converted according to the declared interface before the definition is seen.",
    boundary: "Old-style unspecified parameter lists differ from a void parameter list, variadic arguments receive less checking, and incompatible declarations across units make behavior undefined.",
    scenarioA: "The header declaration double average(const int *values, size_t count) is visible at every call and matches one external definition.",
    scenarioB: "A no-argument function is declared reset(void), explicitly stating that it accepts no parameters in C.",
    misconception: "Writing reset() in a C declaration always means the function takes no arguments, exactly like reset(void).",
    correction: "In a C prototype, use (void) to declare no parameters; an empty parameter list does not provide the same prototype information.",
    checkpoint: "(void)",
  },
  "c.functions.parameters": {
    model: "C passes argument values into parameter objects; a pointer value can let a function access caller-owned objects, but the pointer itself is still passed by value.",
    boundary: "Array parameters adjust to pointers, object lifetime and const qualification constrain access, and aliasing can make writes through two pointers interact.",
    scenarioA: "A swap function receives pointers to two int objects and writes through them, while reassigning only its local pointer parameters would not change caller pointers.",
    scenarioB: "A read-only sum function accepts const int * plus a size_t count and cannot modify elements through that pointer.",
    misconception: "C passes variables by reference whenever their names are used as function arguments.",
    correction: "C passes by value; pass an address explicitly when the function must access caller-owned storage, then validate lifetime and nullability.",
    checkpoint: "passes by value",
  },
  "c.functions.scope-storage": {
    model: "Scope controls name visibility, linkage connects declarations across translation units, and storage duration controls object lifetime independently of those name rules.",
    boundary: "Block-scope static objects retain state, extern declarations do not allocate a new definition, and thread storage or tentative definitions add further cases.",
    scenarioA: "A block automatic counter is created on each call, while a block static counter retains its value across calls but remains named only inside the function.",
    scenarioB: "A file-scope static helper has internal linkage and cannot be named as the same entity from another translation unit.",
    misconception: "A static local variable is globally visible because it lives for the entire program.",
    correction: "A block-scope static object has static storage duration but block scope; lifetime does not widen where its name is visible.",
    checkpoint: "block scope",
  },
  "c.functions.recursion": {
    model: "A recursive C function requires a reachable base case and a call argument that progresses toward it, with each active call owning separate automatic objects.",
    boundary: "The C standard does not guarantee tail-call optimization, deep recursion can exhaust resources, and unsigned progress can wrap away from a base case.",
    scenarioA: "A factorial function handles n <= 1 directly and calls factorial(n - 1) only for positive bounded input.",
    scenarioB: "A recursive linked-list length handles a null pointer as zero and advances to next on every recursive call.",
    misconception: "Tail-recursive C code is guaranteed to use constant stack space because the recursive call appears last.",
    correction: "C does not guarantee tail-call optimization; prove progress and prefer iteration when required depth can exceed safe implementation limits.",
    checkpoint: "does not guarantee tail-call optimization",
  },
  "c.arrays.one-dimensional": {
    model: "A C array is a contiguous fixed-size sequence of elements; array expressions often convert to pointers to the first element, but the array object and pointer are not the same type.",
    boundary: "No runtime bounds check is required, sizeof differs before and after parameter adjustment, and one-past pointers may be compared but not dereferenced.",
    scenarioA: "An int values[4] has valid indexes zero through three, and sizeof values in its defining scope includes storage for all four elements.",
    scenarioB: "When passed to a function parameter, values does not carry its element count, so a separate size_t count is supplied.",
    misconception: "An array argument tells the called function its length automatically because the bracket size remains part of the parameter.",
    correction: "Array parameters adjust to pointer parameters; pass the element count separately and enforce every index against that count.",
    checkpoint: "pass the element count separately",
  },
  "c.arrays.multidimensional": {
    model: "A multidimensional C array is an array of arrays stored in row-major order, and pointer arithmetic requires the inner dimensions to determine each row's stride.",
    boundary: "Variable-length arrays are optional in some later implementations, dynamically allocated flat buffers use a different type, and irregular rows require pointer-based structures.",
    scenarioA: "An int grid[2][3] stores three contiguous int elements in each of two contiguous rows, and grid[r][c] selects row then column.",
    scenarioB: "A function receiving a 2D array declares the column bound so advancing one row skips exactly that many elements.",
    misconception: "A pointer to int can always be used as an int two-dimensional array without carrying or computing row stride.",
    correction: "Preserve the inner dimension in the pointer type or flatten deliberately with an explicit row-stride calculation.",
    checkpoint: "row-stride",
  },
  "c.strings.representation": {
    model: "A C string is a character sequence terminated by the first null character, stored within an array or other valid region large enough for content plus the terminator.",
    boundary: "Character arrays need not contain a string, embedded nulls end string operations early, string literals are not modifiable, and encoding can use multibyte sequences.",
    scenarioA: "The array {'c','a','t','\\0'} is a four-byte representation of the three-character C string cat.",
    scenarioB: "char label[3] = {'c','a','t'} is an array but not a C string because no null terminator fits.",
    misconception: "Every char array is automatically null-terminated and safe to pass to strlen or printf with %s.",
    correction: "Before using string functions, prove that a null terminator occurs within the valid array bounds and keep capacity for it.",
    checkpoint: "null terminator",
  },
  "c.strings.operations": {
    model: "C string operations require a valid terminated source, a destination with enough capacity, and explicit handling of lengths, truncation, overlap, and conversion errors.",
    boundary: "strlen excludes the terminator, strncpy may not terminate, concatenation needs remaining capacity, and byte length can differ from displayed character count.",
    scenarioA: "A bounded line read tracks the array capacity, removes an optional newline, and verifies termination before measuring or copying.",
    scenarioB: "Before appending, code checks that destination length plus source length plus one does not exceed destination capacity.",
    misconception: "strncpy always creates a null-terminated string and therefore makes arbitrary source text safe.",
    correction: "Do not assume strncpy terminates; design from destination capacity, validate source bounds, and establish the terminator explicitly when needed.",
    checkpoint: "destination capacity",
  },
  "c.pointers.address": {
    model: "A pointer value designates an object or function, one-past position, or null; dereference is valid only when the designation, lifetime, alignment, and access type permit it.",
    boundary: "Uninitialized, dangling, misaligned, out-of-bounds, incorrectly converted, or null pointers cannot be made safe merely by checking their numeric appearance.",
    scenarioA: "The address of a live int is passed to a helper, checked against null by contract, and dereferenced only before that int's lifetime ends.",
    scenarioB: "Returning the address of an automatic local creates a dangling pointer once the function returns and its object lifetime ends.",
    misconception: "Any non-null pointer is safe to dereference because null is the only invalid address value.",
    correction: "Dereference requires a pointer to a live compatible object within bounds; non-null alone does not establish provenance, lifetime, alignment, or access validity.",
    checkpoint: "live compatible object",
  },
  "c.pointers.arrays": {
    model: "Within one array object, pointer addition advances by elements and comparisons can include the one-past pointer, while dereference remains limited to actual elements.",
    boundary: "Arithmetic across unrelated objects is not defined, one-past may not be dereferenced, and array-to-pointer conversion loses total length information.",
    scenarioA: "A loop advances int *p from values to values + count, stopping before p equals the one-past endpoint.",
    scenarioB: "Subtracting two pointers into the same array yields an element distance, but subtracting pointers into separate arrays is not a portable distance.",
    misconception: "Pointer arithmetic counts bytes for every pointer type and can traverse freely between separately allocated objects.",
    correction: "Pointer arithmetic is scaled by the pointed-to type and is defined only within one array object plus its one-past position.",
    checkpoint: "one-past position",
  },
  "c.pointers.const": {
    model: "C const qualification can protect the pointed-to object through one access path, the pointer object itself, or both, depending on declarator placement.",
    boundary: "const does not make an originally mutable object globally immutable, casts can discard qualifiers unsafely, and nested pointer qualification has stricter compatibility rules.",
    scenarioA: "const int *p permits p to select another int but prevents modifying an int through p.",
    scenarioB: "int * const p keeps p fixed on one int while permitting modification of that int through p.",
    misconception: "const int * and int * const mean the same thing because both contain the word const.",
    correction: "Read the declarator from the identifier: const int * protects the pointee through that path, while int * const makes the pointer itself nonassignable.",
    checkpoint: "const int *",
  },
  "c.pointers.functions": {
    model: "A function pointer has a compatible function type and can select behavior at runtime, but calls remain valid only when return and parameter types match the pointed-to function.",
    boundary: "Object and function pointers are not generally interchangeable, casts do not repair incompatible call types, and callback context often needs a separate void pointer contract.",
    scenarioA: "A transform function receives int (*operation)(int) and calls either square or negate through the compatible pointer.",
    scenarioB: "A comparison callback uses the exact library-required signature and converts context data only under a documented object-pointer contract.",
    misconception: "Casting any function address to the requested pointer type makes an incompatible callback call safe.",
    correction: "The actual function and pointer call type must be compatible; a cast can silence a diagnostic but cannot create a valid calling convention.",
    checkpoint: "compatible",
  },
  "c.aggregates.struct": {
    model: "A structure groups ordered named members in one object, may contain padding for alignment, and supports whole-structure assignment and value passing when types match.",
    boundary: "Padding bytes can be indeterminate, member layout has implementation constraints, flexible array members need special allocation, and bytewise comparison is not field equality.",
    scenarioA: "A struct Point stores named x and y members, is initialized with designated initializers, and is copied by structure assignment.",
    scenarioB: "Two logically equal structures are compared member by member rather than with memcmp because padding bytes need not match.",
    misconception: "memcmp is always a correct equality test for structures because all members occupy one contiguous object.",
    correction: "Compare structure values by their meaningful members; padding can differ or be indeterminate even when every member value is equal.",
    checkpoint: "meaningful members",
  },
  "c.aggregates.enum": {
    model: "An enumeration declares named integer constants and an enumerated type, improving domain vocabulary while remaining subject to implementation integer representation rules.",
    boundary: "C enums do not automatically reject every out-of-domain integer conversion, underlying representation can vary, and duplicate enumerator values are possible.",
    scenarioA: "enum Status names STATUS_PENDING, STATUS_READY, and STATUS_FAILED so a switch can communicate domain cases clearly.",
    scenarioB: "Input is validated before converting an arbitrary integer to an enum-backed state because not every integer names a declared enumerator.",
    misconception: "A C enum is a runtime-checked closed set that can never hold a value outside its listed enumerators.",
    correction: "Use enums for named integral states but validate external values explicitly; the type alone is not a universal runtime membership check.",
    checkpoint: "validate external values explicitly",
  },
  "c.aggregates.union": {
    model: "A union provides overlapping storage for alternative members; code must track which representation is active or otherwise permitted before reading a member.",
    boundary: "Reading a non-current member has limited implementation-defined or specified cases, padding and trap representations matter, and a union is not a self-tagging variant.",
    scenarioA: "A tagged value stores an enum kind beside a union and reads integer or floating member only when the tag names that member.",
    scenarioB: "Writing the double member and then assuming the int member contains a portable bit conversion is rejected.",
    misconception: "A union remembers which member was last written and prevents code from reading the wrong alternative.",
    correction: "A C union is not self-tagging; maintain and validate a separate discriminator before interpreting the overlapping storage.",
    checkpoint: "separate discriminator",
  },
  "c.aggregates.typedef": {
    model: "A typedef introduces an alias for an existing type, simplifying declarations without creating a distinct type or changing representation and compatibility.",
    boundary: "Aliases can hide pointer constness or ownership expectations, names share ordinary identifier namespaces, and opaque interfaces require incomplete structure techniques beyond a simple alias.",
    scenarioA: "typedef unsigned long Counter creates the alias Counter, but Counter and unsigned long remain compatible names for the same type.",
    scenarioB: "typedef struct Node Node shortens self-referential declarations while the structure tag and typedef name occupy different namespaces.",
    misconception: "A typedef creates a new strongly distinct type that prevents accidental mixing with its underlying type.",
    correction: "typedef creates a type alias, not a new distinct type; enforce domain separation through APIs, structures, and validation rather than the alias alone.",
    checkpoint: "type alias",
  },
  "c.memory.lifetime": {
    model: "An object's storage duration and lifetime determine when storage exists and values may be accessed; pointers do not extend the lifetime of the objects they designate.",
    boundary: "Automatic, static, thread, and allocated storage have different start and end rules, and effective type or indeterminate values can invalidate access even while bytes exist.",
    scenarioA: "A pointer to a block automatic array becomes dangling when execution leaves that block even if the address bits remain unchanged.",
    scenarioB: "Allocated storage remains until free, but every pointer to it becomes invalid for access immediately after deallocation.",
    misconception: "Keeping a pointer variable alive keeps its pointed-to object alive as well.",
    correction: "Track object lifetime independently from pointer lifetime; a surviving pointer can be dangling after scope exit or free.",
    checkpoint: "object lifetime",
  },
  "c.memory.allocate": {
    model: "Dynamic allocation requests a byte region with suitable alignment, checks failure, establishes objects through valid access, and pairs each owned allocation with exactly one eventual free.",
    boundary: "Size multiplication can overflow, realloc can move or fail while preserving the old block, zero-size requests are special, and allocation does not initialize ordinary bytes.",
    scenarioA: "Before malloc(count * sizeof *items), code checks count against SIZE_MAX / sizeof *items and verifies the returned pointer before use.",
    scenarioB: "A temporary pointer receives realloc so failure does not overwrite and leak the still-valid original allocation.",
    misconception: "malloc initializes every allocated element to zero and realloc failure frees the original block automatically.",
    correction: "malloc returns uninitialized storage and realloc failure leaves the original block allocated; check sizes and results before changing the owning pointer.",
    checkpoint: "uninitialized storage",
  },
  "c.files.streams": {
    model: "C streams represent formatted or binary I/O state; code opens with an intentional mode, checks every operation, distinguishes EOF from error, and closes owned streams.",
    boundary: "Text translation, buffering, seek support, update-stream direction changes, encoding, and filesystem errors vary by implementation and stream kind.",
    scenarioA: "A file is opened for reading, fgets results are checked in a loop, feof and ferror distinguish completion from failure, and fclose is checked.",
    scenarioB: "Binary data uses fread element counts and handles a short read rather than assuming the requested byte count always arrives.",
    misconception: "A null result from a read always means normal end-of-file and does not require checking stream error state.",
    correction: "After a read stops, distinguish EOF from error with the stream state and validate the number of elements actually transferred.",
    checkpoint: "distinguish EOF from error",
  },
  "c.resources.cleanup": {
    model: "C resource management assigns clear ownership and routes every success or failure path through cleanup that releases each acquired resource once in reverse dependency order.",
    boundary: "Early returns, partially initialized aggregates, callbacks, signals, and ownership transfer complicate cleanup and require explicit state flags or helper abstractions.",
    scenarioA: "A function opens a file, allocates a buffer, and on any later failure jumps to one cleanup section that frees the buffer then closes the file.",
    scenarioB: "A pointer is set to null after ownership transfers so the former owner does not free the same allocation twice.",
    misconception: "The operating system eventually reclaims resources, so cleanup on error paths is unnecessary in a C program.",
    correction: "Release every owned resource on every path; process cleanup is not a substitute for bounded files, locks, memory, or long-running correctness.",
    checkpoint: "every path",
  },
  "c.modular.headers": {
    model: "A C module boundary places stable public declarations and documented contracts in a header and keeps private helpers and representations inside source files.",
    boundary: "C has no standard module privacy for ordinary headers, exposed structure definitions freeze layout, and circular includes signal poorly separated dependencies.",
    scenarioA: "A stack header declares an incomplete struct Stack and public functions while stack.c defines representation and private resize helpers.",
    scenarioB: "Headers include only dependencies needed for their own declarations and use guards so inclusion order does not alter validity.",
    misconception: "Every function and structure definition should be placed in a header so all source files can share it.",
    correction: "Expose only required declarations and contracts in headers; keep ordinary external definitions and private implementation details in source files.",
    checkpoint: "required declarations",
  },
  "c.modular.preprocessor": {
    model: "The preprocessor performs token-based inclusion, conditional compilation, and macro replacement before C translation, without type checking or ordinary function evaluation.",
    boundary: "Macro arguments can be evaluated multiple times, precedence can change without parentheses, names can collide, and conditional paths can rot when rarely built.",
    scenarioA: "A function-like SQUARE macro is rejected for i++ because multiple argument substitution would modify i more than once.",
    scenarioB: "A small constant uses an enum or const object when type and scope matter instead of a global textual macro.",
    misconception: "A function-like macro behaves exactly like an inline function and evaluates each argument once.",
    correction: "Macros are token replacement; parenthesize carefully, avoid side-effecting arguments, and prefer typed functions or constants when possible.",
    checkpoint: "token replacement",
  },
  "c.modular.build": {
    model: "A multi-file C build compiles each translation unit with compatible declarations and then links the selected objects and libraries under reproducible flags.",
    boundary: "Header dependency tracking, ABI flags, library order, duplicate definitions, stale objects, and conditional macros can make incremental builds inconsistent.",
    scenarioA: "Changing a public header recompiles every dependent source file before linking, preventing old object code from using an incompatible declaration.",
    scenarioB: "A clean strict build uses the same language standard and warning flags in local and CI environments.",
    misconception: "Only the .c file directly edited needs recompilation, even when a shared header changed its declarations.",
    correction: "Track header dependencies and rebuild every affected translation unit before linking a coherent program.",
    checkpoint: "header dependencies",
  },
  "c.quality.ub-sanitizers": {
    model: "Undefined behavior has no required result, so prevention uses standard reasoning, strict diagnostics, targeted tests, and sanitizers that detect only the paths and classes they instrument.",
    boundary: "Sanitizers are not the language specification, miss unexecuted paths, can change timing or layout, and different tools cover different undefined or memory behaviors.",
    scenarioA: "AddressSanitizer catches an exercised out-of-bounds write, and the fix is justified by array bounds rather than by merely silencing the tool.",
    scenarioB: "UndefinedBehaviorSanitizer reports signed overflow in a test, prompting a range check or unsigned design before the operation.",
    misconception: "If sanitizer tests pass, the C program contains no undefined behavior on any input.",
    correction: "Sanitizer success is path-limited evidence; combine it with contracts, bounds and lifetime reasoning, diagnostics, and broader tests.",
    checkpoint: "path-limited evidence",
  },

  "cpp.toolchain.program": {
    model: "A hosted C++ program defines a valid global main returning int, initializes static state before main as specified, and maps normal return or fallthrough to a success status.",
    boundary: "Freestanding environments differ, initialization and destruction order across translation units needs care, and exceptions escaping main terminate the program.",
    scenarioA: "A minimal program defines int main(), writes through std::cout, and returns zero after all automatic objects in main are destroyed.",
    scenarioB: "Command-line code checks argc before constructing a string_view from argv[1] and reports invalid usage with a nonzero status.",
    misconception: "C++ permits void main as a portable alternative whenever the operating system ignores exit status.",
    correction: "A portable hosted C++ entry point returns int; use int main() or a supported argument signature and communicate failure with a nonzero status.",
    checkpoint: "returns int",
  },
  "cpp.toolchain.translation": {
    model: "C++ translation preprocesses each translation unit, checks declarations and templates, emits object code, and links definitions under the one-definition rule.",
    boundary: "Templates and inline entities can appear in multiple units under ODR conditions, modules alter delivery, and link-time optimization can blur physical phase boundaries.",
    scenarioA: "A template definition remains visible in a header so a translation unit can instantiate it for int before linking.",
    scenarioB: "Two non-inline definitions of the same external function compile separately but violate the one-definition rule at link or beyond.",
    misconception: "If separate .cpp files compile, declarations and definitions across them cannot violate a C++ program rule.",
    correction: "Translation units compile independently, but linked entities must still satisfy compatible declarations and the one-definition rule across the entire program.",
    checkpoint: "one-definition rule",
  },
  "cpp.toolchain.namespaces": {
    model: "Namespaces organize names and control lookup without creating runtime objects; qualified names make ownership explicit and using declarations import selected names into a scope.",
    boundary: "Argument-dependent lookup, inline and anonymous namespaces, aliases, and broad using directives can change lookup or linkage in non-obvious ways.",
    scenarioA: "A library exposes learn::parse and the caller uses the qualified name, avoiding collision with another parse function.",
    scenarioB: "A header avoids using namespace std because it would inject many names into every including translation unit.",
    misconception: "using namespace creates a copy of that namespace's objects and is harmless in public headers.",
    correction: "A using directive affects name lookup, not object creation; avoid broad directives in headers and prefer qualification or narrow using declarations.",
    checkpoint: "name lookup",
  },
  "cpp.toolchain.diagnostics": {
    model: "C++ diagnostics report syntax, constraint, instantiation, overload, or tool-detected risk; the first relevant cause and template context matter more than message volume.",
    boundary: "Compilers format template traces differently, warnings are configurable, ill-formed no-diagnostic-required cases exist, and successful compilation does not prove defined behavior.",
    scenarioA: "An overload failure is read from the rejected call outward, comparing candidate parameter constraints instead of editing every template frame.",
    scenarioB: "Strict conversion warnings expose an unintended signed-to-unsigned change even though the compiler could emit code.",
    misconception: "The longest template diagnostic line is necessarily the root cause and all later notes describe separate defects.",
    correction: "Locate the primary failed requirement or call, use candidate notes as context, minimize the example, and treat clean diagnostics as bounded evidence.",
    checkpoint: "failed requirement",
  },
  "cpp.fundamentals.types": {
    model: "C++ types determine representation, valid operations, initialization, lifetime, overload selection, and value category behavior, with cv and reference qualifiers refining access.",
    boundary: "Fundamental widths vary, auto follows deduction rules rather than runtime types, references are not reseatable objects, and class invariants add semantic constraints.",
    scenarioA: "auto count = values.size() deduces the container's unsigned size type rather than an assumed int.",
    scenarioB: "const std::string& binds to an existing string for read-only access without copying under its lifetime rules.",
    misconception: "auto makes a variable dynamically typed so its type can change after later assignments.",
    correction: "auto performs compile-time type deduction once; the variable then has that fixed deduced type for its lifetime.",
    checkpoint: "compile-time type deduction",
  },
  "cpp.fundamentals.expressions": {
    model: "C++ expressions combine operators, conversions, value categories, sequencing, overloads, and temporary lifetimes to compute values and effects.",
    boundary: "Operator overloading can change called behavior but not precedence, signed overflow remains undefined, and dangling views or references can outlive temporaries.",
    scenarioA: "Parentheses make arithmetic grouping explicit while a checked conversion prevents silent narrowing into a smaller destination.",
    scenarioB: "ready && evaluate() short-circuits the right operand, but overloaded operators should not be assumed to preserve built-in short-circuit semantics.",
    misconception: "Overloading an operator changes its precedence and evaluation grouping for the class.",
    correction: "Operator precedence and arity remain fixed by C++ grammar; overloading selects function behavior for the already-grouped operands.",
    checkpoint: "precedence",
  },
  "cpp.fundamentals.selection": {
    model: "C++ if, switch, and conditional expressions choose paths from contextually converted conditions, with initialization statements able to scope decision state.",
    boundary: "Switch fallthrough, dangling else, scoped initializers, pattern-like variant handling, and floating comparisons require explicit branch coverage.",
    scenarioA: "An if initializer parses a value and keeps the parse result scoped to the success and failure branches.",
    scenarioB: "A switch uses [[fallthrough]] only where sharing work is intentional and break elsewhere.",
    misconception: "Every switch label ends its branch automatically in C++ unless braces are omitted.",
    correction: "C++ switch execution falls through following labels until a control transfer; use break or explicit [[fallthrough]] to state intent.",
    checkpoint: "[[fallthrough]]",
  },
  "cpp.fundamentals.iteration": {
    model: "C++ loops maintain invariants and progress, while range-for expresses traversal through begin and end and inherits iterator lifetime and invalidation rules.",
    boundary: "Mutating a container can invalidate iterators, references in range-for control copying, unsigned countdown can wrap, and views can dangle.",
    scenarioA: "A const auto& range-for reads each large string without copying and does not mutate the vector during traversal.",
    scenarioB: "An index loop uses i < values.size() and performs zero iterations for an empty vector.",
    misconception: "auto in a range-for always refers to the original element, so edits through it update the container.",
    correction: "auto copies each element, while auto& binds to the element; choose reference and const qualification according to intended mutation and cost.",
    checkpoint: "auto&",
  },
  "cpp.functions.contracts": {
    model: "A C++ function contract states accepted values and ownership, result and error behavior, side effects, complexity where relevant, and exception guarantees.",
    boundary: "A type signature cannot express every semantic precondition, noexcept is a termination promise rather than an error handler, and references do not encode ownership alone.",
    scenarioA: "A find_user function documents that it borrows the repository, returns optional<User>, performs no mutation, and can allocate while searching.",
    scenarioB: "A swap operation states the no-throw guarantee needed by a container and tests that invariant-preserving behavior.",
    misconception: "If parameter and return types compile, all valid domain inputs and failure behavior are already defined by the signature.",
    correction: "Document and test semantic preconditions, ownership, effects, errors, and guarantees in addition to the C++ type signature.",
    checkpoint: "semantic preconditions",
  },
  "cpp.functions.parameters": {
    model: "C++ parameter choice communicates copying, borrowing, mutation, optionality, and ownership through values, references, pointers, forwarding references, and smart pointers.",
    boundary: "Small value types can be cheaper than references, const reference can extend some temporary lifetimes, and forwarding references require constrained perfect-forwarding design.",
    scenarioA: "A setter takes std::string by value and moves it into storage, supporting both lvalues and rvalues with one ownership-taking interface.",
    scenarioB: "A read-only algorithm takes std::span<const int> to borrow a bounded sequence without owning or copying it.",
    misconception: "Passing every object by const reference is always fastest and always communicates the correct ownership contract.",
    correction: "Choose by value for ownership or cheap copies and references or views for borrowing; parameter form should express semantics before assumed micro-optimization.",
    checkpoint: "borrowing",
  },
  "cpp.functions.overload": {
    model: "Overload resolution forms a candidate set, checks viability, ranks conversions and templates, and selects one best function or reports ambiguity.",
    boundary: "Implicit conversions, initializer lists, default arguments, templates, concepts, and hidden base overloads can produce surprising candidate rankings.",
    scenarioA: "Calls with int and double select matching overloads without conversion, while a short argument may promote and create an unexpected choice.",
    scenarioB: "A derived class adds one overload and uses using Base::name to keep intended base overloads visible.",
    misconception: "C++ chooses the overload whose implementation seems most specific to the runtime value.",
    correction: "Overload resolution uses compile-time argument types and ranked conversions, not runtime values or function-body intent.",
    checkpoint: "compile-time argument types",
  },
  "cpp.functions.headers": {
    model: "C++ headers expose declarations and template or inline definitions under ODR-safe rules, while ordinary external definitions normally reside in one source file.",
    boundary: "Templates need visible definitions for instantiation, inline variables have special ODR rules, and macros or using directives in headers leak into includers.",
    scenarioA: "A class declaration and function prototype live in a guarded header while one .cpp file defines non-inline member functions.",
    scenarioB: "A function template definition remains in the header and is identical in every translation unit that instantiates it.",
    misconception: "Moving any function definition into a header is safe because include guards prevent duplicate definitions at link time.",
    correction: "Include guards prevent repeated text in one translation unit; cross-unit definitions must still satisfy inline, template, or one-definition rules.",
    checkpoint: "one-definition rules",
  },
  "cpp.classes.encapsulation": {
    model: "A class protects invariants by exposing operations that keep state valid and hiding representation details that callers should not coordinate directly.",
    boundary: "Access control is compile-time, friends and references can expose state, getters can leak mutable internals, and serialization may couple to representation.",
    scenarioA: "A BankAccount keeps balance private and allows deposit only for positive amounts, preserving its documented invariant.",
    scenarioB: "A collection returns a read-only view instead of a mutable reference that could bypass validation.",
    misconception: "Encapsulation means adding getters and setters for every private field, regardless of invariants.",
    correction: "Expose domain operations, not automatic field access; each public operation should preserve the class invariant and hide replaceable representation.",
    checkpoint: "class invariant",
  },
  "cpp.classes.construction": {
    model: "Construction establishes a class invariant through member initialization in declaration order, and destruction releases owned resources after the object's lifetime ends.",
    boundary: "Member order ignores initializer-list order, virtual dispatch is restricted during construction and destruction, and throwing constructors destroy only fully constructed subobjects.",
    scenarioA: "A Fraction constructor validates a nonzero denominator and initializes normalized members directly in its initializer list.",
    scenarioB: "A member declared before another is initialized first even when the constructor initializer list writes them in the opposite textual order.",
    misconception: "Members initialize in the order written in the constructor's initializer list.",
    correction: "Members initialize in class declaration order; write initializer lists in that same order and establish the invariant before construction completes.",
    checkpoint: "declaration order",
  },
  "cpp.classes.copy": {
    model: "Copy construction and assignment create or replace independent object state according to value semantics, while compiler-generated special members perform memberwise operations.",
    boundary: "Raw ownership, self-assignment, base members, exception safety, and user-declared destructor or move operations affect generated special-member behavior.",
    scenarioA: "A class containing std::vector safely uses generated copy operations because the vector owns and copies its elements.",
    scenarioB: "A raw owning pointer would be copied shallowly by a generated copy operation, risking double deletion, so ownership is redesigned with a value or smart pointer.",
    misconception: "Compiler-generated copying always performs a deep copy of every resource a class can reach.",
    correction: "Generated copying is memberwise; use RAII value members or define deliberate copy semantics when memberwise behavior does not represent an independent value.",
    checkpoint: "memberwise",
  },
  "cpp.classes.operators": {
    model: "An overloaded operator should preserve the operator's conventional meaning, invariants, const correctness, and relationships such as equality consistency.",
    boundary: "Precedence and arity cannot change, some operators must be members, implicit conversions affect symmetry, and surprising side effects make APIs unsafe.",
    scenarioA: "operator== compares all value-significant fields and is const, so equal objects produce equal observable value state.",
    scenarioB: "operator+ returns a new normalized value while operator+= mutates and returns *this by reference for conventional chaining.",
    misconception: "Operator overloading permits inventing new precedence or making + modify its left operand unexpectedly.",
    correction: "Overloading changes implementation, not grammar; preserve conventional operator semantics and keep invariant and equality rules explicit.",
    checkpoint: "not grammar",
  },
  "cpp.resources.raii": {
    model: "RAII binds resource ownership to object lifetime: construction acquires or establishes ownership and deterministic destruction releases it during every normal scope exit and stack unwind.",
    boundary: "RAII does not resolve ownership cycles, process termination can skip normal destruction, and constructors must handle partial acquisition with member RAII.",
    scenarioA: "An ifstream closes automatically when its scope ends, including when a later operation throws an exception.",
    scenarioB: "A lock_guard releases its mutex at block exit rather than relying on every return path to call unlock manually.",
    misconception: "RAII is only about memory allocated with new and does not apply to files, locks, sockets, or transactions.",
    correction: "RAII applies to any resource with scoped ownership and release, including memory, files, locks, handles, and rollback guards.",
    checkpoint: "scoped ownership",
  },
  "cpp.resources.smart-pointers": {
    model: "unique_ptr expresses exclusive ownership, shared_ptr expresses reference-counted shared ownership, and weak_ptr observes a shared object without extending its lifetime.",
    boundary: "shared ownership cycles leak, aliasing constructors and custom deleters complicate behavior, and raw pointers or references can remain valid non-owning observers.",
    scenarioA: "A factory returns unique_ptr<Widget>, transferring exclusive ownership to the caller without an explicit delete.",
    scenarioB: "A parent owns children strongly while each child uses weak_ptr for an optional parent link, avoiding a reference cycle.",
    misconception: "shared_ptr is the safest default for every pointer because more owners always prevent lifetime bugs.",
    correction: "Prefer unique_ptr for exclusive ownership, use shared_ptr only for genuine shared lifetime, and break observer cycles with weak_ptr.",
    checkpoint: "unique_ptr",
  },
  "cpp.resources.exceptions": {
    model: "Exceptions transfer control to a matching handler while stack unwinding destroys completed automatic objects, enabling RAII cleanup and explicit basic, strong, or no-throw guarantees.",
    boundary: "Destructors should not emit exceptions during unwinding, noexcept violations terminate, catch order matters, and exceptions should not replace expected routine branching indiscriminately.",
    scenarioA: "A vector update builds a replacement first and swaps only after success, preserving the original state if allocation throws.",
    scenarioB: "A catch block handles a specific parse_error before a broader std::exception handler and preserves useful context.",
    misconception: "When an exception occurs, automatic objects in exited scopes are abandoned without destructors running.",
    correction: "Stack unwinding destroys fully constructed automatic objects; RAII uses those destructors to release resources on exceptional exits.",
    checkpoint: "Stack unwinding",
  },
  "cpp.resources.move": {
    model: "Move operations transfer or reuse resources from an expiring object, after which the source remains valid but its state is generally unspecified unless the type documents more.",
    boundary: "std::move is a cast and performs no transfer itself, const objects often cannot move resources, and self-move or exception guarantees need type-specific care.",
    scenarioA: "Moving a vector into an owning object allows its buffer to be transferred, while the source vector remains valid for destruction or assignment.",
    scenarioB: "Calling std::move on a const string selects a copy because ordinary move construction requires a non-const rvalue source.",
    misconception: "std::move immediately empties an object and guarantees exactly which value remains in the source.",
    correction: "std::move only enables move overload selection; after an actual move, rely only on the source being valid unless a stronger state is documented.",
    checkpoint: "valid",
  },
  "cpp.polymorphism.composition": {
    model: "Composition builds behavior from owned or referenced components and is preferred when the relationship is has-a or implemented-in-terms-of rather than substitutable is-a.",
    boundary: "Composition still needs ownership and lifetime design, forwarding can enlarge interfaces, and runtime strategy replacement can require indirection.",
    scenarioA: "A Report owns a Formatter component and delegates formatting without claiming that a Report is a kind of Formatter.",
    scenarioB: "A service receives a Clock interface component for testing rather than inheriting unrelated clock state.",
    misconception: "Inheritance is always the best reuse mechanism because composition requires writing forwarding methods.",
    correction: "Choose composition for has-a collaboration and inheritance only for a sound substitutable abstraction with an intentionally virtual interface.",
    checkpoint: "has-a",
  },
  "cpp.polymorphism.inheritance": {
    model: "Public inheritance models substitutability: derived objects must satisfy the base contract, preserve invariants, and respect access and construction rules.",
    boundary: "Private inheritance is implementation reuse, multiple inheritance adds ambiguity, base constructors run first, and nonvirtual operations do not provide runtime replacement.",
    scenarioA: "A Circle publicly implements a Shape drawing and area contract so code using Shape references can accept it without special cases.",
    scenarioB: "A Stack does not inherit publicly from vector because exposing arbitrary vector insertion would violate the stack interface.",
    misconception: "Any class that reuses another class's code should publicly inherit from it.",
    correction: "Public inheritance requires is-a substitutability, not mere code reuse; otherwise prefer composition or a private implementation technique.",
    checkpoint: "is-a substitutability",
  },
  "cpp.polymorphism.virtual": {
    model: "Virtual dispatch selects the final overrider through a base reference or pointer, and a polymorphic base intended for deletion needs a virtual destructor.",
    boundary: "Calls during construction and destruction dispatch only within the active construction level, default arguments are statically selected, and object slicing removes derived state.",
    scenarioA: "A vector of unique_ptr<Shape> calls virtual draw on each dynamic object and deletes safely through Shape because its destructor is virtual.",
    scenarioB: "A virtual call from the base constructor does not reach a derived override whose subobject is not yet constructed.",
    misconception: "Any same-named derived function is dynamically selected even when the base function is not virtual or the object was copied by value.",
    correction: "Runtime dispatch requires a virtual base function and access through a base reference or pointer to an unsliced object.",
    checkpoint: "virtual base function",
  },
  "cpp.polymorphism.slicing-casts": {
    model: "Copying a derived object into a base value slices derived state, while safe downcasts require a polymorphic hierarchy and a checked dynamic_cast when the dynamic type is uncertain.",
    boundary: "static_cast downcasts trust an external proof, dynamic_cast needs runtime type information and a polymorphic base, and reference failure throws rather than returns null.",
    scenarioA: "Passing Derived by Base value loses its added fields and override behavior, so the interface instead accepts const Base&.",
    scenarioB: "A pointer dynamic_cast is checked for null before derived-only operations are used.",
    misconception: "static_cast from Base* to Derived* checks the runtime object and returns null if the object is not Derived.",
    correction: "Use dynamic_cast for a checked polymorphic downcast; static_cast performs no runtime type check and is valid only when the programmer already proves the dynamic type.",
    checkpoint: "dynamic_cast",
  },
  "cpp.containers.sequence": {
    model: "Sequence containers preserve element order but offer different insertion, erasure, random-access, contiguity, and iterator-invalidation guarantees.",
    boundary: "Vector reallocation invalidates references, deque layout is not one contiguous array, list sacrifices locality, and complexity guarantees do not include every constant cost.",
    scenarioA: "A vector stores scores for fast indexed traversal and reserves known capacity before retaining references during append operations.",
    scenarioB: "A list is rejected for small numeric iteration because pointer overhead and poor locality outweigh cheap middle insertion not actually needed.",
    misconception: "All standard sequence containers support the same iterator stability and random-access operations.",
    correction: "Choose from required operations and verify that container's invalidation and complexity guarantees before retaining iterators or references.",
    checkpoint: "invalidation",
  },
  "cpp.containers.associative": {
    model: "Ordered associative containers use key ordering, while unordered containers use hash and equality; sets store keys and maps associate unique keys with mapped values.",
    boundary: "Custom comparison must be strict weak ordering, hash must agree with equality, insertion can invalidate unordered iterators during rehash, and operator[] can insert.",
    scenarioA: "A map counts words but uses find when a lookup must not create a missing entry, reserving operator[] for intentional insertion or update.",
    scenarioB: "An unordered_set custom key supplies equality and a consistent hash so equal keys always hash equally.",
    misconception: "map operator[] is a read-only lookup that leaves the container unchanged when a key is absent.",
    correction: "map operator[] inserts a value-initialized mapped value for a missing key; use find, contains, or at when insertion is not intended.",
    checkpoint: "inserts",
  },
  "cpp.containers.adaptors": {
    model: "Container adaptors expose a restricted stack, queue, or priority-queue interface over an underlying container to enforce access discipline.",
    boundary: "Adaptors do not expose ordinary iteration, priority_queue order depends on its comparator, and front, top, or pop require nonempty preconditions.",
    scenarioA: "A bracket checker uses stack top and pop only after verifying the stack is nonempty.",
    scenarioB: "A task scheduler defines a comparator so priority_queue top returns the intended highest-priority task rather than assuming pair ordering.",
    misconception: "Calling pop on a standard stack returns the removed value like some other languages' stack APIs.",
    correction: "Standard container-adaptor pop removes without returning; read top or front first after checking nonempty, then call pop.",
    checkpoint: "removes without returning",
  },
  "cpp.containers.iterators": {
    model: "Iterators identify positions in ranges, commonly represented as half-open [first,last), and their valid operations depend on iterator category and container state.",
    boundary: "End iterators cannot be dereferenced, mutation can invalidate iterators, input iterators can be single-pass, and iterators from unrelated ranges cannot be compared freely.",
    scenarioA: "An algorithm processes every vector element from begin up to but not including end and performs zero steps when begin equals end.",
    scenarioB: "After vector insertion triggers reallocation, previously saved iterators are discarded and reacquired.",
    misconception: "The end iterator refers to the last element and can be dereferenced before a loop stops.",
    correction: "Standard ranges are half-open: end is one past the final element and must never be dereferenced.",
    checkpoint: "half-open",
  },
  "cpp.algorithms.standard": {
    model: "Standard algorithms express operations over iterator or range inputs with documented preconditions, complexity, mutation, and result semantics independent of one container type.",
    boundary: "Algorithms may require iterator categories, sorted input, valid output capacity, or nonoverlapping ranges, and remove-like algorithms do not erase container elements themselves.",
    scenarioA: "sort orders a vector under a valid comparator, then lower_bound is used only while that sorted precondition remains true.",
    scenarioB: "remove_if compacts retained elements and returns a new logical end, after which vector erase removes the trailing elements.",
    misconception: "std::remove_if directly changes a vector's size and destroys every removed element.",
    correction: "remove_if rearranges and returns a new logical end; use the container's erase operation to reduce its size.",
    checkpoint: "logical end",
  },
  "cpp.algorithms.lambdas": {
    model: "A lambda creates a closure object whose capture list determines copied or referenced state, parameter list defines calls, and mutable affects copied capture modification.",
    boundary: "Reference captures can dangle, [=] can copy more context than intended, this capture rules evolve, and closure types are unique unnamed types.",
    scenarioA: "A count_if lambda captures threshold by value so later changes to the outer variable do not alter the predicate.",
    scenarioB: "A callback that outlives its creating scope avoids reference capture of a local variable that would dangle.",
    misconception: "A lambda using [&] safely keeps every referenced local alive for as long as the lambda object exists.",
    correction: "Reference capture does not extend local lifetime; ensure every referenced object outlives all closure calls or capture an owned value.",
    checkpoint: "does not extend local lifetime",
  },
  "cpp.algorithms.comparators": {
    model: "Ordering algorithms and containers require a comparator that behaves as a strict weak ordering, including irreflexivity and transitive equivalence classes.",
    boundary: "Using <=, mutable external state, NaN-sensitive relations, or inconsistent tie handling can violate requirements and make behavior undefined or incorrect.",
    scenarioA: "A Person comparator orders by score, then id as a deterministic tie-breaker, and returns false when comparing an object with itself.",
    scenarioB: "A sort comparator using a <= b is rejected because equal values make comp(a,a) true.",
    misconception: "A sorting comparator should return true for equal elements so either order is accepted.",
    correction: "A strict comparator must return false for equivalent values in both directions; use < semantics and consistent tie-breakers.",
    checkpoint: "false for equivalent values",
  },
  "cpp.algorithms.ranges": {
    model: "C++ ranges combine range-aware algorithms and composable lazy views, with concepts checking operations and borrowed or owning relationships determining lifetime safety.",
    boundary: "Views often do not own elements, temporary or mutated sources can dangle or invalidate, lazy evaluation defers work, and not every range is common or sized.",
    scenarioA: "A filter view over a live vector is iterated while the vector remains alive and structurally unchanged.",
    scenarioB: "A view pipeline is not returned when it would refer to a local source destroyed at function exit.",
    misconception: "Every range view owns a copied collection, so it remains valid after the original container is destroyed.",
    correction: "Views commonly borrow and evaluate lazily; prove the source and captured state outlive iteration or return an owning result.",
    checkpoint: "borrow",
  },
  "cpp.generics.function-template": {
    model: "A function template defines a family of functions instantiated for argument types that satisfy all used operations and explicit constraints.",
    boundary: "Deduction does not use every conversion, definitions usually must be visible, overload resolution includes templates and non-templates, and errors can surface at instantiation.",
    scenarioA: "A constrained maximum template accepts two values with a valid ordering and common return behavior rather than assuming every type supports operator<.",
    scenarioB: "Calling a template with mixed types fails deduction until the interface explicitly supports or names a common type.",
    misconception: "A function template is one runtime function that inspects an argument's dynamic type.",
    correction: "A function template is instantiated at compile time into type-specific functions after deduction and constraint checking.",
    checkpoint: "compile time",
  },
  "cpp.generics.class-template": {
    model: "A class template defines a family of class types whose members and invariants depend on template arguments, with each specialization being a distinct type.",
    boundary: "Member definitions need appropriate template syntax, incomplete instantiation can defer errors, deduction guides affect construction, and static members are per specialization.",
    scenarioA: "Box<int> and Box<std::string> share a template pattern but are distinct types with independently instantiated operations.",
    scenarioB: "A member requiring ordering is constrained or instantiated only when the element type supports the required comparison.",
    misconception: "All specializations of a class template are implicitly convertible because they come from the same template.",
    correction: "Each class-template specialization is a distinct type; conversions exist only when explicitly declared or otherwise provided.",
    checkpoint: "distinct type",
  },
  "cpp.generics.requirements": {
    model: "Concepts and requires expressions state compile-time semantic and syntactic requirements, improving overload participation and diagnostics without testing runtime values.",
    boundary: "A syntactically valid expression does not prove every semantic law, overly broad concepts accept broken behavior, and constraints do not replace runtime preconditions.",
    scenarioA: "A sorting helper requires random-access iteration and sortable values, rejecting a list iterator at the call boundary.",
    scenarioB: "A numeric concept checks available operations but documentation still states nonzero divisor as a runtime precondition.",
    misconception: "A requires expression executes sample operations at runtime and proves the algorithm will succeed for every value.",
    correction: "Constraints are compile-time requirements on types and expressions; document semantic laws and validate runtime value preconditions separately.",
    checkpoint: "compile-time requirements",
  },
  "cpp.generics.variants": {
    model: "optional represents presence or absence, variant represents one active alternative from a closed set, and visitation handles alternatives without unchecked type guessing.",
    boundary: "optional does not explain failure, variant can become valueless by exception in limited cases, get can throw, and adding an alternative requires visitor coverage.",
    scenarioA: "A lookup returns optional<User> and the caller checks engagement before dereference rather than using a sentinel User.",
    scenarioB: "A parsed token is variant<Number,Name> and std::visit invokes exhaustive behavior for each alternative.",
    misconception: "std::get automatically converts whichever variant alternative is active into the requested type.",
    correction: "A variant has one active declared alternative; check or visit it, because std::get for the wrong alternative throws bad_variant_access.",
    checkpoint: "active declared alternative",
  },
  "cpp.quality.io": {
    model: "C++ streams carry formatting and error state; extraction must be checked before values are used, and line-oriented input must account for delimiters left by formatted extraction.",
    boundary: "Locale, buffering, synchronization, fail/eof distinctions, exceptions masks, and mixing formatted with line input affect behavior.",
    scenarioA: "An integer extraction appears directly in an if condition, and invalid input clears or terminates processing before the destination is trusted.",
    scenarioB: "After reading a number, the program consumes the pending newline before getline reads a full name.",
    misconception: "istream extraction always assigns a usable default value and eof alone identifies every input failure.",
    correction: "Check stream state after each required extraction and distinguish parse failure, EOF, and I/O error before using destination values.",
    checkpoint: "stream state",
  },
  "cpp.quality.tests": {
    model: "C++ tests assert observable contracts across normal, boundary, failure, lifetime, and exception cases without coupling unnecessarily to private representation.",
    boundary: "Undefined behavior can invalidate a test, nondeterminism needs control, death and exception tests are tool-specific, and one implementation-shaped oracle can reject valid alternatives.",
    scenarioA: "A parser test covers empty, valid, boundary, and malformed input and checks returned value or error rather than private helper call order.",
    scenarioB: "A move-only resource test verifies ownership and cleanup behavior without assuming a moved-from container is empty unless documented.",
    misconception: "High line coverage proves the class contract and every edge case are correct.",
    correction: "Coverage measures execution, not correctness; derive assertions from contracts, equivalence classes, boundaries, failures, and invariants.",
    checkpoint: "contracts",
  },
  "cpp.quality.build": {
    model: "A reliable C++ build pins language mode and toolchain, tracks header and generated dependencies, applies consistent ABI flags, and links one ODR-coherent program.",
    boundary: "Compiler and standard-library ABI, modules, precompiled headers, build caches, conditional macros, and platform libraries can invalidate otherwise successful incremental output.",
    scenarioA: "A changed class header recompiles every dependent translation unit before tests link against one consistent layout.",
    scenarioB: "CI performs a clean C++20 build with the same warning and sanitizer configuration documented for local development.",
    misconception: "Object files built with any compiler flags can be mixed safely as long as the linker accepts their names.",
    correction: "Keep ABI-affecting compiler, library, macro, and language settings consistent across every linked translation unit and dependency.",
    checkpoint: "ABI-affecting",
  },
  "cpp.quality.sanitizers": {
    model: "C++ sanitizers instrument selected undefined, address, or memory behaviors on executed paths and complement type, ownership, lifetime, and contract reasoning.",
    boundary: "They do not cover all defects, different sanitizers conflict or change timing, optimized and unexecuted paths differ, and clean runs are not proof.",
    scenarioA: "AddressSanitizer reports a use-after-free reached by a test, and ownership is redesigned with RAII rather than suppressing the report.",
    scenarioB: "UndefinedBehaviorSanitizer exposes signed overflow at a boundary input and the operation gains a precondition or checked arithmetic.",
    misconception: "Passing all sanitizer tests certifies that a C++ program has no lifetime or undefined-behavior defects.",
    correction: "Sanitizer results are path-limited evidence; combine multiple appropriate tools with static diagnostics, ownership design, invariants, and boundary tests.",
    checkpoint: "path-limited evidence",
  }
} as const satisfies Readonly<Record<string, LanguageTeachingSeed>>;
