export type CCppLanguage = "c" | "cpp";

export interface CCppExecutableCase {
  readonly id: string;
  readonly visibility: "visible" | "hidden";
  readonly category: "normal" | "boundary" | "invalid";
  readonly stdin: string;
  readonly expectedStdout: string;
}

export interface CCppExecutableSpec {
  readonly facet: string;
  readonly prompt: string;
  readonly starterCode: string;
  readonly referenceSolution: string;
  readonly tests: readonly CCppExecutableCase[];
}

type CaseSeed = readonly [stdin: string, expectedStdout: string, category: CCppExecutableCase["category"]];

function define(
  skillId: string,
  facet: string,
  prompt: string,
  starterCode: string,
  referenceSolution: string,
  cases: readonly [CaseSeed, CaseSeed, ...CaseSeed[]],
): CCppExecutableSpec {
  const prefix = skillId.replaceAll(".", "-");
  return {
    facet,
    prompt,
    starterCode,
    referenceSolution,
    tests: cases.map(([stdin, expectedStdout, category], index) => ({
      id: prefix + "-case-" + (index + 1),
      visibility: index === 0 ? "visible" : "hidden",
      category,
      stdin,
      expectedStdout,
    })),
  };
}

export const C_CPP_NON_CODE_FACETS: Readonly<Record<string, string>> = {
  "c.toolchain.phases": "The current runner compiles and runs one submitted source set but does not expose separate preprocess, compile, assemble, and link artifacts, so an stdout task would not honestly prove phase diagnosis.",
  "c.toolchain.diagnostics": "A passing reference program cannot prove that a learner can interpret and repair compiler diagnostics; this facet needs captured failing compilations and diagnostic-aware grading.",
  "c.modular.headers": "This outcome requires review of a public header, matching implementation, self-containment, and include guards; the current single-entry assessment model cannot grade the complete artifact honestly.",
  "c.modular.build": "A repeatable multi-file build description and dependency graph are build artifacts outside the current source-plus-stdin/stdout contract.",
  "c.quality.ub-sanitizers": "The pinned runtime compiles ordinary C23 without sanitizer instrumentation, so it cannot honestly claim AddressSanitizer or UndefinedBehaviorSanitizer evidence.",
  "cpp.toolchain.translation": "The current runner does not expose preprocessing, translation-unit, object, or link-stage artifacts, so successful stdout is not evidence of translation-stage diagnosis.",
  "cpp.toolchain.diagnostics": "A correct reference executable cannot assess reading and repairing compiler diagnostics; this requires a diagnostic-capture assessment mode.",
  "cpp.functions.headers": "The skill requires a self-contained declaration header and matching definition artifact, which the current one-item source contract cannot review completely.",
  "cpp.quality.build": "Build-system targets, dependencies, warning profiles, and repeatability are external artifacts not represented by deterministic stdin/stdout cases.",
  "cpp.quality.sanitizers": "The pinned G++ runner is not compiled with sanitizer instrumentation, so passing output cannot serve as sanitizer or undefined-behavior evidence.",
};

export const C_CPP_NEW_EXECUTABLE_SPECS: Readonly<Record<string, CCppExecutableSpec>> = {
  "c.toolchain.program": define(
    "c.toolchain.program",
    "hosted entry point, checked input, and termination status",
    "Read one integer in a conforming hosted C program, print the integer plus one followed by a newline, and return a successful integer status.",
    `#include <stdio.h>\n\nint main(void) {\n    int value;\n    /* read, print value + 1, and return a status */\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    int value;\n    if (scanf(\"%d\", &value) != 1) return 1;\n    printf(\"%d\\n\", value + 1);\n    return 0;\n}\n`,
    [["4\n", "5\n", "normal"], ["-1\n", "0\n", "boundary"], ["0\n", "1\n", "boundary"]],
  ),
  "c.toolchain.headers": define(
    "c.toolchain.headers",
    "standard header declaration and unsigned-char ctype contract",
    "Read one ASCII character and use the correctly declared standard character-classification facility to print digit, alpha, or other.",
    `#include <ctype.h>\n#include <stdio.h>\n\nint main(void) {\n    int ch = getchar();\n    /* classify ch without violating the ctype contract */\n    return 0;\n}\n`,
    `#include <ctype.h>\n#include <stdio.h>\n\nint main(void) {\n    int ch = getchar();\n    if (ch == EOF) return 1;\n    unsigned char value = (unsigned char)ch;\n    if (isdigit(value)) puts(\"digit\");\n    else if (isalpha(value)) puts(\"alpha\");\n    else puts(\"other\");\n    return 0;\n}\n`,
    [["7\n", "digit\n", "normal"], ["A\n", "alpha\n", "boundary"], ["?\n", "other\n", "boundary"]],
  ),
  "c.types.scalar": define(
    "c.types.scalar",
    "deliberate integer, floating, and Boolean scalar declarations",
    "Read an integer quantity and a decimal unit price, store the nonzero state in a Boolean object, and print active plus the product rounded to two decimals.",
    `#include <stdbool.h>\n#include <stdio.h>\n\nint main(void) {\n    int quantity;\n    double price;\n    /* declare the Boolean state and print the result */\n    return 0;\n}\n`,
    `#include <stdbool.h>\n#include <stdio.h>\n\nint main(void) {\n    int quantity;\n    double price;\n    if (scanf(\"%d %lf\", &quantity, &price) != 2) return 1;\n    bool active = quantity != 0;\n    printf(\"%s %.2f\\n\", active ? \"active\" : \"inactive\", quantity * price);\n    return 0;\n}\n`,
    [["3 2.50\n", "active 7.50\n", "normal"], ["0 9.99\n", "inactive 0.00\n", "boundary"], ["-2 1.25\n", "active -2.50\n", "boundary"]],
  ),
  "c.types.literals-format": define(
    "c.types.literals-format",
    "matched fixed-width input and output conversion macros",
    "Read one signed 64-bit integer with the portable inttypes conversion macro and print its absolute magnitude as an unsigned 64-bit value.",
    `#include <inttypes.h>\n#include <stdint.h>\n#include <stdio.h>\n\nint main(void) {\n    int64_t value;\n    /* use SCNd64 and PRIu64 with matching argument types */\n    return 0;\n}\n`,
    `#include <inttypes.h>\n#include <stdint.h>\n#include <stdio.h>\n\nint main(void) {\n    int64_t value;\n    if (scanf(\"%\" SCNd64, &value) != 1) return 1;\n    uint64_t magnitude = value < 0 ? (uint64_t)(-(value + 1)) + 1u : (uint64_t)value;\n    printf(\"%\" PRIu64 \"\\n\", magnitude);\n    return 0;\n}\n`,
    [["-42\n", "42\n", "normal"], ["0\n", "0\n", "boundary"], ["-9223372036854775808\n", "9223372036854775808\n", "boundary"]],
  ),
  "c.types.conversions": define(
    "c.types.conversions",
    "range-checked narrowing before conversion",
    "Read a long long value and print its signed-byte value only when it is representable from -128 through 127; otherwise print out-of-range.",
    `#include <stdio.h>\n\nint main(void) {\n    long long value;\n    /* validate before narrowing to signed char */\n    return 0;\n}\n`,
    `#include <limits.h>\n#include <stdio.h>\n\nint main(void) {\n    long long value;\n    if (scanf(\"%lld\", &value) != 1) return 1;\n    if (value < SCHAR_MIN || value > SCHAR_MAX) puts(\"out-of-range\");\n    else printf(\"%d\\n\", (int)(signed char)value);\n    return 0;\n}\n`,
    [["42\n", "42\n", "normal"], ["127\n", "127\n", "boundary"], ["128\n", "out-of-range\n", "boundary"]],
  ),
  "c.control.jump": define(
    "c.control.jump",
    "structured continue, break, and return behavior",
    "Read a count and integers, skip zeros with continue, stop at the first negative with break, and print the sum of preceding positive values.",
    `#include <stdio.h>\n\nint main(void) {\n    int count;\n    /* read values and use structured jump statements */\n    return 0;\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    int count;\n    if (scanf(\"%d\", &count) != 1 || count < 0 || count > 100) return 1;\n    long long sum = 0;\n    for (int i = 0; i < count; ++i) {\n        int value;\n        if (scanf(\"%d\", &value) != 1) return 1;\n        if (value == 0) continue;\n        if (value < 0) break;\n        sum += value;\n    }\n    printf(\"%lld\\n\", sum);\n    return 0;\n}\n`,
    [["6\n2 0 3 -1 9 9\n", "5\n", "normal"], ["0\n", "0\n", "boundary"], ["3\n-1 5 6\n", "0\n", "boundary"]],
  ),
  "c.control.input": define(
    "c.control.input",
    "bounded line input and complete strtol validation",
    "Read one bounded text line, parse exactly one base-10 integer from 0 through 100, and print the value or invalid without using scanf for the conversion.",
    `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    char line[64];\n    /* use fgets and strtol; reject trailing non-space input */\n    return 0;\n}\n`,
    `#include <ctype.h>\n#include <errno.h>\n#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    char line[64];\n    if (fgets(line, sizeof line, stdin) == NULL) return 1;\n    errno = 0;\n    char *end;\n    long value = strtol(line, &end, 10);\n    while (isspace((unsigned char)*end)) ++end;\n    if (errno != 0 || end == line || *end != '\\0' || value < 0 || value > 100) puts(\"invalid\");\n    else printf(\"%ld\\n\", value);\n    return 0;\n}\n`,
    [["42\n", "42\n", "normal"], ["0\n", "0\n", "boundary"], ["12x\n", "invalid\n", "invalid"]],
  ),
  "c.functions.prototype": define(
    "c.functions.prototype",
    "compatible declaration, definition, and typed call",
    "Declare a long long cube function before main, call it for one input, and provide a compatible definition after main.",
    `#include <stdio.h>\n\n/* declare cube */\n\nint main(void) {\n    long long value;\n    /* read, call, print */\n}\n\n/* define cube */\n`,
    `#include <stdio.h>\n\nstatic long long cube(long long value);\n\nint main(void) {\n    long long value;\n    if (scanf(\"%lld\", &value) != 1) return 1;\n    printf(\"%lld\\n\", cube(value));\n    return 0;\n}\n\nstatic long long cube(long long value) { return value * value * value; }\n`,
    [["3\n", "27\n", "normal"], ["0\n", "0\n", "boundary"], ["-2\n", "-8\n", "boundary"]],
  ),
  "c.functions.parameters": define(
    "c.functions.parameters",
    "value parameters versus explicit pointer output parameters",
    "Call a function that receives two integers by value and writes their ordered minimum and maximum through non-null output pointers, then print both.",
    `#include <stdio.h>\n\nstatic void order_pair(int a, int b, int *minimum, int *maximum) {\n    /* assign caller-visible outputs */\n}\n\nint main(void) {\n    /* read, call, print */\n}\n`,
    `#include <stdio.h>\n\nstatic void order_pair(int a, int b, int *minimum, int *maximum) {\n    if (a <= b) { *minimum = a; *maximum = b; }\n    else { *minimum = b; *maximum = a; }\n}\n\nint main(void) {\n    int a, b, minimum, maximum;\n    if (scanf(\"%d %d\", &a, &b) != 2) return 1;\n    order_pair(a, b, &minimum, &maximum);\n    printf(\"%d %d\\n\", minimum, maximum);\n    return 0;\n}\n`,
    [["9 2\n", "2 9\n", "normal"], ["4 4\n", "4 4\n", "boundary"], ["-1 -8\n", "-8 -1\n", "boundary"]],
  ),
  "c.functions.scope-storage": define(
    "c.functions.scope-storage",
    "block scope and persistent static storage duration",
    "Implement a function-local static counter that increments on each call, call it n times, and print the final persistent value; print zero when n is zero.",
    `#include <stdio.h>\n\nstatic unsigned next_count(void) {\n    /* function-local static object */\n}\n\nint main(void) {\n    /* call n times and print */\n}\n`,
    `#include <stdio.h>\n\nstatic unsigned next_count(void) {\n    static unsigned count = 0;\n    return ++count;\n}\n\nint main(void) {\n    unsigned n;\n    if (scanf(\"%u\", &n) != 1 || n > 1000u) return 1;\n    unsigned result = 0;\n    for (unsigned i = 0; i < n; ++i) result = next_count();\n    printf(\"%u\\n\", result);\n    return 0;\n}\n`,
    [["5\n", "5\n", "normal"], ["0\n", "0\n", "boundary"], ["1\n", "1\n", "boundary"]],
  ),
  "c.functions.recursion": define(
    "c.functions.recursion",
    "explicit recursive base case and decreasing progress",
    "Read n from 0 through 20 and compute n factorial with a recursive unsigned long long function that has an explicit base case.",
    `#include <stdio.h>\n\nstatic unsigned long long factorial(unsigned n) {\n    /* base case and recursive progress */\n}\n\nint main(void) {\n    /* read and print */\n}\n`,
    `#include <stdio.h>\n\nstatic unsigned long long factorial(unsigned n) {\n    return n < 2u ? 1u : n * factorial(n - 1u);\n}\n\nint main(void) {\n    unsigned n;\n    if (scanf(\"%u\", &n) != 1 || n > 20u) return 1;\n    printf(\"%llu\\n\", factorial(n));\n    return 0;\n}\n`,
    [["5\n", "120\n", "normal"], ["0\n", "1\n", "boundary"], ["1\n", "1\n", "boundary"]],
  ),
  "c.arrays.multidimensional": define(
    "c.arrays.multidimensional",
    "row-major bounded two-dimensional traversal",
    "Read row and column counts up to 10 and a rectangular integer grid, traverse it with nested bounds, and print each row sum on one line separated by spaces.",
    `#include <stdio.h>\n\nint main(void) {\n    int grid[10][10];\n    size_t rows, columns;\n    /* read and traverse the used rectangle */\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    int grid[10][10];\n    size_t rows, columns;\n    if (scanf(\"%zu %zu\", &rows, &columns) != 2 || rows == 0 || columns == 0 || rows > 10 || columns > 10) return 1;\n    for (size_t r = 0; r < rows; ++r) for (size_t c = 0; c < columns; ++c) if (scanf(\"%d\", &grid[r][c]) != 1) return 1;\n    for (size_t r = 0; r < rows; ++r) {\n        long long sum = 0;\n        for (size_t c = 0; c < columns; ++c) sum += grid[r][c];\n        if (r) putchar(' ');\n        printf(\"%lld\", sum);\n    }\n    putchar('\\n');\n    return 0;\n}\n`,
    [["2 3\n1 2 3 4 5 6\n", "6 15\n", "normal"], ["1 1\n-7\n", "-7\n", "boundary"], ["2 1\n0 9\n", "0 9\n", "boundary"]],
  ),
  "c.strings.representation": define(
    "c.strings.representation",
    "bounded character array and terminating null character",
    "Read at most 40 non-newline characters with fgets, remove only the trailing newline when present, and compute the string length by scanning to the null terminator.",
    `#include <stdio.h>\n\nint main(void) {\n    char text[42];\n    /* bounded read, newline removal, manual length */\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    char text[42];\n    if (fgets(text, sizeof text, stdin) == NULL) return 1;\n    size_t length = 0;\n    while (text[length] != '\\0' && text[length] != '\\n') ++length;\n    if (text[length] == '\\n') text[length] = '\\0';\n    printf(\"%zu\\n\", length);\n    return 0;\n}\n`,
    [["hello\n", "5\n", "normal"], ["\n", "0\n", "boundary"], ["a\n", "1\n", "boundary"]],
  ),
  "c.strings.operations": define(
    "c.strings.operations",
    "capacity-aware bounded string transformation",
    "Read at most 40 lowercase ASCII letters, reject other characters with invalid, and print the string reversed without writing outside the array.",
    `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char text[42];\n    /* validate, remove newline, and reverse within bounds */\n}\n`,
    `#include <stdio.h>\n#include <string.h>\n\nint main(void) {\n    char text[42];\n    if (fgets(text, sizeof text, stdin) == NULL) return 1;\n    size_t length = strcspn(text, \"\\n\");\n    if (text[length] == '\\n') text[length] = '\\0';\n    for (size_t i = 0; i < length; ++i) if (text[i] < 'a' || text[i] > 'z') { puts(\"invalid\"); return 0; }\n    for (size_t i = length; i > 0; --i) putchar(text[i - 1]);\n    putchar('\\n');\n    return 0;\n}\n`,
    [["buddy\n", "yddub\n", "normal"], ["\n", "\n", "boundary"], ["a1\n", "invalid\n", "invalid"]],
  ),
  "c.pointers.arrays": define(
    "c.pointers.arrays",
    "pointer traversal confined to one array object",
    "Read up to 100 integers and sum them by advancing a pointer from the first element to the one-past endpoint without dereferencing the endpoint.",
    `#include <stdio.h>\n\nint main(void) {\n    int values[100];\n    size_t count;\n    /* read and traverse with pointers */\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    int values[100];\n    size_t count;\n    if (scanf(\"%zu\", &count) != 1 || count > 100) return 1;\n    for (size_t i = 0; i < count; ++i) if (scanf(\"%d\", &values[i]) != 1) return 1;\n    long long sum = 0;\n    for (const int *cursor = values; cursor != values + count; ++cursor) sum += *cursor;\n    printf(\"%lld\\n\", sum);\n    return 0;\n}\n`,
    [["4\n1 2 3 4\n", "10\n", "normal"], ["0\n", "0\n", "boundary"], ["1\n-5\n", "-5\n", "boundary"]],
  ),
  "c.pointers.const": define(
    "c.pointers.const",
    "read-only pointee contract with const pointer input",
    "Implement a sum function whose array parameter does not permit element mutation, then read up to 100 integers and print the sum.",
    `#include <stdio.h>\n\nstatic long long sum_values(const int *values, size_t count) {\n    /* read only through values */\n}\n\nint main(void) {\n    /* read, call, print */\n}\n`,
    `#include <stdio.h>\n\nstatic long long sum_values(const int *values, size_t count) {\n    long long sum = 0;\n    for (size_t i = 0; i < count; ++i) sum += values[i];\n    return sum;\n}\n\nint main(void) {\n    size_t count;\n    int values[100];\n    if (scanf(\"%zu\", &count) != 1 || count > 100) return 1;\n    for (size_t i = 0; i < count; ++i) if (scanf(\"%d\", &values[i]) != 1) return 1;\n    printf(\"%lld\\n\", sum_values(values, count));\n    return 0;\n}\n`,
    [["3\n2 4 6\n", "12\n", "normal"], ["0\n", "0\n", "boundary"], ["2\n-3 3\n", "0\n", "boundary"]],
  ),
  "c.pointers.functions": define(
    "c.pointers.functions",
    "compatible function pointer and callback invocation",
    "Read an operation character plus two integers, select a compatible add or multiply callback, invoke it through a typed function pointer, and print the result.",
    `#include <stdio.h>\n\ntypedef long long (*operation_fn)(long long, long long);\n/* define callbacks and selection */\n\nint main(void) {\n    /* read, select, invoke */\n}\n`,
    `#include <stdio.h>\n\ntypedef long long (*operation_fn)(long long, long long);\nstatic long long add(long long a, long long b) { return a + b; }\nstatic long long multiply(long long a, long long b) { return a * b; }\n\nint main(void) {\n    char operation;\n    long long a, b;\n    if (scanf(\" %c %lld %lld\", &operation, &a, &b) != 3) return 1;\n    operation_fn function = operation == '+' ? add : operation == '*' ? multiply : NULL;\n    if (function == NULL) { puts(\"invalid\"); return 0; }\n    printf(\"%lld\\n\", function(a, b));\n    return 0;\n}\n`,
    [["+ 4 7\n", "11\n", "normal"], ["* 0 9\n", "0\n", "boundary"], ["? 1 2\n", "invalid\n", "invalid"]],
  ),
  "c.aggregates.struct": define(
    "c.aggregates.struct",
    "named fields, initialization, and structure processing",
    "Read a product id, quantity, and integer unit price into a structure and print the id and total value using a function that accepts a const structure pointer.",
    `#include <stdio.h>\n\ntypedef struct { int id; int quantity; long long unit_price; } Product;\n/* define total */\n\nint main(void) {\n    /* initialize and process Product */\n}\n`,
    `#include <stdio.h>\n\ntypedef struct { int id; int quantity; long long unit_price; } Product;\nstatic long long total(const Product *product) { return (long long)product->quantity * product->unit_price; }\n\nint main(void) {\n    Product product;\n    if (scanf(\"%d %d %lld\", &product.id, &product.quantity, &product.unit_price) != 3) return 1;\n    printf(\"%d %lld\\n\", product.id, total(&product));\n    return 0;\n}\n`,
    [["7 3 25\n", "7 75\n", "normal"], ["1 0 99\n", "1 0\n", "boundary"], ["9 2 -5\n", "9 -10\n", "boundary"]],
  ),
  "c.aggregates.enum": define(
    "c.aggregates.enum",
    "closed named states with explicit external-value validation",
    "Read an external integer state, convert only values 0 through 2 to a named enum, and print idle, running, stopped, or invalid with exhaustive control flow.",
    `#include <stdio.h>\n\ntypedef enum { IDLE, RUNNING, STOPPED } State;\n\nint main(void) {\n    /* validate before enum conversion and switch */\n}\n`,
    `#include <stdio.h>\n\ntypedef enum { IDLE, RUNNING, STOPPED } State;\n\nint main(void) {\n    int raw;\n    if (scanf(\"%d\", &raw) != 1) return 1;\n    if (raw < IDLE || raw > STOPPED) { puts(\"invalid\"); return 0; }\n    State state = (State)raw;\n    switch (state) {\n        case IDLE: puts(\"idle\"); break;\n        case RUNNING: puts(\"running\"); break;\n        case STOPPED: puts(\"stopped\"); break;\n    }\n    return 0;\n}\n`,
    [["1\n", "running\n", "normal"], ["0\n", "idle\n", "boundary"], ["3\n", "invalid\n", "invalid"]],
  ),
  "c.aggregates.union": define(
    "c.aggregates.union",
    "tagged union with active-member discipline",
    "Read tag i or d and a value, store it in the matching member of a tagged union, and print int N or double N.NN without reading an inactive member.",
    `#include <stdio.h>\n\ntypedef enum { INTEGER_VALUE, DOUBLE_VALUE } ValueTag;\ntypedef struct { ValueTag tag; union { long long integer; double decimal; } data; } Value;\n\nint main(void) {\n    /* set the tag and matching member, then inspect safely */\n}\n`,
    `#include <stdio.h>\n\ntypedef enum { INTEGER_VALUE, DOUBLE_VALUE } ValueTag;\ntypedef struct { ValueTag tag; union { long long integer; double decimal; } data; } Value;\n\nint main(void) {\n    char tag;\n    if (scanf(\" %c\", &tag) != 1) return 1;\n    Value value;\n    if (tag == 'i') { value.tag = INTEGER_VALUE; if (scanf(\"%lld\", &value.data.integer) != 1) return 1; }\n    else if (tag == 'd') { value.tag = DOUBLE_VALUE; if (scanf(\"%lf\", &value.data.decimal) != 1) return 1; }\n    else { puts(\"invalid\"); return 0; }\n    if (value.tag == INTEGER_VALUE) printf(\"int %lld\\n\", value.data.integer);\n    else printf(\"double %.2f\\n\", value.data.decimal);\n    return 0;\n}\n`,
    [["i 42\n", "int 42\n", "normal"], ["d 0\n", "double 0.00\n", "boundary"], ["x 1\n", "invalid\n", "invalid"]],
  ),
  "c.aggregates.typedef": define(
    "c.aggregates.typedef",
    "clear alias for an existing structure type",
    "Use typedef to name a Point structure, read two points, and print their Manhattan distance while preserving the structure representation.",
    `#include <stdio.h>\n#include <stdlib.h>\n\n/* define Point alias */\n\nint main(void) {\n    /* read two Points and print distance */\n}\n`,
    `#include <stdio.h>\n#include <stdlib.h>\n\ntypedef struct { long x; long y; } Point;\n\nint main(void) {\n    Point a, b;\n    if (scanf(\"%ld %ld %ld %ld\", &a.x, &a.y, &b.x, &b.y) != 4) return 1;\n    printf(\"%ld\\n\", labs(a.x - b.x) + labs(a.y - b.y));\n    return 0;\n}\n`,
    [["1 2 4 6\n", "7\n", "normal"], ["0 0 0 0\n", "0\n", "boundary"], ["-2 3 2 -1\n", "8\n", "boundary"]],
  ),
  "c.memory.lifetime": define(
    "c.memory.lifetime",
    "static object lifetime without returning an automatic address",
    "Implement a function that stores each supplied integer in a function-local static object and returns its valid address, then print values from two sequential calls.",
    `#include <stdio.h>\n\nstatic const int *remember(int value) {\n    /* return an address that remains valid after return */\n}\n\nint main(void) {\n    /* call twice and print each observed value immediately */\n}\n`,
    `#include <stdio.h>\n\nstatic const int *remember(int value) {\n    static int stored;\n    stored = value;\n    return &stored;\n}\n\nint main(void) {\n    int first, second;\n    if (scanf(\"%d %d\", &first, &second) != 2) return 1;\n    const int *address = remember(first);\n    printf(\"%d \", *address);\n    address = remember(second);\n    printf(\"%d\\n\", *address);\n    return 0;\n}\n`,
    [["3 8\n", "3 8\n", "normal"], ["0 0\n", "0 0\n", "boundary"], ["-1 5\n", "-1 5\n", "boundary"]],
  ),
  "c.files.streams": define(
    "c.files.streams",
    "owned temporary stream with checked write, rewind, read, and close",
    "Read up to 20 integers, persist them to a temporary text stream, rewind and read them back, then print their sum while checking and closing the stream.",
    `#include <stdio.h>\n\nint main(void) {\n    /* acquire a temporary stream, round-trip values, and close */\n}\n`,
    `#include <stdio.h>\n\nint main(void) {\n    size_t count;\n    if (scanf(\"%zu\", &count) != 1 || count > 20) return 1;\n    FILE *stream = tmpfile();\n    if (stream == NULL) return 1;\n    for (size_t i = 0; i < count; ++i) { int value; if (scanf(\"%d\", &value) != 1 || fprintf(stream, \"%d\\n\", value) < 0) { fclose(stream); return 1; } }\n    rewind(stream);\n    long long sum = 0;\n    for (size_t i = 0; i < count; ++i) { int value; if (fscanf(stream, \"%d\", &value) != 1) { fclose(stream); return 1; } sum += value; }\n    if (fclose(stream) != 0) return 1;\n    printf(\"%lld\\n\", sum);\n    return 0;\n}\n`,
    [["4\n1 2 3 4\n", "10\n", "normal"], ["0\n", "0\n", "boundary"], ["2\n-5 5\n", "0\n", "boundary"]],
  ),
  "c.resources.cleanup": define(
    "c.resources.cleanup",
    "single failure-safe cleanup path for partially acquired resources",
    "Read up to 20 integers, allocate storage and acquire a temporary stream, print their sum, and release each acquired resource exactly once through one cleanup path.",
    `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int status = 1;\n    int *values = NULL;\n    FILE *stream = NULL;\n    /* acquire, use, then release exactly once */\n    return status;\n}\n`,
    `#include <stdio.h>\n#include <stdlib.h>\n\nint main(void) {\n    int status = 1;\n    int *values = NULL;\n    FILE *stream = NULL;\n    size_t count;\n    if (scanf(\"%zu\", &count) != 1 || count > 20) goto cleanup;\n    values = count == 0 ? NULL : malloc(count * sizeof *values);\n    if (count != 0 && values == NULL) goto cleanup;\n    stream = tmpfile();\n    if (stream == NULL) goto cleanup;\n    long long sum = 0;\n    for (size_t i = 0; i < count; ++i) { if (scanf(\"%d\", &values[i]) != 1) goto cleanup; sum += values[i]; }\n    printf(\"%lld\\n\", sum);\n    status = 0;\ncleanup:\n    if (stream != NULL) fclose(stream);\n    free(values);\n    return status;\n}\n`,
    [["3\n2 3 4\n", "9\n", "normal"], ["0\n", "0\n", "boundary"], ["2\n-2 2\n", "0\n", "boundary"]],
  ),
  "c.modular.preprocessor": define(
    "c.modular.preprocessor",
    "fully parenthesized expression macro for side-effect-free arguments",
    "Define a fully parenthesized SQUARE macro, read a long long value whose square is representable, and print the square; the task contract forbids side-effecting macro arguments.",
    `#include <stdio.h>\n\n/* define SQUARE for side-effect-free arguments */\n\nint main(void) {\n    long long value;\n    /* read and print SQUARE(value) */\n}\n`,
    `#include <stdio.h>\n\n#define SQUARE(value) ((value) * (value))\n\nint main(void) {\n    long long value;\n    if (scanf(\"%lld\", &value) != 1) return 1;\n    printf(\"%lld\\n\", SQUARE(value));\n    return 0;\n}\n`,
    [["7\n", "49\n", "normal"], ["0\n", "0\n", "boundary"], ["-3\n", "9\n", "boundary"]],
  ),
  "cpp.toolchain.program": define(
    "cpp.toolchain.program",
    "hosted main, stream I/O, and successful termination",
    "Read one integer in a hosted C++ program, print value plus one followed by a newline, and finish with successful main semantics.",
    `#include <iostream>\n\nint main() {\n    int value{};\n    // read, print value + 1, and finish successfully\n}\n`,
    `#include <iostream>\n\nint main() {\n    int value{};\n    if (!(std::cin >> value)) return 1;\n    std::cout << value + 1 << '\\n';\n    return 0;\n}\n`,
    [["4\n", "5\n", "normal"], ["-1\n", "0\n", "boundary"], ["0\n", "1\n", "boundary"]],
  ),
  "cpp.toolchain.namespaces": define(
    "cpp.toolchain.namespaces",
    "qualified lookup across same-named namespace functions",
    "Define scale in namespaces metric and binary, read m or b plus an integer, and call the selected function with explicit qualification; metric multiplies by 1000 and binary by 1024.",
    `#include <iostream>\n\nnamespace metric { /* define scale */ }\nnamespace binary { /* define scale */ }\n\nint main() {\n    // read mode and value, then use qualified lookup\n}\n`,
    `#include <iostream>\n\nnamespace metric { long long scale(long long value) { return value * 1000; } }\nnamespace binary { long long scale(long long value) { return value * 1024; } }\n\nint main() {\n    char mode{};\n    long long value{};\n    if (!(std::cin >> mode >> value)) return 1;\n    if (mode == 'm') std::cout << metric::scale(value) << '\\n';\n    else if (mode == 'b') std::cout << binary::scale(value) << '\\n';\n    else std::cout << "invalid\\n";\n}\n`,
    [["m 3\n", "3000\n", "normal"], ["b 0\n", "0\n", "boundary"], ["x 2\n", "invalid\n", "invalid"]],
  ),
  "cpp.fundamentals.types": define(
    "cpp.fundamentals.types",
    "fixed-width value type and explicit Boolean state",
    "Read two signed 64-bit integers, store whether their sum is nonzero in bool, and print active or inactive followed by the sum.",
    `#include <cstdint>\n#include <iostream>\n\nint main() {\n    std::int64_t left{}, right{};\n    // read, form explicit bool state, and print\n}\n`,
    `#include <cstdint>\n#include <iostream>\n\nint main() {\n    std::int64_t left{}, right{};\n    if (!(std::cin >> left >> right)) return 1;\n    std::int64_t sum = left + right;\n    bool active = sum != 0;\n    std::cout << (active ? "active " : "inactive ") << sum << '\\n';\n}\n`,
    [["4 7\n", "active 11\n", "normal"], ["0 0\n", "inactive 0\n", "boundary"], ["-3 3\n", "inactive 0\n", "boundary"]],
  ),
  "cpp.functions.contracts": define(
    "cpp.functions.contracts",
    "explicit precondition validation and optional result",
    "Implement safe_square with the documented input contract -1000000 through 1000000, returning std::optional<long long>; print the square or invalid.",
    `#include <iostream>\n#include <optional>\n\nstd::optional<long long> safe_square(long long value) {\n    // enforce the contract before multiplication\n}\n\nint main() {\n    // read, call, inspect optional\n}\n`,
    `#include <iostream>\n#include <optional>\n\nstd::optional<long long> safe_square(long long value) {\n    if (value < -1000000 || value > 1000000) return std::nullopt;\n    return value * value;\n}\n\nint main() {\n    long long value{};\n    if (!(std::cin >> value)) return 1;\n    if (auto result = safe_square(value)) std::cout << *result << '\\n';\n    else std::cout << "invalid\\n";\n}\n`,
    [["12\n", "144\n", "normal"], ["0\n", "0\n", "boundary"], ["1000001\n", "invalid\n", "invalid"]],
  ),
  "cpp.functions.parameters": define(
    "cpp.functions.parameters",
    "const-reference input and reference output parameters",
    "Implement summarize taking a vector by const reference and writing its minimum and maximum through references; read a nonempty vector and print both values.",
    `#include <iostream>\n#include <vector>\n\nvoid summarize(const std::vector<int>& values, int& minimum, int& maximum) {\n    // inspect without copying and assign outputs\n}\n\nint main() {\n    // read, call, print\n}\n`,
    `#include <iostream>\n#include <vector>\n\nvoid summarize(const std::vector<int>& values, int& minimum, int& maximum) {\n    minimum = maximum = values.front();\n    for (int value : values) { if (value < minimum) minimum = value; if (value > maximum) maximum = value; }\n}\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count == 0 || count > 100) return 1;\n    std::vector<int> values(count);\n    for (int& value : values) if (!(std::cin >> value)) return 1;\n    int minimum{}, maximum{};\n    summarize(values, minimum, maximum);\n    std::cout << minimum << ' ' << maximum << '\\n';\n}\n`,
    [["4\n9 2 7 3\n", "2 9\n", "normal"], ["1\n5\n", "5 5\n", "boundary"], ["3\n-8 -2 -5\n", "-8 -2\n", "boundary"]],
  ),
  "cpp.functions.overload": define(
    "cpp.functions.overload",
    "compile-time overload selection by distinct parameter types",
    "Provide label overloads for int and std::string, read tag i or s and a matching value, then print int:value or text:value using overload resolution.",
    `#include <iostream>\n#include <string>\n\n// define label overloads\n\nint main() {\n    // read tag, call matching overload\n}\n`,
    `#include <iostream>\n#include <string>\n\nstd::string label(int value) { return "int:" + std::to_string(value); }\nstd::string label(const std::string& value) { return "text:" + value; }\n\nint main() {\n    char tag{};\n    if (!(std::cin >> tag)) return 1;\n    if (tag == 'i') { int value{}; if (!(std::cin >> value)) return 1; std::cout << label(value) << '\\n'; }\n    else if (tag == 's') { std::string value; if (!(std::cin >> value)) return 1; std::cout << label(value) << '\\n'; }\n    else std::cout << "invalid\\n";\n}\n`,
    [["i 42\n", "int:42\n", "normal"], ["s x\n", "text:x\n", "boundary"], ["q 1\n", "invalid\n", "invalid"]],
  ),
  "cpp.classes.encapsulation": define(
    "cpp.classes.encapsulation",
    "private invariant protected by public operations",
    "Implement Account with a private nonnegative balance, deposit and withdraw operations that reject negative amounts and overdrafts, then print the resulting balance or rejected.",
    `#include <iostream>\n\nclass Account {\n    long long balance_;\npublic:\n    explicit Account(long long balance);\n    bool apply(long long amount);\n    long long balance() const;\n};\n\nint main() {\n    // read initial balance and signed transaction\n}\n`,
    `#include <iostream>\n\nclass Account {\n    long long balance_;\npublic:\n    explicit Account(long long balance) : balance_(balance >= 0 ? balance : 0) {}\n    bool apply(long long amount) { if (amount < 0 && -amount > balance_) return false; balance_ += amount; return true; }\n    long long balance() const { return balance_; }\n};\n\nint main() {\n    long long initial{}, transaction{};\n    if (!(std::cin >> initial >> transaction) || initial < 0) return 1;\n    Account account(initial);\n    if (!account.apply(transaction)) std::cout << "rejected\\n";\n    else std::cout << account.balance() << '\\n';\n}\n`,
    [["100 -30\n", "70\n", "normal"], ["0 0\n", "0\n", "boundary"], ["10 -11\n", "rejected\n", "boundary"]],
  ),
  "cpp.classes.construction": define(
    "cpp.classes.construction",
    "constructor-established class invariant",
    "Implement Rectangle so its constructor clamps negative dimensions to zero, expose a const area query, and print the area for two input dimensions.",
    `#include <iostream>\n\nclass Rectangle {\n    long long width_;\n    long long height_;\npublic:\n    Rectangle(long long width, long long height);\n    long long area() const;\n};\n\nint main() {\n    // construct and query\n}\n`,
    `#include <iostream>\n\nclass Rectangle {\n    long long width_;\n    long long height_;\npublic:\n    Rectangle(long long width, long long height) : width_(width < 0 ? 0 : width), height_(height < 0 ? 0 : height) {}\n    long long area() const { return width_ * height_; }\n};\n\nint main() {\n    long long width{}, height{};\n    if (!(std::cin >> width >> height)) return 1;\n    Rectangle rectangle(width, height);\n    std::cout << rectangle.area() << '\\n';\n}\n`,
    [["4 6\n", "24\n", "normal"], ["0 9\n", "0\n", "boundary"], ["-2 5\n", "0\n", "boundary"]],
  ),
  "cpp.classes.copy": define(
    "cpp.classes.copy",
    "independent value after copy construction",
    "Create a Value object, copy-construct a second object, change only the copy through a member function, and print original then copy to demonstrate independent value semantics.",
    `#include <iostream>\n\nclass Value {\n    int value_;\npublic:\n    explicit Value(int value);\n    void add(int amount);\n    int get() const;\n};\n\nint main() {\n    // construct, copy, mutate copy, print both\n}\n`,
    `#include <iostream>\n\nclass Value {\n    int value_;\npublic:\n    explicit Value(int value) : value_(value) {}\n    void add(int amount) { value_ += amount; }\n    int get() const { return value_; }\n};\n\nint main() {\n    int value{}, change{};\n    if (!(std::cin >> value >> change)) return 1;\n    Value original(value);\n    Value copy(original);\n    copy.add(change);\n    std::cout << original.get() << ' ' << copy.get() << '\\n';\n}\n`,
    [["5 3\n", "5 8\n", "normal"], ["0 0\n", "0 0\n", "boundary"], ["-2 5\n", "-2 3\n", "boundary"]],
  ),
  "cpp.classes.operators": define(
    "cpp.classes.operators",
    "meaningful value-type addition operator",
    "Define Point operator+ to add corresponding coordinates without mutating either operand, read two points, and print the resulting coordinates.",
    `#include <iostream>\n\nstruct Point { long long x; long long y; };\n// define operator+\n\nint main() {\n    // read two points, add, print\n}\n`,
    `#include <iostream>\n\nstruct Point { long long x; long long y; };\nPoint operator+(const Point& left, const Point& right) { return {left.x + right.x, left.y + right.y}; }\n\nint main() {\n    Point left{}, right{};\n    if (!(std::cin >> left.x >> left.y >> right.x >> right.y)) return 1;\n    Point result = left + right;\n    std::cout << result.x << ' ' << result.y << '\\n';\n}\n`,
    [["1 2 3 4\n", "4 6\n", "normal"], ["0 0 0 0\n", "0 0\n", "boundary"], ["-2 5 2 -5\n", "0 0\n", "boundary"]],
  ),
  "cpp.resources.raii": define(
    "cpp.resources.raii",
    "scope-bound acquisition and deterministic destruction",
    "Implement a Guard that increments a static live count in its constructor and decrements it in its destructor; print count and value inside a nested scope, then count after scope exit.",
    `#include <iostream>\n\nclass Guard {\n    int value_;\n    static int live_;\npublic:\n    explicit Guard(int value);\n    ~Guard();\n    int value() const;\n    static int live();\n};\n\nint main() {\n    // observe inside and after a scope\n}\n`,
    `#include <iostream>\n\nclass Guard {\n    int value_;\n    static int live_;\npublic:\n    explicit Guard(int value) : value_(value) { ++live_; }\n    ~Guard() { --live_; }\n    int value() const { return value_; }\n    static int live() { return live_; }\n};\nint Guard::live_ = 0;\n\nint main() {\n    int value{};\n    if (!(std::cin >> value)) return 1;\n    { Guard guard(value); std::cout << Guard::live() << ' ' << guard.value() << '\\n'; }\n    std::cout << Guard::live() << '\\n';\n}\n`,
    [["7\n", "1 7\n0\n", "normal"], ["0\n", "1 0\n0\n", "boundary"], ["-3\n", "1 -3\n0\n", "boundary"]],
  ),
  "cpp.resources.smart-pointers": define(
    "cpp.resources.smart-pointers",
    "exclusive ownership transfer with std::unique_ptr",
    "Create an integer with std::make_unique, move ownership to a second unique_ptr, and print empty plus the owned value to show the source no longer owns the object.",
    `#include <iostream>\n#include <memory>\n\nint main() {\n    int value{};\n    // allocate with make_unique, move ownership, print state\n}\n`,
    `#include <iostream>\n#include <memory>\n#include <utility>\n\nint main() {\n    int value{};\n    if (!(std::cin >> value)) return 1;\n    auto source = std::make_unique<int>(value);\n    std::unique_ptr<int> owner = std::move(source);\n    std::cout << (source ? "owned" : "empty") << ' ' << *owner << '\\n';\n}\n`,
    [["9\n", "empty 9\n", "normal"], ["0\n", "empty 0\n", "boundary"], ["-4\n", "empty -4\n", "boundary"]],
  ),
  "cpp.resources.exceptions": define(
    "cpp.resources.exceptions",
    "typed exception for a violated operation precondition",
    "Implement checked_divide that throws std::invalid_argument for a zero divisor, call it inside try, and print either integer quotient or division-by-zero from the catch handler.",
    `#include <iostream>\n#include <stdexcept>\n\nlong long checked_divide(long long numerator, long long denominator) {\n    // throw for zero, otherwise divide\n}\n\nint main() {\n    // read, try, catch\n}\n`,
    `#include <iostream>\n#include <stdexcept>\n\nlong long checked_divide(long long numerator, long long denominator) {\n    if (denominator == 0) throw std::invalid_argument("zero divisor");\n    return numerator / denominator;\n}\n\nint main() {\n    long long numerator{}, denominator{};\n    if (!(std::cin >> numerator >> denominator)) return 1;\n    try { std::cout << checked_divide(numerator, denominator) << '\\n'; }\n    catch (const std::invalid_argument&) { std::cout << "division-by-zero\\n"; }\n}\n`,
    [["9 3\n", "3\n", "normal"], ["5 0\n", "division-by-zero\n", "boundary"], ["0 2\n", "0\n", "boundary"]],
  ),
  "cpp.resources.move": define(
    "cpp.resources.move",
    "explicit moved-from state in a move-only owner",
    "Implement move construction for a Token owning an int through unique_ptr, transfer ownership while leaving the source empty, then print empty and the destination value.",
    `#include <iostream>\n#include <memory>\n\nclass Token {\n    std::unique_ptr<int> value_;\npublic:\n    explicit Token(int value);\n    Token(Token&& other) noexcept;\n    bool empty() const;\n    int value() const;\n};\n\nint main() {\n    // construct, move, inspect\n}\n`,
    `#include <iostream>\n#include <memory>\n#include <utility>\n\nclass Token {\n    std::unique_ptr<int> value_;\npublic:\n    explicit Token(int value) : value_(std::make_unique<int>(value)) {}\n    Token(Token&& other) noexcept : value_(std::move(other.value_)) {}\n    Token(const Token&) = delete;\n    Token& operator=(const Token&) = delete;\n    bool empty() const { return !value_; }\n    int value() const { return *value_; }\n};\n\nint main() {\n    int value{};\n    if (!(std::cin >> value)) return 1;\n    Token source(value);\n    Token destination(std::move(source));\n    std::cout << (source.empty() ? "empty" : "owned") << ' ' << destination.value() << '\\n';\n}\n`,
    [["12\n", "empty 12\n", "normal"], ["0\n", "empty 0\n", "boundary"], ["-9\n", "empty -9\n", "boundary"]],
  ),
  "cpp.polymorphism.composition": define(
    "cpp.polymorphism.composition",
    "has-a composition with delegated behavior",
    "Model Car as containing an Engine whose efficiency multiplies fuel into distance, read efficiency and fuel, and print Car::range after delegating to the component.",
    `#include <iostream>\n\nclass Engine { /* efficiency and distance */ };\nclass Car { /* contain Engine and delegate range */ };\n\nint main() {\n    // construct composed object and query\n}\n`,
    `#include <iostream>\n\nclass Engine {\n    long long efficiency_;\npublic:\n    explicit Engine(long long efficiency) : efficiency_(efficiency) {}\n    long long distance(long long fuel) const { return efficiency_ * fuel; }\n};\nclass Car {\n    Engine engine_;\npublic:\n    explicit Car(long long efficiency) : engine_(efficiency) {}\n    long long range(long long fuel) const { return engine_.distance(fuel); }\n};\n\nint main() {\n    long long efficiency{}, fuel{};\n    if (!(std::cin >> efficiency >> fuel)) return 1;\n    Car car(efficiency);\n    std::cout << car.range(fuel) << '\\n';\n}\n`,
    [["15 4\n", "60\n", "normal"], ["10 0\n", "0\n", "boundary"], ["0 8\n", "0\n", "boundary"]],
  ),
  "cpp.polymorphism.inheritance": define(
    "cpp.polymorphism.inheritance",
    "is-a specialization reusing a protected base contract",
    "Define Employee with a protected base pay and Developer deriving publicly with a total_pay member that adds a bonus; read both values and print the result.",
    `#include <iostream>\n\nclass Employee { /* protected base pay */ };\nclass Developer : public Employee { /* add bonus behavior */ };\n\nint main() {\n    // construct derived value and query\n}\n`,
    `#include <iostream>\n\nclass Employee {\nprotected:\n    long long base_pay_;\npublic:\n    explicit Employee(long long base_pay) : base_pay_(base_pay) {}\n};\nclass Developer : public Employee {\npublic:\n    using Employee::Employee;\n    long long total_pay(long long bonus) const { return base_pay_ + bonus; }\n};\n\nint main() {\n    long long base{}, bonus{};\n    if (!(std::cin >> base >> bonus)) return 1;\n    Developer developer(base);\n    std::cout << developer.total_pay(bonus) << '\\n';\n}\n`,
    [["100 25\n", "125\n", "normal"], ["0 0\n", "0\n", "boundary"], ["50 -10\n", "40\n", "boundary"]],
  ),
  "cpp.polymorphism.virtual": define(
    "cpp.polymorphism.virtual",
    "runtime dispatch through a virtual interface",
    "Define Shape with a virtual area query and virtual destructor, implement Square and Rectangle, select one from input through unique_ptr<Shape>, and print its area.",
    `#include <iostream>\n#include <memory>\n\nclass Shape { /* virtual interface */ };\nclass Square : public Shape { /* override area */ };\nclass Rectangle : public Shape { /* override area */ };\n\nint main() {\n    // construct through base owner and dispatch\n}\n`,
    `#include <iostream>\n#include <memory>\n\nclass Shape { public: virtual ~Shape() = default; virtual long long area() const = 0; };\nclass Square : public Shape { long long side_; public: explicit Square(long long side) : side_(side) {} long long area() const override { return side_ * side_; } };\nclass Rectangle : public Shape { long long width_, height_; public: Rectangle(long long width, long long height) : width_(width), height_(height) {} long long area() const override { return width_ * height_; } };\n\nint main() {\n    char kind{};\n    if (!(std::cin >> kind)) return 1;\n    std::unique_ptr<Shape> shape;\n    if (kind == 's') { long long side{}; if (!(std::cin >> side)) return 1; shape = std::make_unique<Square>(side); }\n    else if (kind == 'r') { long long width{}, height{}; if (!(std::cin >> width >> height)) return 1; shape = std::make_unique<Rectangle>(width, height); }\n    else { std::cout << "invalid\\n"; return 0; }\n    std::cout << shape->area() << '\\n';\n}\n`,
    [["r 3 5\n", "15\n", "normal"], ["s 0\n", "0\n", "boundary"], ["x 1\n", "invalid\n", "invalid"]],
  ),
  "cpp.polymorphism.slicing-casts": define(
    "cpp.polymorphism.slicing-casts",
    "reference-preserved dynamic type and checked downcast",
    "Pass a Dog through an Animal reference without slicing, use dynamic_cast to check the derived type, and print dog plus its age when the cast succeeds.",
    `#include <iostream>\n\nclass Animal { public: virtual ~Animal() = default; };\nclass Dog : public Animal { /* age */ };\n\nint main() {\n    // bind base reference and perform checked cast\n}\n`,
    `#include <iostream>\n\nclass Animal { public: virtual ~Animal() = default; };\nclass Dog : public Animal { int age_; public: explicit Dog(int age) : age_(age) {} int age() const { return age_; } };\n\nint main() {\n    int age{};\n    if (!(std::cin >> age)) return 1;\n    Dog dog(age);\n    Animal& animal = dog;\n    if (const auto* derived = dynamic_cast<const Dog*>(&animal)) std::cout << "dog " << derived->age() << '\\n';\n    else std::cout << "not-dog\\n";\n}\n`,
    [["5\n", "dog 5\n", "normal"], ["0\n", "dog 0\n", "boundary"], ["-1\n", "dog -1\n", "boundary"]],
  ),
  "cpp.containers.associative": define(
    "cpp.containers.associative",
    "ordered map insertion and frequency lookup",
    "Read up to 30 whitespace-delimited words, count them in std::map, and print key=count pairs in key order separated by single spaces.",
    `#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n    // read, count in map, print ordered entries\n}\n`,
    `#include <iostream>\n#include <map>\n#include <string>\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count > 30) return 1;\n    std::map<std::string, int> frequencies;\n    for (std::size_t i = 0; i < count; ++i) { std::string word; if (!(std::cin >> word)) return 1; ++frequencies[word]; }\n    bool first = true;\n    for (const auto& [word, frequency] : frequencies) { if (!first) std::cout << ' '; first = false; std::cout << word << '=' << frequency; }\n    std::cout << '\\n';\n}\n`,
    [["5\npear apple pear kiwi apple\n", "apple=2 kiwi=1 pear=2\n", "normal"], ["0\n", "\n", "boundary"], ["1\nx\n", "x=1\n", "boundary"]],
  ),
  "cpp.containers.adaptors": define(
    "cpp.containers.adaptors",
    "FIFO semantics through the queue adaptor",
    "Read up to 30 integers into std::queue and remove them in FIFO order, printing values separated by single spaces.",
    `#include <iostream>\n#include <queue>\n\nint main() {\n    // push, then consume through front and pop\n}\n`,
    `#include <iostream>\n#include <queue>\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count > 30) return 1;\n    std::queue<int> values;\n    for (std::size_t i = 0; i < count; ++i) { int value{}; if (!(std::cin >> value)) return 1; values.push(value); }\n    bool first = true;\n    while (!values.empty()) { if (!first) std::cout << ' '; first = false; std::cout << values.front(); values.pop(); }\n    std::cout << '\\n';\n}\n`,
    [["4\n3 1 4 2\n", "3 1 4 2\n", "normal"], ["0\n", "\n", "boundary"], ["1\n-5\n", "-5\n", "boundary"]],
  ),
  "cpp.containers.iterators": define(
    "cpp.containers.iterators",
    "valid half-open iterator range",
    "Read a vector and use iterators to sum the half-open interior range excluding the first and last elements; print zero when fewer than three elements exist.",
    `#include <iostream>\n#include <numeric>\n#include <vector>\n\nint main() {\n    // form only valid half-open iterator ranges\n}\n`,
    `#include <iostream>\n#include <numeric>\n#include <vector>\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count > 100) return 1;\n    std::vector<long long> values(count);\n    for (auto& value : values) if (!(std::cin >> value)) return 1;\n    long long sum = count < 3 ? 0 : std::accumulate(values.begin() + 1, values.end() - 1, 0LL);\n    std::cout << sum << '\\n';\n}\n`,
    [["5\n1 2 3 4 5\n", "9\n", "normal"], ["0\n", "0\n", "boundary"], ["2\n7 8\n", "0\n", "boundary"]],
  ),
  "cpp.algorithms.lambdas": define(
    "cpp.algorithms.lambdas",
    "capturing predicate supplied to a standard algorithm",
    "Read a threshold and vector, capture the threshold in a lambda passed to std::count_if, and print how many values are strictly greater.",
    `#include <algorithm>\n#include <iostream>\n#include <vector>\n\nint main() {\n    // read and use a capturing lambda with count_if\n}\n`,
    `#include <algorithm>\n#include <iostream>\n#include <vector>\n\nint main() {\n    int threshold{};\n    std::size_t count{};\n    if (!(std::cin >> threshold >> count) || count > 100) return 1;\n    std::vector<int> values(count);\n    for (int& value : values) if (!(std::cin >> value)) return 1;\n    auto result = std::count_if(values.begin(), values.end(), [threshold](int value) { return value > threshold; });\n    std::cout << result << '\\n';\n}\n`,
    [["3 5\n1 4 3 9 0\n", "2\n", "normal"], ["0 0\n", "0\n", "boundary"], ["5 3\n5 5 5\n", "0\n", "boundary"]],
  ),
  "cpp.algorithms.comparators": define(
    "cpp.algorithms.comparators",
    "strict weak ordering with an explicit tie-breaker",
    "Read name-score records and sort them by descending score then ascending name using a comparator, printing the names in order.",
    `#include <algorithm>\n#include <iostream>\n#include <string>\n#include <vector>\n\nstruct Record { std::string name; int score; };\n\nint main() {\n    // sort with a complete tie-breaker\n}\n`,
    `#include <algorithm>\n#include <iostream>\n#include <string>\n#include <vector>\n\nstruct Record { std::string name; int score; };\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count > 30) return 1;\n    std::vector<Record> records(count);\n    for (auto& record : records) if (!(std::cin >> record.name >> record.score)) return 1;\n    std::sort(records.begin(), records.end(), [](const Record& a, const Record& b) { return a.score != b.score ? a.score > b.score : a.name < b.name; });\n    for (std::size_t i = 0; i < records.size(); ++i) { if (i) std::cout << ' '; std::cout << records[i].name; }\n    std::cout << '\\n';\n}\n`,
    [["3\nzoe 8 amy 9 bob 8\n", "amy bob zoe\n", "normal"], ["0\n", "\n", "boundary"], ["2\nb 1 a 1\n", "a b\n", "boundary"]],
  ),
  "cpp.algorithms.ranges": define(
    "cpp.algorithms.ranges",
    "lazy C++20 filter and transform view pipeline",
    "Read integers and build a C++20 ranges pipeline that keeps even values and squares them, then print the resulting values separated by spaces.",
    `#include <iostream>\n#include <ranges>\n#include <vector>\n\nint main() {\n    // compose filter and transform views, then iterate\n}\n`,
    `#include <iostream>\n#include <ranges>\n#include <vector>\n\nint main() {\n    std::size_t count{};\n    if (!(std::cin >> count) || count > 100) return 1;\n    std::vector<long long> values(count);\n    for (auto& value : values) if (!(std::cin >> value)) return 1;\n    auto result = values | std::views::filter([](long long value) { return value % 2 == 0; }) | std::views::transform([](long long value) { return value * value; });\n    bool first = true;\n    for (long long value : result) { if (!first) std::cout << ' '; first = false; std::cout << value; }\n    std::cout << '\\n';\n}\n`,
    [["5\n1 2 3 4 5\n", "4 16\n", "normal"], ["0\n", "\n", "boundary"], ["3\n1 3 5\n", "\n", "boundary"]],
  ),
  "cpp.generics.class-template": define(
    "cpp.generics.class-template",
    "type-parameterized value class with const queries",
    "Define a PairBox class template storing two values and returning min and max const references, instantiate it for long long, and print min then max.",
    `#include <iostream>\n\ntemplate <typename T>\nclass PairBox {\n    // store two T values and expose min/max\n};\n\nint main() {\n    // instantiate and query\n}\n`,
    `#include <iostream>\n\ntemplate <typename T>\nclass PairBox {\n    T first_;\n    T second_;\npublic:\n    PairBox(T first, T second) : first_(first), second_(second) {}\n    const T& minimum() const { return second_ < first_ ? second_ : first_; }\n    const T& maximum() const { return first_ < second_ ? second_ : first_; }\n};\n\nint main() {\n    long long first{}, second{};\n    if (!(std::cin >> first >> second)) return 1;\n    PairBox<long long> values(first, second);\n    std::cout << values.minimum() << ' ' << values.maximum() << '\\n';\n}\n`,
    [["8 3\n", "3 8\n", "normal"], ["5 5\n", "5 5\n", "boundary"], ["-2 -9\n", "-9 -2\n", "boundary"]],
  ),
  "cpp.generics.requirements": define(
    "cpp.generics.requirements",
    "C++20 concept-constrained generic addition",
    "Define an Addable concept requiring a + b convertible to T, constrain an add function with it, and compose the function to sum three long long values.",
    `#include <concepts>\n#include <iostream>\n\n// define Addable and constrained add\n\nint main() {\n    // read three values and compose add\n}\n`,
    `#include <concepts>\n#include <iostream>\n\ntemplate <typename T>\nconcept Addable = requires(T a, T b) { { a + b } -> std::convertible_to<T>; };\n\ntemplate <Addable T>\nT add(const T& a, const T& b) { return a + b; }\n\nint main() {\n    long long a{}, b{}, c{};\n    if (!(std::cin >> a >> b >> c)) return 1;\n    std::cout << add(add(a, b), c) << '\\n';\n}\n`,
    [["1 2 3\n", "6\n", "normal"], ["0 0 0\n", "0\n", "boundary"], ["-5 2 3\n", "0\n", "boundary"]],
  ),
  "cpp.generics.variants": define(
    "cpp.generics.variants",
    "closed type-safe sum type and exhaustive visitor",
    "Read tag i or s and a matching integer or word into std::variant<int,std::string>, then use std::visit to print int:value or text:value.",
    `#include <iostream>\n#include <string>\n#include <variant>\n\nint main() {\n    // construct matching alternative and visit\n}\n`,
    `#include <iostream>\n#include <string>\n#include <type_traits>\n#include <variant>\n\nint main() {\n    char tag{};\n    if (!(std::cin >> tag)) return 1;\n    std::variant<int, std::string> value;\n    if (tag == 'i') { int number{}; if (!(std::cin >> number)) return 1; value = number; }\n    else if (tag == 's') { std::string text; if (!(std::cin >> text)) return 1; value = text; }\n    else { std::cout << "invalid\\n"; return 0; }\n    std::visit([](const auto& item) { using T = std::decay_t<decltype(item)>; if constexpr (std::is_same_v<T, int>) std::cout << "int:" << item << '\\n'; else std::cout << "text:" << item << '\\n'; }, value);\n}\n`,
    [["s buddy\n", "text:buddy\n", "normal"], ["i 0\n", "int:0\n", "boundary"], ["x value\n", "invalid\n", "invalid"]],
  ),
  "cpp.quality.io": define(
    "cpp.quality.io",
    "quoted stream extraction preserving embedded spaces",
    "Read one std::quoted string, then print its character count, a colon, and the original text; reject malformed extraction by returning failure.",
    `#include <iomanip>\n#include <iostream>\n#include <string>\n\nint main() {\n    std::string text;\n    // use std::quoted extraction and print length:text\n}\n`,
    `#include <iomanip>\n#include <iostream>\n#include <string>\n\nint main() {\n    std::string text;\n    if (!(std::cin >> std::quoted(text))) return 1;\n    std::cout << text.size() << ':' << text << '\\n';\n}\n`,
    [["\"hello world\"\n", "11:hello world\n", "normal"], ["\"\"\n", "0:\n", "boundary"], ["\"x\"\n", "1:x\n", "boundary"]],
  ),
  "cpp.quality.tests": define(
    "cpp.quality.tests",
    "embedded boundary assertions plus observable classification",
    "Implement is_even, keep the supplied embedded checks for zero, negative, odd, and even values, then classify one input as even or odd only after the checks pass.",
    `#include <array>\n#include <iostream>\n\nbool is_even(long long value) {\n    // implement\n}\n\nint main() {\n    // retain embedded boundary checks, then classify input\n}\n`,
    `#include <array>\n#include <iostream>\n\nbool is_even(long long value) { return value % 2 == 0; }\n\nint main() {\n    const std::array<std::pair<long long, bool>, 4> checks{{{0, true}, {-2, true}, {1, false}, {7, false}}};\n    for (const auto& [input, expected] : checks) if (is_even(input) != expected) return 2;\n    long long value{};\n    if (!(std::cin >> value)) return 1;\n    std::cout << (is_even(value) ? "even" : "odd") << '\\n';\n}\n`,
    [["8\n", "even\n", "normal"], ["0\n", "even\n", "boundary"], ["-3\n", "odd\n", "boundary"]],
  ),
};
