export interface TrancheTeachingSeed {
  readonly model: string;
  readonly boundary: string;
  readonly scenarioA: string;
  readonly scenarioB: string;
  readonly misconception: string;
  readonly correction: string;
}

/**
 * Explicit topic-specific editorial seeds. These are not approved prose. The
 * generator expands only structure; every factual model, boundary, scenario,
 * misconception, and correction below is deliberately authored per skill.
 */
export const FOUNDATIONS_GIT_TRANCHE_SEEDS = {
  "pf.computing.hardware-software": {
    model: "A processor executes instructions, working memory holds active instructions and data, storage retains files, devices exchange data, and the operating system coordinates access to hardware.",
    boundary: "Real machines use caches, virtual memory, firmware, accelerators, and many operating-system layers, so the simple processor-memory-storage picture is a first model rather than a wiring diagram.",
    scenarioA: "An image editor loads compressed bytes from storage into working memory while the processor applies a crop operation and the display shows the changed pixels.",
    scenarioB: "Saving the image asks the operating system to persist new bytes; closing without saving can discard the in-memory edit while the old stored file remains.",
    misconception: "Adding more disk storage always makes every running program faster because storage and working memory are the same resource.",
    correction: "Storage capacity and working memory serve different roles; performance depends on the actual bottleneck, while unsaved active state can disappear even when ample storage exists.",
  },
  "pf.computing.execution": {
    model: "Source text reaches observable behavior through a named toolchain: a compiler may translate ahead of time, an interpreter may execute through another runtime, and a virtual machine may execute an intermediate form.",
    boundary: "Compiled and interpreted are not permanent language categories; one implementation can combine ahead-of-time compilation, bytecode, interpretation, and just-in-time compilation.",
    scenarioA: "A C source file is passed to a compiler and linker, producing an executable that the operating system loads before its output appears.",
    scenarioB: "A Java source file becomes bytecode that a JVM loads and may interpret or compile further while the application is running.",
    misconception: "Compiled languages run directly from source while interpreted languages never translate any code.",
    correction: "Execution must name the concrete implementation and stages; source is represented or translated before a processor carries out machine instructions, and runtimes can mix strategies.",
  },
  "pf.computing.determinism": {
    model: "A deterministic computation produces the same observable result when its defined instructions, input, initial state, and relevant environment are the same.",
    boundary: "Time, randomness, concurrency schedules, network responses, uninitialized data, undefined behavior, and external files can change relevant state or environment between runs.",
    scenarioA: "A pure arithmetic routine receives the same two integers twice in the same defined runtime and produces the same sum both times.",
    scenarioB: "A greeting program includes the current clock time, so identical source and typed name can still yield different output on two runs.",
    misconception: "The same source file must always produce identical output, regardless of input, state, environment, or undefined behavior.",
    correction: "Agreement is expected only after holding all relevant inputs and defined state constant; differing observations should be traced to a changed input, state, environment, or invalid assumption.",
  },
  "pf.problem.io": {
    model: "A solvable programming problem states the data received, the observable result required, and the constraints that every acceptable result must respect.",
    boundary: "Examples illustrate a contract but do not replace it, and hidden assumptions such as units, valid ranges, ordering, duplicates, or empty input must be made explicit.",
    scenarioA: "A fare calculator receives distance in whole kilometers and passenger category, returns rupees, and must reject negative distance.",
    scenarioB: "A username checker receives text, returns valid or invalid, and declares allowed characters, length limits, and case rules.",
    misconception: "A feature request such as make a calculator is precise enough because the programmer can guess inputs and expected behavior later.",
    correction: "Implementation should begin only after inputs, outputs, constraints, units, and invalid cases are explicit enough to test without guessing intent.",
  },
  "pf.problem.decomposition": {
    model: "Decomposition divides one requirement into cohesive subproblems whose inputs and outputs connect and whose combined behavior covers the original need.",
    boundary: "Splitting work by arbitrary line count or creating fragments with hidden shared state does not produce useful decomposition, and integration responsibilities must remain visible.",
    scenarioA: "A quiz application is separated into loading questions, presenting one question, checking an answer, updating score, and reporting the final result.",
    scenarioB: "An expense report is separated into parsing entries, validating currency and dates, aggregating categories, and formatting a summary.",
    misconception: "Decomposition means writing many tiny functions even when their responsibilities and interfaces are unclear.",
    correction: "A good decomposition names responsibilities and data flow so each part can be understood and tested while the parts still cover the complete requirement.",
  },
  "pf.problem.pseudocode": {
    model: "Structured pseudocode expresses precise executable intent with sequence, selection, iteration, and named operations without depending on one language's punctuation.",
    boundary: "Pseudocode is not an excuse for ambiguous phrases such as handle errors somehow; its conventions, inputs, state changes, and termination must still be traceable.",
    scenarioA: "Pseudocode for an average initializes total, visits each value, updates total, and divides by the count only after checking that the collection is nonempty.",
    scenarioB: "Pseudocode for ticket eligibility tests age and membership in explicit branches before returning one named decision.",
    misconception: "Any informal paragraph counts as pseudocode even when two readers could execute different steps from it.",
    correction: "Useful pseudocode has unambiguous control flow and state effects that another person can trace and translate without inventing missing decisions.",
  },
  "pf.problem.examples": {
    model: "Representative, boundary, and invalid examples turn an abstract contract into checkable observations and often reveal missing constraints before implementation.",
    boundary: "A handful of examples cannot prove correctness for every input, and expected results must be derived from the contract rather than copied from the implementation under test.",
    scenarioA: "For an age rule of 18 or older, examples include 25 as representative, 17 and 18 around the boundary, and negative age as invalid.",
    scenarioB: "For a list maximum, examples include mixed values, one value, duplicate maxima, all negative values, and an explicitly handled empty list.",
    misconception: "One normal example is enough because boundary and invalid inputs are unlikely to occur in real use.",
    correction: "Examples should deliberately cover equivalence classes, boundaries, emptiness, duplication, sign, and invalid data that can change the required behavior.",
  },
  "pf.state.values-types": {
    model: "A value's conceptual type determines which operations are meaningful, such as arithmetic for numbers, logical operations for truth values, and ordered character operations for text.",
    boundary: "Concrete languages differ in numeric ranges, coercion, representation, nullability, and collection types, so conceptual compatibility does not guarantee identical runtime behavior.",
    scenarioA: "The text value 12 can be joined with kg to display 12kg, while the numeric value 12 can be added to 3 to produce 15.",
    scenarioB: "A truth value records whether access is allowed, while a collection records several permissions that must be searched or traversed.",
    misconception: "Values that look similar on screen always support the same operations, so text 12 and number 12 are interchangeable.",
    correction: "Choose and validate a type from the intended operations; convert representations explicitly when moving between text, numbers, truth values, and collections.",
  },
  "pf.state.expressions": {
    model: "An expression combines operands and operators to produce a value; evaluation follows declared grouping, precedence, short-circuit, and type rules while creating intermediate results.",
    boundary: "Precedence varies by operator and language, floating-point arithmetic is not exact real arithmetic, and side effects inside expressions can make order important or unsafe.",
    scenarioA: "The expression 2 + 3 * 4 evaluates multiplication first to 12 and then addition to 14, while parentheses can request a different grouping.",
    scenarioB: "The Boolean expression hasTicket AND age >= 18 can stop after a false hasTicket in a language with short-circuit conjunction.",
    misconception: "Expressions are always evaluated strictly from left to right, regardless of parentheses or operator precedence.",
    correction: "Trace the syntax tree or explicit grouping, evaluate inner and higher-precedence operations first, and apply the runtime's documented order and type rules.",
  },
  "pf.state.mutation": {
    model: "Rebinding changes which value a name denotes, while mutation changes the state of an existing mutable object that may be reachable through more than one name.",
    boundary: "Languages differ in reference, value, copy, and immutability semantics, so alias behavior must be confirmed for the concrete type and operation.",
    scenarioA: "Two names refer to the same shopping-list object; appending through one name makes the added item visible when reading through the other.",
    scenarioB: "Reassigning one name to a new list leaves the original shared list unchanged for another name that still refers to it.",
    misconception: "Assigning or updating through one name can never affect a value observed through another name.",
    correction: "First trace which names reach the same mutable object, then distinguish changing that object from rebinding one name to a different value.",
  },
  "pf.control.sequence": {
    model: "Sequential statements complete in a defined order, and each statement reads the state produced by earlier statements before creating the next state.",
    boundary: "Function calls, exceptions, asynchronous work, and concurrency can interrupt or defer apparent textual order, so this model applies to the declared synchronous path.",
    scenarioA: "A receipt routine reads price, computes tax from price, then computes total from both values; moving total before tax breaks its dependency.",
    scenarioB: "A conversion routine parses text before multiplying the number and formats output only after the calculation succeeds.",
    misconception: "Independent-looking lines may be freely reordered because a program eventually executes all of them anyway.",
    correction: "Preserve data and effect dependencies by tracing the state after each statement and moving a statement only when its reads and writes remain valid.",
  },
  "pf.control.selection": {
    model: "Selection evaluates Boolean conditions to choose the one appropriate path, with branch order and boundary comparisons determining which path handles each input.",
    boundary: "Overlapping conditions, unreachable branches, missing default behavior, and floating-point comparisons can make an apparently complete decision incomplete or order-dependent.",
    scenarioA: "A grading rule tests score at least 90 before score at least 75 so a score of 95 reaches the highest band instead of the first broad match.",
    scenarioB: "A delivery rule handles negative distance as invalid, zero as pickup, up to five as local, and larger values as extended delivery.",
    misconception: "Separate if statements and one if-else-if chain always have identical behavior when several conditions are true.",
    correction: "Choose independent or mutually exclusive branches deliberately, order overlapping conditions from specific to broad, and test every boundary and default path.",
  },
  "pf.control.iteration": {
    model: "A loop needs an initial state, a continuation condition or next element, a body, progress toward completion, and a clear state when repetition stops.",
    boundary: "Empty input, one iteration, off-by-one bounds, mutation during traversal, and conditions that never change are distinct cases that can break termination or coverage.",
    scenarioA: "A counted loop visits indexes zero through length minus one exactly once and never reads the nonexistent index equal to length.",
    scenarioB: "A password retry loop stops on success or after three failed attempts, updating the attempt count on every failed path.",
    misconception: "A loop terminates automatically once its body has run enough times, even if the condition never changes.",
    correction: "Identify and test the progress measure on every path, then prove that the continuation condition eventually becomes false or input is exhausted.",
  },
  "pf.control.nested": {
    model: "With nested control flow, the inner construct completes for each applicable outer state; total executions are derived by tracing both levels and their bounds.",
    boundary: "Rows can have different lengths, inner branches can skip work, and resetting an inner counter in the wrong place changes both coverage and execution count.",
    scenarioA: "A grid traversal visits each row and then each column in that row, producing one coordinate pair per cell including row and column zero.",
    scenarioB: "A timetable comparison visits each student and each registered course, but skips inactive registrations before counting matches.",
    misconception: "Two nested loops each running n times perform about n steps rather than up to n multiplied by n inner executions.",
    correction: "Trace the inner loop separately for every outer iteration and multiply or sum the actual per-outer counts while respecting branches and irregular sizes.",
  },
  "pf.abstraction.functions": {
    model: "A function contract states purpose, inputs, returned result, observable effects, preconditions, and failure behavior independently of the implementation steps.",
    boundary: "A short name or type signature alone does not describe units, valid ranges, side effects, exceptions, mutation, or ordering guarantees.",
    scenarioA: "A convertCelsius function accepts a finite Fahrenheit number, returns a Celsius number, and does not print or mutate external state.",
    scenarioB: "A withdraw function requires a positive amount not exceeding balance, returns the new balance, and declares how invalid requests fail.",
    misconception: "Knowing a function's name and parameter count is enough to use it safely without understanding its contract.",
    correction: "Callers and tests need explicit input constraints, result meaning, effects, and failure rules; implementation can change while that contract remains stable.",
  },
  "pf.abstraction.calls": {
    model: "A call evaluates arguments, binds resulting values to parameters in a new call frame, executes local statements, and returns control and an optional result to the caller.",
    boundary: "Argument evaluation order, pass-by-value details, reference sharing, default arguments, recursion, exceptions, and asynchronous calls vary by language and function.",
    scenarioA: "Calling area(3, 4) binds width to 3 and height to 4 in a new frame, computes 12, returns 12, and removes that frame.",
    scenarioB: "An outer total call pauses while an inner discount call computes its result, then resumes with that returned value in the outer frame.",
    misconception: "Parameters permanently replace the caller's variable names, so a function has no separate local frame.",
    correction: "Trace caller and callee frames separately: arguments produce values, parameters are local bindings, and only declared returned values or effects cross the boundary.",
  },
  "pf.abstraction.scope": {
    model: "Scope determines where a name can be resolved, while lifetime determines how long its associated storage or value exists; a local name normally belongs to its block or call frame.",
    boundary: "Languages differ in block, function, module, class, closure, and dynamic scope rules, and a captured value may outlive the call that created its local name.",
    scenarioA: "A local variable named total inside calculate does not overwrite an unrelated total in the caller unless an explicit shared object or global is updated.",
    scenarioB: "Two functions can each use a local index name because each call resolves that name in a separate scope and frame.",
    misconception: "If two variables share the same spelling anywhere in a program, they must refer to one global value.",
    correction: "Resolve each use from its lexical context and active frame, and make cross-scope state explicit rather than assuming identical spelling implies identity.",
  },
  "pf.abstraction.recursion": {
    model: "A recursive definition solves a problem using a base case and calls on strictly smaller or otherwise progressing instances, with each call receiving its own frame.",
    boundary: "A reachable base case is necessary but not sufficient: every recursive path must progress toward it, and deep recursion can exceed runtime stack limits.",
    scenarioA: "Factorial of three calls factorial of two, then one, reaches the base result, and multiplies returned values while frames unwind.",
    scenarioB: "A folder-size routine returns a file's size directly and recursively sums each child only when the current item is a folder.",
    misconception: "Adding any base-case branch guarantees termination even if recursive calls keep the same argument.",
    correction: "Check both reachability and progress: each recursive path must move a well-founded measure toward a base case before the call can return.",
  },
  "pf.data.sequences": {
    model: "A sequence stores ordered elements at valid positions; indexed access, update, slicing, and traversal must respect empty input and the first and last valid indexes.",
    boundary: "Index origins, negative indexes, slicing bounds, mutability, and out-of-range behavior differ by language and sequence type.",
    scenarioA: "For four items with zero-based indexing, valid indexes are zero through three and a loop condition index less than length visits each exactly once.",
    scenarioB: "Removing the first queue item changes later positions, so cached indexes must be reconsidered before another access.",
    misconception: "A sequence of length four has a valid element at index four because length names the last position.",
    correction: "For a zero-based sequence, the last valid index is length minus one; test empty, first, last, and one-past-last cases explicitly.",
  },
  "pf.data.records": {
    model: "A record groups named fields that describe one conceptual entity, with each field chosen for a defined meaning, type, optionality, and validation rule.",
    boundary: "Records do not automatically enforce identity, uniqueness, normalization, privacy, or database relationships, and duplicated derived fields can become inconsistent.",
    scenarioA: "A student record groups id, display name, enrollment date, and active status while keeping calculated progress outside the editable identity fields.",
    scenarioB: "A coordinate record names latitude and longitude with range constraints so callers do not confuse two unlabeled numeric positions.",
    misconception: "Any values frequently used together should be copied into one record, including every derived and unrelated field.",
    correction: "Group cohesive facts about one entity, name their meanings and constraints, and derive redundant values rather than storing conflicting copies when possible.",
  },
  "pf.data.set-map": {
    model: "A set represents unique membership, while a map associates unique keys with values; neither structure is chosen merely because it can hold several items.",
    boundary: "Iteration order, hashability, equality, duplicate handling, and lookup complexity vary by implementation, and maps do not permit duplicate keys simultaneously.",
    scenarioA: "A set of completed badge identifiers answers whether a badge is present without storing duplicate completions.",
    scenarioB: "A map from learner id to current streak retrieves the streak associated with one unique learner key.",
    misconception: "Sets and maps are interchangeable because both usually offer fast lookup and use braces in some languages.",
    correction: "Choose a set for membership of unique values and a map when each unique key must retrieve an associated value; state order needs separately.",
  },
  "pf.data.selection": {
    model: "Data-structure choice follows required operations and invariants: order, duplicates, positional access, key lookup, insertion, removal, traversal, and memory constraints.",
    boundary: "Big-O labels alone omit constant costs, scale, mutation patterns, library guarantees, concurrency, persistence, and readability for the actual workload.",
    scenarioA: "A playback queue needs stable order and duplicate songs, so a sequence fits better than a set that removes duplicates.",
    scenarioB: "A permission check needs unique role membership, while a profile lookup needs a map from user id to profile record.",
    misconception: "One structure, such as a list, is always best because it can represent every small dataset somehow.",
    correction: "List the dominant operations and invariants first, compare at least one alternative, and choose the simplest structure whose guarantees match those needs.",
  },
  "pf.tools.files": {
    model: "A path identifies a filesystem location using roots and segments; relative paths resolve from a declared working directory, while extensions are naming conventions rather than guarantees of content.",
    boundary: "Separators, drive roots, case sensitivity, symbolic links, permissions, and reserved names differ across operating systems and filesystems.",
    scenarioA: "From project/src, the relative path ../tests/input.txt moves to project and then enters tests, while an absolute path starts from the system root.",
    scenarioB: "Renaming notes.txt to notes.py changes the extension but does not transform its text into valid Python source.",
    misconception: "A relative path always resolves from the user's home folder and a file extension proves the file's format.",
    correction: "Resolve relative paths from the current working directory, normalize segments carefully, and inspect or validate content instead of trusting an extension alone.",
  },
  "pf.tools.terminal-editor": {
    model: "An editor changes source files, a terminal runs commands in a working directory, and saving the file is a separate action from executing a named tool on it.",
    boundary: "Shell syntax, PATH lookup, quoting, environment variables, permissions, and editor autosave behavior differ, so commands and active files must be verified explicitly.",
    scenarioA: "A learner saves main.py, confirms the terminal is in the project folder, runs python main.py, and distinguishes program output from source text.",
    scenarioB: "A command fails because the terminal remains in the parent folder; printing the working directory reveals the mismatch before any code change.",
    misconception: "Typing code in an editor automatically runs it, and every terminal starts in the folder containing the visible file.",
    correction: "Save intentionally, inspect the working directory and command, run the declared tool, and read its output or diagnostic as a separate workflow step.",
  },
  "pf.tools.errors": {
    model: "Build or syntax failures prevent a valid artifact, runtime failures occur during execution, and logic failures complete but violate the required behavior; the earliest relevant diagnostic guides the next observation.",
    boundary: "One defect can trigger many later diagnostics, exceptions can wrap original causes, and undefined behavior can evade clean classification.",
    scenarioA: "A missing delimiter produces a parser location before execution, so changing the calculation is irrelevant until syntax is repaired.",
    scenarioB: "A program runs and prints 12 instead of required 10, so a state trace and failing example investigate logic rather than compiler configuration.",
    misconception: "Every red message is the root cause, so fixing the last diagnostic first is the fastest strategy.",
    correction: "Classify the phase, start with the earliest actionable cause, reproduce minimally, and confirm the repair removes the original failure without creating another.",
  },
  "pf.tools.debug-test": {
    model: "A disciplined debug loop reproduces a failure, states a hypothesis, isolates a small case, observes relevant state, changes one likely cause, and reruns tests including a regression case.",
    boundary: "Debugger inspection can perturb timing, one passing example does not establish the hypothesis, and changing several causes at once destroys evidence about which change mattered.",
    scenarioA: "An off-by-one list failure is reproduced with a one-element case, the index is observed at the condition, the bound is corrected, and empty and multi-element regressions run.",
    scenarioB: "A total is wrong only after refunds; a focused test isolates one refund and a trace reveals the sign is added instead of subtracted.",
    misconception: "Debugging means making plausible edits until the visible failure disappears, without preserving a failing test.",
    correction: "Use observations to test one hypothesis at a time and keep the smallest exposing case as a regression test after the cause is repaired.",
  },
  "pf.practice.read-code": {
    model: "Reading code begins by naming its contract, tracing inputs and state changes, identifying control paths and calls, and checking edge cases before proposing edits.",
    boundary: "Identifier names and comments can be stale or misleading, and a quick happy-path reading can miss exceptions, mutation, aliasing, or hidden dependencies.",
    scenarioA: "Before changing a discount routine, a learner predicts outputs at zero, the threshold, and above the threshold and then confirms each branch in a trace.",
    scenarioB: "A loop is annotated with its changing variables and termination condition before a new filtering rule is inserted.",
    misconception: "Understanding code means reading each line's syntax; predicting state and behavior is unnecessary until editing begins.",
    correction: "Build and test a behavioral model first, because purpose, data flow, effects, and edge cases determine whether a later edit preserves the contract.",
  },
  "pf.practice.feedback": {
    model: "Useful feedback is converted into a diagnosis, an explained correction, a new exposing test, and an independent retry rather than copied as a replacement answer.",
    boundary: "Feedback can be incomplete or wrong, scores alone do not identify causes, and a corrected near-copy does not prove transfer to a new context.",
    scenarioA: "After an off-by-one answer fails, the learner identifies the invalid last index, corrects the bound, adds empty and one-item tests, and solves a new traversal problem.",
    scenarioB: "A vague comment about clarity is translated into one specific naming or decomposition change and verified against the original behavior.",
    misconception: "Once the correct answer is shown, recognizing it means the underlying skill has been learned.",
    correction: "Explain the failure in your own words, produce evidence that the correction works, and complete a delayed or surface-different attempt without the shown answer.",
  },
  "pf.practice.assistance": {
    model: "Documentation and AI assistance should answer a bounded question, expose assumptions, cite applicable versions, and be verified against the problem, authoritative sources, and executable tests.",
    boundary: "Confident wording is not evidence, generated code can leak secrets or violate constraints, and a correct snippet in one version or context may be wrong in another.",
    scenarioA: "A learner asks for the documented return behavior of one library call, checks official versioned docs, then writes boundary tests before using the suggestion.",
    scenarioB: "An AI-proposed fix is compared with the assignment constraints and rejected because it imports a forbidden library despite passing one example.",
    misconception: "A fluent answer from documentation search or an AI tool can be submitted without verification if it looks conventional.",
    correction: "Retain ownership by narrowing the request, checking source and version, testing normal and boundary behavior, and explaining every submitted decision.",
  },
  "pf.practice.integrity": {
    model: "Academic and professional integrity requires distinguishing allowed collaboration, attributed reference use, licensed reuse, and work represented as one's own under the applicable rules.",
    boundary: "Policies and licenses vary by course and project, common knowledge has limits, and attribution does not automatically grant permission or satisfy an independent-work requirement.",
    scenarioA: "A learner discusses an algorithm idea with a peer, writes an independent solution, and records the collaboration because the course policy allows conceptual discussion with attribution.",
    scenarioB: "Code copied from a repository is not submitted when its license and the assignment's independent-work rule do not permit that reuse.",
    misconception: "Adding a source link makes any copied solution acceptable, regardless of license or assessment rules.",
    correction: "Check both permission and attribution requirements, describe assistance accurately, and never represent another person's or tool's work as independent evidence of mastery.",
  },

  "git.shell.paths": {
    model: "Shell commands resolve relative paths from the current working directory, while absolute paths begin at a filesystem root; dot and dot-dot name current and parent locations.",
    boundary: "Windows and POSIX roots, separators, case rules, quoting, links, and permission behavior differ, so a path valid on one machine may not identify the same location elsewhere.",
    scenarioA: "From repo/src, ../README.md resolves to the README in repo, while ./README.md looks inside src and may not exist.",
    scenarioB: "A directory name containing spaces is passed as one quoted argument instead of being split into several shell words.",
    misconception: "Every relative path starts from the repository root, regardless of the terminal's current working directory.",
    correction: "Inspect the working directory first, resolve each segment from that location, and quote paths as data according to the active shell's rules.",
  },
  "git.shell.inspect": {
    model: "Read-only inspection commands establish location, directory contents, file content, status, and differences before any command changes filesystem or repository state.",
    boundary: "Hidden files, ignored files, permissions, binary content, pager behavior, and large output can make one inspection command incomplete.",
    scenarioA: "Before editing, a learner prints the working directory, lists hidden entries, checks Git status, and opens the exact target file.",
    scenarioB: "After a surprising build failure, file metadata and a diff reveal that the edited file is a similarly named copy outside the repository.",
    misconception: "Inspection is unnecessary because command prompts and editor tabs always identify the active directory and file accurately.",
    correction: "Collect cheap read-only evidence before mutation so later commands operate on the intended path, file, branch, and repository state.",
  },
  "git.shell.create-move": {
    model: "Creating, copying, moving, renaming, and deleting files changes paths and content independently; each operation should name an exact source and destination and be verified afterward.",
    boundary: "Overwrites, recursive operations, links, permissions, case-only renames, and cross-filesystem moves have platform-specific behavior and can cause irreversible loss.",
    scenarioA: "A source file is moved with Git-aware tooling, then status confirms one rename rather than an accidental deletion plus unrelated new file.",
    scenarioB: "A new directory is created before copying a template, and the destination is inspected before any original is removed.",
    misconception: "Move and copy are interchangeable because both make the file appear at the destination.",
    correction: "Copy preserves the source while move changes its location; verify both endpoints and repository status before treating the operation as complete.",
  },
  "git.shell.safety": {
    model: "Safe shell work scopes destructive commands to verified literal paths, previews targets, preserves recoverable copies, and avoids constructing commands from untrusted text.",
    boundary: "Aliases, glob expansion, variable expansion, symlinks, elevated permissions, and different shell parsing can broaden a command beyond what its text appears to target.",
    scenarioA: "Before a recursive cleanup, the learner resolves and prints the intended build directory and removes only that verified path inside the repository.",
    scenarioB: "A script passes a user-supplied filename as a quoted argument rather than concatenating it into an executable shell command.",
    misconception: "A familiar delete command is safe to run immediately if the typed path looks approximately correct.",
    correction: "Verify resolved scope and current state, prefer non-destructive previews and exact-path APIs, and keep a recovery path before destructive execution.",
  },
  "git.model.repository": {
    model: "A Git repository stores versioned objects and references in its metadata while the working tree presents one checked-out snapshot plus local changes.",
    boundary: "Bare repositories have no normal working tree, nested repositories and worktrees alter layout, and untracked files are not yet represented in committed history.",
    scenarioA: "Editing README changes the working tree but does not alter the last commit object until new content is staged and committed.",
    scenarioB: "Deleting the .git metadata leaves ordinary files visible but removes that directory's repository history and references.",
    misconception: "The repository is just the visible project folder, so every file in it is automatically versioned.",
    correction: "Distinguish Git's object/reference database from the working tree and use status to see which visible files are tracked, modified, staged, or untracked.",
  },
  "git.model.index": {
    model: "The index, or staging area, records the exact proposed snapshot for the next commit separately from both the current working tree and the previous commit.",
    boundary: "Partial staging, intent-to-add, conflict stages, file-mode changes, and generated files make the index more than a simple list of filenames.",
    scenarioA: "Only the tested half of a modified file is staged, so the staged diff differs from the remaining working-tree diff.",
    scenarioB: "A file is edited again after staging; the commit would contain the earlier staged version unless the index is updated.",
    misconception: "Staging marks a filename, so later edits to that file automatically become part of the same staged snapshot.",
    correction: "Inspect both staged and unstaged diffs because the index stores content at staging time, and restage only the changes intended for the next commit.",
  },
  "git.model.ignore": {
    model: "Ignore rules suppress untracked-path reporting and accidental addition; they do not remove files that Git already tracks.",
    boundary: "Rule order, negation, directory patterns, global excludes, nested ignore files, and path anchoring affect which untracked paths match.",
    scenarioA: "Adding .env to an ignore file prevents a new local .env from appearing as untracked, but a previously committed .env remains tracked.",
    scenarioB: "A broad build/ rule ignores generated output while a documented negation keeps one required fixture within that tree visible.",
    misconception: "Adding a secret file to .gitignore erases it from existing commits and remote history.",
    correction: "Ignore affects future untracked-path selection only; stop tracking current content separately and rotate or purge exposed secrets using an explicit incident process.",
  },
  "git.model.stage-commit": {
    model: "A commit stores an immutable snapshot reference, parent relationship, author/committer metadata, and message based on the current index, not every working-tree change.",
    boundary: "Amend and history rewriting create new commit objects, timestamps and identities can differ, and committing does not automatically publish to a remote.",
    scenarioA: "A learner stages one bug fix, reviews the staged diff, commits it with a causal message, and leaves an unrelated experiment unstaged.",
    scenarioB: "After committing, status still shows a modified local note because it was never added to the index.",
    misconception: "Commit saves the entire project exactly as currently visible and sends it to GitHub in one operation.",
    correction: "A commit records the staged snapshot locally; inspect the index before committing and treat remote push as a separate authorized action.",
  },
  "git.history.messages": {
    model: "A useful commit message states the change's intent and reason at the granularity of one coherent snapshot, enabling review, search, and later diagnosis.",
    boundary: "Message conventions vary by project, and a perfect message cannot compensate for a mixed, untested, or secret-containing commit.",
    scenarioA: "Fix empty-cart total by handling zero items explains both behavior and cause more clearly than changes or update.",
    scenarioB: "A dependency bump message names the affected package and security or compatibility reason rather than listing regenerated files.",
    misconception: "Commit messages only matter for large teams, so generic labels such as stuff are sufficient for personal work.",
    correction: "Write a concise imperative summary and necessary why context so future you and collaborators can understand the snapshot without reconstructing intent from every line.",
  },
  "git.history.log-show": {
    model: "Log traverses commit history and references, while show inspects one selected object's metadata and patch; filters narrow evidence without changing history.",
    boundary: "Default history can omit unreachable commits, merges have multiple parents, path filtering changes traversal, and abbreviated hashes can become ambiguous.",
    scenarioA: "A learner searches log for changes to parser.ts, selects a full commit identity, and uses show to inspect that commit's exact patch.",
    scenarioB: "A graph view reveals that a merge commit joins two parent lines rather than representing an ordinary single-parent step.",
    misconception: "The newest log entry is always the commit that introduced a particular line or behavior.",
    correction: "Use relevant path, author, text, graph, or date filters and inspect candidate commits directly instead of inferring origin from recency alone.",
  },
  "git.history.diff": {
    model: "A diff compares two explicitly named states, such as working tree to index, index to HEAD, or one commit to another, and reports line-oriented changes rather than intent.",
    boundary: "Renames are inferred, binary changes are limited, generated formatting can obscure logic, and an empty diff can mean the wrong pair of states was compared.",
    scenarioA: "git diff reviews unstaged edits while git diff --staged reviews the snapshot proposed for the next commit.",
    scenarioB: "Comparing a release tag with the current branch isolates all committed changes since that release rather than local uncommitted edits.",
    misconception: "One diff command always shows every change in the repository, including staged, unstaged, and untracked content.",
    correction: "Name or understand both comparison endpoints and inspect untracked status separately so no category of work is silently omitted.",
  },
  "git.history.tags": {
    model: "A tag gives a stable human-readable reference to a specific Git object, commonly a release commit; annotated tags also store message, tagger, and optional signature.",
    boundary: "Tags can be moved or deleted, lightweight and annotated tags differ, and creating a local tag does not automatically publish it to a remote.",
    scenarioA: "An annotated v1.0.0 tag points to the tested release commit and records release context before that tag is pushed explicitly.",
    scenarioB: "A deployment resolves the tag's commit identity rather than assuming a same-named branch or latest main commit.",
    misconception: "A tag is a read-only branch that automatically follows new commits and appears on every remote.",
    correction: "Treat a tag as a named pointer to one chosen object, verify its target, and publish or protect it according to project policy.",
  },
  "git.branches.refs": {
    model: "A branch is a movable reference to a commit, while HEAD identifies the currently checked-out reference or a specific commit in detached state.",
    boundary: "Remote-tracking references are local observations, branch names are not commits, and deleting a name does not immediately delete reachable commit objects.",
    scenarioA: "Committing on feature moves the feature reference to the new commit while main continues to point at its previous commit.",
    scenarioB: "Checking out a release tag detaches HEAD, so a new commit exists without advancing a normal local branch unless one is created.",
    misconception: "A branch contains its own copied files and commits rather than naming one position in a shared commit graph.",
    correction: "Reason from references and commit ancestry: branch names move as commits are created, while snapshots belong to commit objects shared across the graph.",
  },
  "git.branches.workflow": {
    model: "A branch workflow isolates a coherent change, starts from an intentional base, incorporates reviewable commits, and synchronizes with the target branch before integration.",
    boundary: "Long-lived divergence, stacked branches, release branches, and protected targets require project-specific update and integration rules.",
    scenarioA: "A short feature branch begins from current main, contains one tested concern, and opens a review before merging back.",
    scenarioB: "Before new work, the learner verifies the active branch and clean status so changes do not accidentally land on main.",
    misconception: "Creating many branches automatically prevents conflicts and guarantees changes are based on the latest target.",
    correction: "Branches provide named isolation, but developers must choose the base, keep scope coherent, update deliberately, test, and integrate through the agreed process.",
  },
  "git.branches.merge": {
    model: "A merge combines histories by finding ancestry and creating either a fast-forward reference move or a merge result that reconciles both lines of work.",
    boundary: "Merge strategy, rename detection, binary files, generated artifacts, and semantic interactions can produce a textually clean merge that still breaks behavior.",
    scenarioA: "When main has not advanced, merging feature fast-forwards main to the feature commit without creating an extra merge commit.",
    scenarioB: "When both branches advanced, Git performs a three-way merge and tests reveal an API interaction even though no text conflict occurred.",
    misconception: "A merge is successful and correct whenever Git reports no textual conflicts.",
    correction: "After reconciling history, inspect the combined diff and run relevant builds and tests because semantic incompatibilities can remain without conflict markers.",
  },
  "git.branches.conflicts": {
    model: "A conflict records multiple unresolved versions in the index; resolution requires understanding both intents, editing a coherent result, removing markers, testing, and staging the resolved content.",
    boundary: "Choosing ours or theirs can discard valid work, conflicts can involve rename/delete and binary states, and a resolved text can still be semantically wrong.",
    scenarioA: "Two branches change the same validation branch differently, so the resolver reads both commits and writes one rule that preserves required cases from each.",
    scenarioB: "After removing conflict markers, status and staged diff are inspected and the focused test suite runs before the merge is completed.",
    misconception: "Conflict resolution means deleting marker lines and choosing the version that compiles first.",
    correction: "Recover both change intentions, construct and test the correct combined behavior, then stage only after no marker or unresolved index entry remains.",
  },
  "git.remotes.clone": {
    model: "Clone creates a local repository, copies reachable objects and remote configuration, creates remote-tracking references, and checks out an initial working branch.",
    boundary: "Authentication, partial or shallow clone, submodules, large files, default-branch choice, and server permissions can change what is fetched or checked out.",
    scenarioA: "Cloning a public repository creates local origin configuration and an origin/main tracking reference while local changes remain entirely local.",
    scenarioB: "A shallow clone contains limited ancestry, so a history query cannot assume every older commit is available locally.",
    misconception: "Clone creates a live shared folder where local edits immediately alter the remote repository.",
    correction: "A clone is an independent local repository initialized from remote data; later fetch and push operations synchronize selected references explicitly.",
  },
  "git.remotes.fetch": {
    model: "Fetch downloads new reachable objects and updates remote-tracking references without merging them into the current local branch or changing its working tree.",
    boundary: "Refspecs, pruning, shallow boundaries, authentication, force-updated remote branches, and tags affect which references change.",
    scenarioA: "After fetch, origin/main moves to the server's latest commit while local main and the learner's working files stay unchanged.",
    scenarioB: "The learner compares local main with origin/main before deciding whether to merge, rebase, or leave the branch untouched.",
    misconception: "Fetching is the same as pulling and can silently rewrite the current branch's files.",
    correction: "Fetch updates the local view of remote references only; inspect divergence and choose a separate integration operation deliberately.",
  },
  "git.remotes.pull": {
    model: "Pull is a compound operation that first fetches and then integrates an upstream branch by the configured merge or rebase policy.",
    boundary: "Dirty worktrees, divergent history, force-updated upstreams, policy configuration, conflicts, and submodules can make pull unsafe or surprising.",
    scenarioA: "A learner with a clean branch fetches, inspects divergence, and pulls with an explicit rebase policy required by the project.",
    scenarioB: "When local uncommitted edits exist, the learner stops and preserves them rather than using pull as an unexplained synchronization button.",
    misconception: "Pull only downloads remote data and therefore cannot create commits, replay work, or cause conflicts.",
    correction: "Treat pull as fetch plus integration, know the selected strategy, inspect state first, and test the resulting local history and files.",
  },
  "git.remotes.push": {
    model: "Push asks a remote to update selected references with local objects, subject to authentication, fast-forward, protection, and server policy.",
    boundary: "Force options, refspecs, tags, protected branches, hooks, credentials, and concurrent updates can reject or dangerously overwrite remote history.",
    scenarioA: "A feature branch is pushed to a same-named remote branch after tests, then used to open review without updating protected main directly.",
    scenarioB: "A rejected non-fast-forward push triggers fetch and history inspection rather than an immediate force push.",
    misconception: "Push uploads all local branches and files, and force push is the normal fix whenever the server rejects an update.",
    correction: "Verify the source and destination refs, review outgoing commits, respect protection, and use force-with-lease only under an explicit history-rewrite policy.",
  },
  "git.collaboration.issue": {
    model: "A useful issue states the observed need or defect, reproducible context, expected and actual behavior, acceptance criteria, scope, and relevant evidence without embedding secrets.",
    boundary: "Project templates and privacy rules vary, and an issue may describe work without authorizing access, disclosure, or a particular implementation.",
    scenarioA: "A bug issue includes minimal reproduction steps, version, expected total, actual total, and a redacted test case while omitting customer data.",
    scenarioB: "A feature issue defines measurable acceptance criteria and out-of-scope behavior before code or estimates are proposed.",
    misconception: "A short title such as login broken is enough because developers can discover the environment and expected behavior themselves.",
    correction: "Provide concise reproducible evidence and testable acceptance boundaries so another person can confirm and close the work without guessing intent.",
  },
  "git.collaboration.pr": {
    model: "A pull request presents a bounded change for review with linked motivation, implementation summary, risk, tests, screenshots or evidence, and an understandable commit or diff history.",
    boundary: "A pull request is not proof of correctness, approval rules vary, and generated files, migrations, rollout, compatibility, or security may need specialized evidence.",
    scenarioA: "A parser fix PR links the issue, explains the boundary defect, includes the regression test, and identifies no schema or deployment impact.",
    scenarioB: "A UI change includes keyboard and narrow-screen evidence plus a note about deliberately unchanged behavior.",
    misconception: "Opening a pull request is only a request to merge, so description, tests, and scope explanation are optional when the diff exists.",
    correction: "Treat the PR as a review artifact: make intent, boundaries, evidence, and risk legible so reviewers can evaluate more than raw syntax changes.",
  },
  "git.collaboration.review": {
    model: "Code review evaluates correctness, security, maintainability, tests, requirements, and risk; actionable feedback identifies location, consequence, and a verifiable change or question.",
    boundary: "Review cannot prove absence of defects, style preferences should not masquerade as blockers, and approvals depend on reviewer expertise and current diff state.",
    scenarioA: "A reviewer points to an unchecked empty input, explains the resulting crash, and requests a focused boundary test rather than writing vague needs work feedback.",
    scenarioB: "After an update, the reviewer rechecks the changed commit range and verifies the earlier concern rather than assuming it remains fixed.",
    misconception: "Review quality is measured by the number of comments, and personal style differences should block a correct change.",
    correction: "Prioritize evidence-backed defects and risks, label optional suggestions, and verify resolutions against requirements and tests with respectful, specific language.",
  },
  "git.collaboration.integrate": {
    model: "Integration applies the project's approved merge, squash, or rebase policy after required review and checks, then verifies the target branch and cleans up references safely.",
    boundary: "Different strategies preserve different history, branch protection can change, and green checks may be stale relative to the final commit.",
    scenarioA: "A squash policy combines a noisy feature history into one target commit only after current required checks pass on the reviewed head.",
    scenarioB: "After merge, the target branch is updated locally and the deployed or built artifact is verified before the feature branch is removed.",
    misconception: "Any merge button produces equivalent history and a green check from an earlier commit remains valid after new changes.",
    correction: "Use the declared integration strategy, require checks for the exact reviewed revision, inspect the resulting target, and preserve traceability to the request.",
  },
  "git.tools.dependencies": {
    model: "Dependency manifests declare requested packages and constraints, while lockfiles record a resolved graph for reproducible installation in a defined tool and platform context.",
    boundary: "Optional and platform dependencies, registries, transitive updates, install scripts, integrity metadata, and tool versions can still affect reproducibility and security.",
    scenarioA: "A new library is added through the package manager so both manifest intent and lockfile resolution change and are reviewed together.",
    scenarioB: "A lockfile-only security update is inspected for unexpected package or lifecycle-script changes before tests run.",
    misconception: "Editing a manifest version is sufficient, and lockfiles are generated noise that should never be reviewed or committed.",
    correction: "Use the ecosystem tool, review declared and resolved changes, pin the package-manager version where needed, and test the exact lockfile installed in CI.",
  },
  "git.tools.build": {
    model: "A build transforms declared source and assets into validated artifacts through repeatable commands whose inputs, outputs, environment, and failure status are explicit.",
    boundary: "Caches, generated code, timestamps, native tools, network access, environment variables, and undeclared local files can make builds non-reproducible.",
    scenarioA: "A clean build in a fresh workspace produces the same tested bundle from the lockfile rather than relying on a developer's old output directory.",
    scenarioB: "A failing compile exits nonzero and stops packaging instead of emitting a seemingly successful partial artifact.",
    misconception: "If the application runs from the editor, the documented clean build and its artifact are guaranteed to work elsewhere.",
    correction: "Run the declared clean build with pinned dependencies, inspect exit status and artifact, and remove reliance on undeclared machine state.",
  },
  "git.tools.config": {
    model: "Configuration separates environment-specific values and policy from code, with precedence, defaults, validation, and secret handling defined for each source.",
    boundary: "Configuration can be executable or interpolated, environment variables leak in logs or child processes, and local, project, user, and system precedence varies by tool.",
    scenarioA: "A service validates required database host and port at startup while reading the password from a secret channel excluded from Git.",
    scenarioB: "A surprising formatter setting is traced through project and user configuration precedence rather than changed randomly in source.",
    misconception: "All configuration files belong in version control because configuration is not code and cannot contain sensitive data.",
    correction: "Version safe shared defaults and schemas, keep credentials out of the repository, document precedence, and validate effective configuration without printing secrets.",
  },
  "git.tools.artifacts": {
    model: "Build artifacts are generated outputs with traceable source revision, toolchain, dependencies, checksums, and retention rules; they are not automatically source-of-truth files.",
    boundary: "Some generated code or vendored assets may be intentionally versioned, while large, signed, or platform-specific artifacts need dedicated storage and provenance.",
    scenarioA: "A release archive is named with version and commit, hashed, scanned, and stored by CI rather than committed into the source branch.",
    scenarioB: "A generated API client is committed only because project policy requires review and reproducible regeneration from a versioned schema.",
    misconception: "Every generated file should be ignored, or alternatively every build output should be committed so users can find it.",
    correction: "Classify each output by reproducibility and distribution need, document the policy, and preserve provenance without polluting source history unnecessarily.",
  },
  "git.quality.debugger": {
    model: "A debugger pauses controlled execution to inspect frames, variables, and control flow against a stated hypothesis, using breakpoints and stepping as observations rather than random exploration.",
    boundary: "Breakpoints alter timing, optimized code can reorder or remove variables, and debugger state does not replace a reproducible test or explain external-system behavior.",
    scenarioA: "A breakpoint before a failing division confirms the denominator becomes zero only on empty input, supporting one specific guard hypothesis.",
    scenarioB: "Stepping into a helper reveals an argument is already wrong at the call boundary, moving investigation to the caller rather than the helper body.",
    misconception: "The best debugging strategy is to step through every line from program start until something looks suspicious.",
    correction: "Reproduce narrowly, state what observation would support or refute a hypothesis, place targeted breakpoints, and preserve the exposing case as a test.",
  },
  "git.quality.format-lint": {
    model: "A formatter applies mechanical layout rules, while a linter reports configured syntactic, semantic, safety, or maintainability patterns; both must run with pinned project configuration.",
    boundary: "A clean lint result is not proof of correctness, rules can conflict or produce false positives, and automatic fixes can change behavior in some tools.",
    scenarioA: "Formatting changes are separated from a logic fix so reviewers can see behavior clearly while CI enforces the same formatter version.",
    scenarioB: "A linter warns about an unhandled promise; the learner understands the failure path before applying a fix instead of disabling the rule globally.",
    misconception: "Formatter and linter are synonyms, and code that passes both cannot contain bugs or security flaws.",
    correction: "Use formatting for consistent presentation and linting for bounded static checks, review automatic changes, and retain tests and human reasoning for behavior.",
  },
  "git.quality.bisect": {
    model: "Bisect performs a binary search over an ordered commit ancestry using a reliable good/bad test to identify the first commit where behavior changes.",
    boundary: "Flaky tests, merge topology, unbuildable commits, environmental drift, and an incorrect known-good point can produce a misleading culprit.",
    scenarioA: "A deterministic regression script marks release v1 good and current main bad, then classifies midpoint commits until one introducing commit remains.",
    scenarioB: "An untestable midpoint is skipped with a recorded reason rather than guessed good or bad.",
    misconception: "Bisect examines code changes automatically and determines which developer caused a bug without a reproducible test.",
    correction: "Provide trustworthy boundary commits and a deterministic classifier, then inspect and verify the identified commit as evidence rather than blame.",
  },
  "git.quality.hooks": {
    model: "Git hooks run local or server-side programs at lifecycle points to automate checks, but their installation, environment, trust, and bypass policy must be explicit.",
    boundary: "Client hooks are not cloned automatically, can be bypassed, execute with developer privileges, and may behave differently across shells and platforms.",
    scenarioA: "A versioned hook launcher runs fast formatting checks before commit while authoritative CI reruns all required checks independently.",
    scenarioB: "A downloaded repository's hook scripts are reviewed before installation because they can execute arbitrary local commands.",
    misconception: "A pre-commit hook guarantees every commit in the remote passed the check and is safe to trust.",
    correction: "Treat hooks as convenience and defense in depth, distribute them transparently, minimize privilege, and enforce non-bypassable policy on trusted CI or server controls.",
  },
  "git.ci.pipeline": {
    model: "A CI pipeline runs versioned jobs for an exact revision in a controlled environment, preserving logs and artifacts and gating integration on declared required results.",
    boundary: "Secrets, caches, untrusted pull requests, matrix variants, flaky tests, mutable actions, and stale approvals introduce risk even when a pipeline is green.",
    scenarioA: "A pull request runs lint, unit tests, and build against its current commit, and branch protection requires those exact checks before merge.",
    scenarioB: "An untrusted contribution receives no production secret and builds in a restricted job before any privileged deployment stage.",
    misconception: "A green pipeline proves the software is correct and secure for every environment and remains valid after later commits.",
    correction: "Interpret CI as scoped evidence for one revision and declared matrix, protect secrets and dependencies, and rerun required checks whenever the reviewed revision changes.",
  },
  "git.security.secrets": {
    model: "Secrets must enter through approved secret storage, be redacted from output, receive least privilege and expiry, and be rotated immediately when exposed.",
    boundary: "Deleting a file or commit does not remove copies from clones, logs, caches, artifacts, or provider history, and encoded text is not encryption.",
    scenarioA: "A leaked API key is revoked first, impact and logs are reviewed, a replacement is issued with narrower scope, and repository history is remediated separately.",
    scenarioB: "CI exposes a short-lived token only to the deployment job and masks it without echoing commands or uploading its environment as an artifact.",
    misconception: "Moving a committed key into .gitignore or deleting the latest file makes the old credential safe again.",
    correction: "Assume exposed credentials are compromised, revoke and rotate them, investigate use and copies, then clean history and prevention controls without treating cleanup as rotation.",
  },
  "git.recovery.undo": {
    model: "Safe recovery chooses an operation from the state to preserve: restore working changes, unstage the index, revert a published commit, or reset/reflog only with understood history consequences.",
    boundary: "Uncommitted data may be unrecoverable, reflog is local and expires, reset modes differ, and rewriting shared history can discard collaborators' work.",
    scenarioA: "A bad commit already on main is undone with a new revert commit, preserving public history and reviewability.",
    scenarioB: "A staged file is unstaged without discarding its working-tree edit because the learner distinguishes index recovery from content deletion.",
    misconception: "Git undo is one universal command, and hard reset is the fastest safe way to reverse any mistake.",
    correction: "Inspect working tree, index, commits, remotes, and reflog first; state what must survive, then choose the least destructive operation that changes only the intended layer.",
  },
  "git.project.collaboration": {
    model: "A collaborative project defines contribution setup, issue and branch flow, review ownership, required checks, release practice, communication norms, and a safe escalation path.",
    boundary: "One workflow does not fit every team, documentation can drift, and social permission, security response, licensing, and technical enforcement are separate concerns.",
    scenarioA: "A new contributor follows documented setup, claims a scoped issue, opens a focused branch and PR, responds to review, and sees the exact checks required for merge.",
    scenarioB: "A security-sensitive report uses a private disclosure channel rather than a public issue while ordinary defects remain transparent.",
    misconception: "Installing Git and granting repository access is enough to make collaboration predictable and safe.",
    correction: "Make responsibilities, lifecycle, evidence, permissions, communication, and exceptions explicit, then test the contributor path and update it when practice changes.",
  }
} as const satisfies Readonly<Record<string, TrancheTeachingSeed>>;
