import type { TrancheTeachingSeed } from "./foundations-git-tranche";

export interface JavaPythonTeachingSeed extends TrancheTeachingSeed {
  /** Exact source-aligned phrase used by the deterministic fill-gap item. */
  readonly checkpoint: string;
}

/**
 * Topic-specific teaching claims for the Java SE 21 and Python 3.14 tranches.
 * The generator expands structure only; these models, boundaries, examples,
 * misconceptions, corrections, and checkpoints are deliberately authored per
 * atomic skill and remain AI-assisted drafts pending independent human review.
 */
export const JAVA_PYTHON_TRANCHE_SEEDS = {
  "java.toolchain.platform": {
    model: "Java source is checked and translated by JDK tools into class-file bytecode, while a JVM loads, verifies, links, and executes that bytecode with runtime services.",
    boundary: "The language, JDK toolchain, JVM specification, and a concrete runtime implementation are related but distinct; ahead-of-time or just-in-time compilation does not erase those boundaries.",
    scenarioA: "The learner traces Main.java through javac into Main.class and then explains why java launches a JVM rather than interpreting the source file as ordinary text.",
    scenarioB: "A class file compiled for a newer release is rejected by an older runtime even though both machines have a command named java.",
    misconception: "The JDK, Java language, bytecode, and JVM are four names for the same component and always have the same version behavior.",
    correction: "Treat language rules, JDK tools, class-file bytecode, and the JVM as separate layers with explicit compatibility; javac produces class-file bytecode for a declared release.",
    checkpoint: "class-file bytecode",
  },
  "java.toolchain.first-program": {
    model: "A conventional Java application places a correctly named class in a source file, declares a supported static main entry point, compiles it, and launches the resulting class by binary name.",
    boundary: "Source-file launch modes and newer compact entry forms exist, but a beginner must still understand class names, file paths, compilation output, class paths, and process exit behavior.",
    scenarioA: "Main.java declares public class Main with public static void main(String[] args), prints one line, compiles with javac, and runs with java Main.",
    scenarioB: "The compiler rejects a public class named App stored in Main.java, so the learner repairs the file/class contract instead of changing the runtime command randomly.",
    misconception: "Java executes any method named main regardless of its declaring class, modifiers, parameter type, or how the class is launched.",
    correction: "For the conventional entry contract, declare public static void main(String[] args) and launch the containing class by its binary name.",
    checkpoint: "public static void main",
  },
  "java.toolchain.jshell": {
    model: "JShell evaluates snippets in a persistent interactive state that is useful for small API and expression experiments, while saved source remains the reproducible artifact for multi-file programs.",
    boundary: "Snippet declaration order, imports, scratch state, startup configuration, and JShell conveniences can differ from a clean compiled application.",
    scenarioA: "The learner evaluates Math.floorDiv(-7, 3) in JShell, records the result, then writes the verified call into a small source file and test.",
    scenarioB: "A snippet works only because an earlier session imported a package, so a clean reset exposes the missing dependency before the idea moves into source code.",
    misconception: "If an expression succeeds once in a long-running JShell session, the same text is automatically a complete reproducible Java program.",
    correction: "Use JShell for a bounded experiment, then transfer the finding into saved source with explicit imports, declarations, inputs, and a repeatable check.",
    checkpoint: "bounded experiment",
  },
  "java.toolchain.diagnostics": {
    model: "Compile diagnostics describe source or type failures before execution, uncaught exceptions report runtime failure with a causal stack, and logic defects require contract-based observation despite successful execution.",
    boundary: "One syntax or type mistake can cascade into later diagnostics, stack traces show call locations rather than an automatic root-cause verdict, and clean output is not proof of correctness.",
    scenarioA: "A type mismatch is repaired from the first relevant javac diagnostic, while a later NullPointerException is traced from the exception type through the first application frame.",
    scenarioB: "A program compiles and exits normally but returns an off-by-one result, so a boundary assertion—not the compiler—reveals the logic defect.",
    misconception: "Every Java defect becomes either a compiler error or a stack trace, so a run without either must be correct.",
    correction: "Classify compile-time, exceptional runtime, and logic failures separately; start with the first causal diagnostic or relevant application stack frame and verify the repaired contract.",
    checkpoint: "first causal diagnostic",
  },
  "java.fundamentals.primitives": {
    model: "Java primitive variables hold values from fixed language-defined types, local variables require definite assignment, fields receive defaults, and final prevents reassignment after initialization.",
    boundary: "Integer ranges are fixed but arithmetic can overflow, floating values approximate many decimals, char is a UTF-16 code unit, and var infers only a local static type from an initializer.",
    scenarioA: "A measurement uses double, an exact count uses int after a range check, and a local final conversion factor documents that the binding will not be reassigned.",
    scenarioB: "A supplementary Unicode symbol occupies two char values, so code-point-aware APIs are used instead of assuming one char always means one visible character.",
    misconception: "All numeric primitives expand automatically to preserve mathematical results, and local primitives silently start at zero.",
    correction: "Choose a primitive by its specified range and precision, initialize every local before use, and check overflow or precision when the domain requires it.",
    checkpoint: "initialize every local",
  },
  "java.fundamentals.expressions": {
    model: "Java expressions follow operator grouping, short-circuit rules, numeric promotion, conversion, and evaluation order; assignment converts only after the right-hand expression is evaluated.",
    boundary: "Integer division truncates, narrowing needs an explicit cast but can lose data, overflow wraps for integer arithmetic, and && or || skip a right operand conditionally.",
    scenarioA: "The learner predicts that 5 / 2 is 2 before assignment to a double and changes one operand to double when 2.5 is the required result.",
    scenarioB: "A bounds guard uses index >= 0 && index < values.length so the array access is evaluated only after both safety checks succeed.",
    misconception: "The destination variable type controls every intermediate operation, and an explicit cast makes any narrowing conversion safe.",
    correction: "Trace operand promotion and each intermediate operation before the assignment conversion; a cast requests narrowing but does not prove the value fits.",
    checkpoint: "operand promotion",
  },
  "java.fundamentals.selection": {
    model: "Java if statements and switch statements or expressions choose one documented path from complete conditions, with case coverage, fall-through, yields, and null behavior made explicit.",
    boundary: "Classic switch statements can fall through, switch expressions must produce a value, enum/string/null handling differs by construct and version, and boundary predicates can leave gaps.",
    scenarioA: "A score classifier tests the exact lower and upper boundaries for each band and uses an else branch for invalid input.",
    scenarioB: "A switch expression over an enum returns one label per constant and uses a deliberate default only when forward compatibility is more important than exhaustive compiler checking.",
    misconception: "Every Java switch case stops automatically and default always makes a decision complete and correct.",
    correction: "Use arrow cases or explicit control transfer to prevent accidental fall-through, and test every boundary rather than treating default as proof of complete selection.",
    checkpoint: "accidental fall-through",
  },
  "java.fundamentals.iteration": {
    model: "Java while, do-while, counted for, and enhanced-for loops repeat a body while preserving a progress argument, termination condition, and valid traversal state.",
    boundary: "Enhanced-for does not expose a writable index, mutation can invalidate iteration, off-by-one bounds are common, and sentinel loops must handle missing or malformed termination input.",
    scenarioA: "A counted loop visits indices 0 through length - 1, maintains a running total, and is tested for empty, one-element, and many-element arrays.",
    scenarioB: "A sentinel loop reads until a quit token or end of input and updates input on every path so malformed data cannot create an infinite loop.",
    misconception: "Changing a local element variable inside an enhanced-for loop replaces the corresponding array or collection element.",
    correction: "Select a loop whose state matches the job, prove progress toward termination, and use an index, iterator, or collection operation when the underlying structure must change.",
    checkpoint: "progress toward termination",
  },
  "java.methods.contracts": {
    model: "A Java method defines a typed call contract, receives copies of argument values, returns a declared value or completes void, and should make observable side effects explicit.",
    boundary: "A copied reference still refers to the same object, reassignment of a parameter is local, mutable arguments can be changed through aliases, and exceptions are part of failure behavior.",
    scenarioA: "A static clamp method documents its inclusive bounds, returns a value for normal and boundary cases, and has no hidden mutation.",
    scenarioB: "A method reassigns a List parameter without changing the caller's variable, but adding through that copied reference changes the shared list object.",
    misconception: "Java passes objects by reference, so assigning a new object to a parameter also changes the caller's variable.",
    correction: "Java is pass-by-value: a reference value is copied for an object argument, so parameter reassignment stays local while mutation through the shared reference remains observable.",
    checkpoint: "pass-by-value",
  },
  "java.methods.overload-scope": {
    model: "Overload resolution selects an applicable declaration from compile-time argument types, while lexical scope determines which local, parameter, field, or type name a use denotes.",
    boundary: "Return type alone cannot distinguish overloads, null can make unrelated reference overloads ambiguous, boxing and varargs affect applicability, and shadowing can hide fields.",
    scenarioA: "Calls to format(int) and format(double) select different overloads from argument types, while this.label distinguishes a field from a constructor parameter.",
    scenarioB: "Calling choose(null) is ambiguous between String and StringBuilder overloads, so the API is redesigned rather than relying on a surprising cast.",
    misconception: "Java chooses an overload from the runtime class of each argument and can use the expected return type to break every tie.",
    correction: "Resolve overloads from compile-time argument types and applicable signatures; use distinct contracts and explicit qualification to avoid ambiguity and accidental shadowing.",
    checkpoint: "compile-time argument types",
  },
  "java.data.arrays": {
    model: "A Java array is a fixed-length object with zero-based indexed elements, a runtime component type, and independently allocated rows for multidimensional array structures.",
    boundary: "Length cannot change, reference arrays start with null elements, covariance can fail at runtime, ragged rows have different lengths, and every access must satisfy its current row bound.",
    scenarioA: "A sum routine handles an empty int array and traverses indices strictly below values.length without reading one element past the end.",
    scenarioB: "A ragged int[][] traversal checks matrix[row].length for each row rather than assuming a rectangle from matrix.length.",
    misconception: "A two-dimensional Java array is one rectangular block, and every row always has the same length as the outer array.",
    correction: "Treat a multidimensional array as an array of row references, allocate and bound-check each row independently, and never infer column count from the outer length.",
    checkpoint: "array of row references",
  },
  "java.data.strings": {
    model: "Java String values are immutable sequences of UTF-16 code units; content operations return new values, StringBuilder supports repeated construction, and equals compares content.",
    boundary: "Reference identity differs from content equality, code units differ from Unicode code points, locale affects some transformations, and repeated concatenation in a loop can allocate excessively.",
    scenarioA: "A parser uses equals for tokens, strip for surrounding whitespace, and a StringBuilder to assemble an unknown number of output fragments.",
    scenarioB: "A display-length check counts code points rather than char units so a supplementary symbol is not treated as two user characters.",
    misconception: "The == operator compares String text, and one char always represents one complete Unicode character.",
    correction: "Use equals for String content and code-point-aware operations when Unicode characters matter; reserve == for reference identity checks.",
    checkpoint: "equals for String content",
  },
  "java.objects.class": {
    model: "A Java class combines private representation with constructors and cohesive methods that preserve invariants and expose the smallest useful public interface.",
    boundary: "Getters can leak mutable state, public fields bypass validation, static state is shared across instances, and encapsulation is about enforceable contracts rather than accessor count.",
    scenarioA: "A Counter keeps its value private, rejects a negative starting value, and exposes increment and value methods without returning mutable internals.",
    scenarioB: "A class returns List.copyOf for a snapshot instead of returning the owned mutable list directly to callers.",
    misconception: "A class is encapsulated as long as every field has a public getter and setter.",
    correction: "Keep representation private and expose behavior that preserves invariants; do not publish mutation merely to mirror each field.",
    checkpoint: "preserves invariants",
  },
  "java.objects.constructors": {
    model: "A constructor establishes a valid new object by initializing required state, validating arguments, and delegating to another constructor or superclass before ordinary instance use.",
    boundary: "Constructors are not inherited or dynamically dispatched, this(...) or super(...) ordering is constrained, partially initialized this can escape, and records have their own constructor forms.",
    scenarioA: "A two-argument constructor validates normalized bounds, while a convenience constructor delegates with this(...) so the invariant has one implementation.",
    scenarioB: "A constructor rejects null before assigning the field and never registers this with another component until all invariant checks have passed.",
    misconception: "Java supplies a no-argument constructor even after any constructor is declared, and validation can be postponed safely until the first method call.",
    correction: "Declare every required construction path explicitly and establish the complete invariant before the new reference becomes observable.",
    checkpoint: "complete invariant",
  },
  "java.objects.identity": {
    model: "Java reference equality tests whether references denote the same object, equals defines value equality, and equal objects must produce equal hash codes for hashed collections.",
    boundary: "null needs safe handling, mutable equality fields break hashed lookup, inheritance can threaten symmetry, arrays use identity equality by default, and records derive component-based behavior.",
    scenarioA: "Two separately constructed Money values compare equal through equals and produce the same hash code, so a HashSet stores one logical value.",
    scenarioB: "A key's amount is not mutated after insertion into a HashMap because changing equality/hash state can make the entry unreachable by lookup.",
    misconception: "Overriding equals is enough; hashCode may remain inherited because maps compare keys with equals eventually.",
    correction: "Implement equals and hashCode as one stable contract: equal objects must have equal hash codes, and fields used by the contract should not change while hashed.",
    checkpoint: "equal hash codes",
  },
  "java.objects.records": {
    model: "A Java record declares a transparent nominal carrier whose components define generated accessors, construction, equality, hashing, and representation, while validation can live in a compact constructor.",
    boundary: "A record is shallowly immutable, component references may denote mutable objects, records cannot extend another class, and hidden mutable representation or identity-rich lifecycle may call for a class.",
    scenarioA: "A Point record validates finite coordinates and relies on generated component accessors and value equality.",
    scenarioB: "A domain aggregate with hidden cache and state transitions remains a class because transparent component state is not its intended public contract.",
    misconception: "Record components and every object reachable from them become deeply immutable automatically.",
    correction: "Use a record for transparent shallowly immutable data and defensively copy mutable components when deep isolation is part of the contract.",
    checkpoint: "shallowly immutable",
  },
  "java.abstraction.interfaces": {
    model: "A Java interface defines a focused behavioral contract that unrelated classes can implement and clients can depend on without knowing concrete representation.",
    boundary: "Default methods can create conflicts, interface constants are public static final, contracts include semantics beyond method signatures, and a broad interface can still couple clients tightly.",
    scenarioA: "FileNotifier and MemoryNotifier implement one Notifier interface, letting a service test against the memory implementation without branching on concrete types.",
    scenarioB: "A default method collision from two parent interfaces is resolved explicitly in the implementing class rather than relying on declaration order.",
    misconception: "Any classes with matching method names already satisfy a Java interface without declaring implements or honoring semantic behavior.",
    correction: "Declare implements and satisfy both the interface signatures and documented behavioral contract; clients should depend on the smallest coherent interface.",
    checkpoint: "behavioral contract",
  },
  "java.abstraction.inheritance": {
    model: "Class inheritance reuses and specializes behavior only when every subtype can honor the base contract, with superclass construction and protected/public surface controlled deliberately.",
    boundary: "Private representation is not inherited as accessible state, constructors chain, final restricts extension or override, and field hiding does not provide polymorphic state.",
    scenarioA: "Circle extends Shape because every Circle supports the complete Shape area contract and initializes required Shape state through super(...).",
    scenarioB: "A read-only collection subtype that throws from an inherited mutator violates substitution, so the design uses a narrower interface or composition.",
    misconception: "Inheritance is appropriate whenever two classes share fields or helper code, even if the subtype rejects base operations.",
    correction: "Use inheritance only for a valid substitution relationship; otherwise extract a collaborator or shared helper and compose it.",
    checkpoint: "substitution relationship",
  },
  "java.abstraction.dispatch": {
    model: "An overridden instance method is selected at runtime from the receiver object's class, while overload resolution, static methods, private methods, and fields follow different compile-time rules.",
    boundary: "A signature mismatch creates an overload instead of an override, covariant returns are allowed, constructors are not dispatched, and calling overridable methods during construction can observe incomplete state.",
    scenarioA: "A Shape reference holding a Circle invokes Circle.area at runtime, and @Override lets the compiler verify the intended signature.",
    scenarioB: "A static method with the same signature is hidden rather than overridden, so the reference's compile-time type determines the selected declaration.",
    misconception: "Every same-named member uses dynamic dispatch, including fields, static methods, overloads, and constructor calls.",
    correction: "Dynamic dispatch applies to overridden instance methods on the runtime receiver; use @Override and distinguish it from overload selection and member hiding.",
    checkpoint: "overridden instance methods",
  },
  "java.abstraction.composition": {
    model: "Composition gives an object owned or injected collaborators and delegates focused work, allowing reuse without claiming a subtype relationship.",
    boundary: "Composition still needs clear ownership and lifecycle, excessive forwarding can obscure an interface, circular dependencies create coupling, and shared mutable collaborators need coordination.",
    scenarioA: "A ReportService receives a Formatter interface and delegates formatting, so output policy changes independently of report identity.",
    scenarioB: "A Stack wraps an ArrayDeque instead of extending it, preventing callers from using queue operations that violate the stack contract.",
    misconception: "Composition means copying another class's methods into a wrapper and exposing all of them unchanged.",
    correction: "Compose a collaborator behind a purpose-built contract and delegate only behavior that preserves the owning object's invariants.",
    checkpoint: "purpose-built contract",
  },
  "java.generics.types": {
    model: "Java generic types and methods introduce compile-time type parameters so one implementation can preserve relationships among input, stored, and returned types without raw casts.",
    boundary: "Type erasure restricts runtime type tests and generic array creation, primitives need wrappers, static members cannot use a class type parameter directly, and raw types discard checks.",
    scenarioA: "Box<T> stores and returns T, while a static <T> T first(List<T>) method preserves the list element type at each call.",
    scenarioB: "A raw List accepts a String into a collection expected to hold Integer, moving the failure to a later compiler-inserted cast.",
    misconception: "Generic type arguments are fully reified at runtime, so new T() and new T[10] are always available.",
    correction: "Use type parameters for compile-time relationships and account for type erasure; avoid raw types and require factories or reifiable representations when runtime construction is needed.",
    checkpoint: "type erasure",
  },
  "java.generics.bounds": {
    model: "Bounds and wildcards express which types an API accepts: extends supports safe production, super supports safe consumption, and a named type parameter relates multiple positions.",
    boundary: "Generic types are invariant, wildcard capture limits writing, null remains writable to many producer views, and PECS is guidance rather than a substitute for the exact contract.",
    scenarioA: "A sum method accepts List<? extends Number> because it reads Numbers without inserting values into the caller's collection.",
    scenarioB: "A copy method writes Integer values into List<? super Integer> and uses a named T only when source and destination element relationships must be shared.",
    misconception: "Because Integer extends Number, List<Integer> is automatically a subtype of List<Number>.",
    correction: "Java generics are invariant; use ? extends for a producer, ? super for a consumer, or a named type parameter when positions must share one type.",
    checkpoint: "generics are invariant",
  },
  "java.collections.core": {
    model: "Java collection interfaces encode different contracts: List preserves positional sequence, Set uniqueness, Map key-value association, and Queue ordered removal policy; implementations add performance and ordering traits.",
    boundary: "Hash iteration order is not a sorting promise, equality/hashing govern uniqueness and keys, null policies vary, mutability may be restricted, and big-O guarantees depend on implementation and workload.",
    scenarioA: "A word counter uses Map<String,Integer>, while a unique insertion-ordered report uses LinkedHashSet rather than a List plus repeated scans.",
    scenarioB: "A priority queue retrieves the least element by its comparator but does not expose the entire collection in sorted iteration order.",
    misconception: "ArrayList, HashSet, HashMap, and PriorityQueue differ only in method names and can be swapped without changing semantics.",
    correction: "Choose the interface contract first—order, duplicates, lookup, or removal policy—then select an implementation whose guarantees and cost fit the operations.",
    checkpoint: "interface contract first",
  },
  "java.collections.iteration": {
    model: "Collection traversal must follow the iterator and ownership contract: use an iterator's remove when supported, bulk operations, or a separate result instead of structurally mutating behind an active traversal.",
    boundary: "Fail-fast behavior is best-effort rather than synchronization, unmodifiable views can reflect backing changes, immutable copies detach differently, and concurrent collections define separate consistency rules.",
    scenarioA: "An Iterator removes expired entries through iterator.remove while visiting, avoiding a structural change through the collection itself.",
    scenarioB: "List.copyOf creates an unmodifiable snapshot, while Collections.unmodifiableList creates a view whose contents can still change through the backing list.",
    misconception: "Removing directly from an ArrayList inside an enhanced-for loop is safe whenever the removed element is the current one.",
    correction: "Mutate through the traversal mechanism or after traversal, and distinguish an unmodifiable view from an immutable detached copy.",
    checkpoint: "unmodifiable view",
  },
  "java.errors.exceptions": {
    model: "Java exceptions propagate up call frames until a compatible handler is reached; responsible boundaries catch only failures they can translate, recover from, or enrich without losing the cause.",
    boundary: "finally and try-with-resources affect cleanup, a catch order must place specific types first, suppressed exceptions can accompany resource failure, and broad catches can hide programming defects.",
    scenarioA: "A repository method lets an IOException propagate, while a service wraps it in a domain exception with the original cause and useful operation context.",
    scenarioB: "A parser catches NumberFormatException at the input boundary, reports the invalid field, and does not catch unrelated RuntimeException values as ordinary input failure.",
    misconception: "Catching Exception at every method makes a program robust because no failure can escape.",
    correction: "Catch an exception only at a responsible boundary, preserve its cause and context, and let unhandled failures propagate to a policy that can act.",
    checkpoint: "responsible boundary",
  },
  "java.errors.checked": {
    model: "Checked exceptions make selected recoverable conditions part of a method's compile-time contract, while unchecked exceptions commonly report programming, invariant, or caller-contract failures.",
    boundary: "The checked/unchecked choice is an API design decision rather than severity, wrapping everything loses useful distinctions, and exceptions should not encode expected branch flow.",
    scenarioA: "A file-loading API declares IOException because callers can choose retry, alternate input, or escalation, while an invalid negative argument throws IllegalArgumentException.",
    scenarioB: "A domain parse method returns an explicit result for common absence but throws a named exception when malformed input prevents a promised conversion.",
    misconception: "Checked means serious and unchecked means harmless, so every important failure should extend Exception directly.",
    correction: "Choose checked or unchecked from caller recovery and contract needs, not severity; document the failure policy and avoid exceptions for routine alternatives.",
    checkpoint: "caller recovery",
  },
  "java.io.files": {
    model: "Modern Java file code uses Path and Files with an explicit charset, bounded data handling, and deliberate policies for absence, replacement, partial writes, and path resolution.",
    boundary: "The working directory changes relative paths, text line endings vary, a write can fail partway, symbolic links and permissions matter, and Files convenience methods may load an entire file.",
    scenarioA: "A settings reader resolves a Path from configuration, reads UTF-8 text, validates every field, and distinguishes a missing file from malformed content.",
    scenarioB: "A save operation writes a sibling temporary file and then moves it according to a documented replacement policy instead of assuming one write is crash-atomic.",
    misconception: "A relative filename always refers to the source-file directory, and Java text methods automatically choose the intended encoding.",
    correction: "Resolve paths from an explicit base and specify the charset and replacement/failure policy; do not infer location from the source tree.",
    checkpoint: "explicit base",
  },
  "java.io.resources": {
    model: "Try-with-resources closes each declared AutoCloseable in reverse order even when the body fails, and explicit interoperable data formats are safer boundaries than native object deserialization.",
    boundary: "Close itself can fail and become suppressed, ownership decides who closes a resource, some wrappers cascade closure, and untrusted serialized objects can execute dangerous construction paths.",
    scenarioA: "A BufferedReader and underlying stream are declared in try-with-resources so cleanup occurs on normal return and on parsing failure.",
    scenarioB: "The application stores validated JSON fields rather than deserializing an arbitrary ObjectInputStream from an uploaded file.",
    misconception: "Garbage collection promptly closes files and sockets, so explicit resource management only improves style.",
    correction: "Use try-with-resources for owned closeable resources and inspect primary plus suppressed failures; garbage collection is not a cleanup schedule.",
    checkpoint: "try-with-resources",
  },
  "java.functional.lambdas": {
    model: "A lambda supplies behavior for a functional interface, receives target typing from context, and may capture only final or effectively final local bindings.",
    boundary: "Captured object state can still mutate, this refers to the enclosing instance, overloads can make target typing ambiguous, and side effects complicate reuse or parallel execution.",
    scenarioA: "A Comparator<String> lambda compares length then text, and a method reference replaces it only when the same contract remains clear.",
    scenarioB: "A lambda captures an effectively final threshold but accumulates results through an explicit collector instead of mutating an external list.",
    misconception: "Effectively final capture makes every referenced object immutable and gives each lambda a private copy of its state.",
    correction: "Capture copies of local binding values under effectively final rules; referenced mutable objects remain shared, so make side effects explicit or avoid them.",
    checkpoint: "effectively final",
  },
  "java.functional.streams": {
    model: "A Java stream pipeline has a source, lazy intermediate transformations, and one terminal operation; it describes a traversal and cannot be reused after consumption.",
    boundary: "Streams are not storage, infinite sources need bounded terminals, encounter order depends on source and operations, side effects can violate assumptions, and parallel execution is not automatically faster.",
    scenarioA: "A finite list stream filters valid readings, maps units, and collects a new list without mutating the source collection.",
    scenarioB: "A second terminal operation on the same stream is replaced by creating a new stream from the reusable collection source.",
    misconception: "Intermediate operations run immediately and a Stream can be traversed repeatedly like a List.",
    correction: "Intermediate stream operations are lazy until a terminal operation, and each stream traversal is single-use; recreate it from the source for another pass.",
    checkpoint: "single-use",
  },
  "java.functional.collectors": {
    model: "Reduction combines values with an identity and associative accumulator, while collectors manage mutable result containers through supplier, accumulator, combiner, and finisher contracts.",
    boundary: "A non-associative operation can change under regrouping, an incorrect identity corrupts empty or parallel results, duplicate map keys need a merge policy, and mutable reduction must not share unsafe containers.",
    scenarioA: "Integer values reduce with identity 0 and Integer::sum, producing 0 for an empty stream and the same result under valid regrouping.",
    scenarioB: "toMap receives an explicit merge function when two records can share a key, instead of failing unpredictably on production data.",
    misconception: "Any binary operation works in reduce because streams always combine values from left to right exactly once.",
    correction: "Use an associative operation with a true identity for reduction, and choose a collector whose combination and duplicate-key behavior matches the result contract.",
    checkpoint: "associative operation",
  },
  "java.functional.optional": {
    model: "Optional represents possible absence in a return contract and supports explicit transformation or fallback without using a magic sentinel value.",
    boundary: "Optional is not a universal field/parameter replacement, get can throw, orElse evaluates its fallback eagerly, null inside Optional is prohibited, and absence may need a richer error result.",
    scenarioA: "A lookup returns Optional<User>; the caller maps the name or uses orElseGet for an expensive fallback without calling get blindly.",
    scenarioB: "A required constructor parameter remains a validated User rather than Optional<User>, keeping invalid object state unrepresentable.",
    misconception: "Wrapping every nullable field and parameter in Optional automatically removes null problems and is always the preferred API.",
    correction: "Use Optional primarily for an explicit possibly-absent return, consume it with mapping or deliberate fallback, and keep required state required.",
    checkpoint: "possibly-absent return",
  },
  "java.packages.access": {
    model: "Java packages provide names and an access boundary, while public, protected, package-private, and private control which clients may depend on each type or member.",
    boundary: "Packages are not a security sandbox, protected includes package and subtype rules, split packages/modules complicate deployment, and public API compatibility persists beyond source organization.",
    scenarioA: "Implementation classes remain package-private behind one public service interface, reducing the surface callers can couple to.",
    scenarioB: "A protected field is replaced with a protected method or narrower collaborator because direct mutable representation would spread subclass coupling.",
    misconception: "Package-private members are private to one source file, and protected means accessible only by subclasses everywhere.",
    correction: "Package-private access is shared across the package; protected combines package access with constrained subtype access, so expose the minimum stable surface.",
    checkpoint: "minimum stable surface",
  },
  "java.build.maven": {
    model: "A Maven project declares coordinates, conventional source/test layout, dependencies, plugins, and lifecycle phases so a clean environment can reproduce test and package outputs.",
    boundary: "Dependency ranges, unpinned plugins, profiles, repositories, generated sources, local caches, and environment-sensitive tests can still break reproducibility.",
    scenarioA: "mvn verify compiles main and test sources, runs deterministic tests, and produces a versioned artifact from the committed pom.xml.",
    scenarioB: "A build succeeds locally only because an undeclared jar exists in the developer cache, so the dependency is declared and CI verifies from a clean cache.",
    misconception: "If mvn package succeeds once, the pom fully captures the build and the same artifact is guaranteed everywhere.",
    correction: "Treat the POM and locked build policy as an executable contract, pin relevant plugin and dependency behavior, and verify from a clean environment.",
    checkpoint: "executable contract",
  },
  "java.testing.junit": {
    model: "JUnit tests arrange isolated state, perform one observable behavior, and assert normal, boundary, and failure contracts with deterministic fixtures and readable parameterization.",
    boundary: "Test order is not a state-sharing mechanism, sleeps and real external systems create flakiness, mocks can overfit implementation, and line coverage does not prove assertions or edge cases.",
    scenarioA: "A parameterized test covers empty, singleton, normal, and boundary inputs, while assertThrows checks the exact invalid-input contract.",
    scenarioB: "A repository dependency is replaced at its external boundary, but the test asserts service output rather than private helper call order.",
    misconception: "A green test with high line coverage proves the implementation is correct and makes boundary analysis unnecessary.",
    correction: "Derive JUnit cases and assertions from the public contract, isolate each fixture, and cover normal, boundary, and failure behavior deterministically.",
    checkpoint: "public contract",
  },
  "java.quality.debug": {
    model: "Java debugging combines a reproducible failing case, breakpoints and state inspection, stack-aware hypotheses, structured diagnostics, and a regression test that proves the repair.",
    boundary: "A debugger can change timing, logs can leak secrets or become user-facing control flow, optimized/runtime internals may differ, and the first visible bad value can have an earlier cause.",
    scenarioA: "A conditional breakpoint stops at the first invalid balance, the learner traces its assignment backward, fixes the invariant, and adds a boundary regression test.",
    scenarioB: "Structured logging records an operation id and safe status without printing tokens, passwords, full personal data, or replacing exception propagation.",
    misconception: "Adding print statements until the symptom disappears is sufficient debugging evidence and production logging may include any value useful to a developer.",
    correction: "Debug from a reproducible failure and explicit hypothesis, inspect the causal state, protect sensitive data, and preserve the fix with an automated regression test.",
    checkpoint: "reproducible failure",
  },
  "java.runtime.memory": {
    model: "Java objects remain reachable through roots and reference chains; garbage collection may reclaim unreachable storage later, while aliases and long-lived references can retain objects unintentionally.",
    boundary: "Collection timing is unspecified, finalization is not reliable cleanup, a reachable object can still be a logical leak, weak reference types have special semantics, and native resources need explicit closure.",
    scenarioA: "A static cache retains every request object through a map, so bounded eviction removes the unwanted root path rather than forcing a collection.",
    scenarioB: "Two local variables alias one mutable list; changing through either reference affects the same heap object even though both variables are later reassigned independently.",
    misconception: "Java cannot leak memory because garbage collection frees every object that the application no longer intends to use.",
    correction: "Garbage collection reclaims only unreachable objects on its own schedule; diagnose logical retention by tracing reachability from roots and release non-memory resources explicitly.",
    checkpoint: "unreachable objects",
  },
  "java.concurrency.tasks": {
    model: "Java tasks describe units of work, while executors own scheduling, worker resources, result futures, cancellation, and an explicit shutdown lifecycle.",
    boundary: "Submitting does not guarantee immediate start or success, Future.get can block or wrap failure, cancellation is cooperative, unbounded queues can exhaust memory, and executor threads keep a process alive.",
    scenarioA: "A fixed executor runs three independent Callable tasks, collects each Future result, handles failure, and shuts down in a finally path.",
    scenarioB: "A timeout cancels remaining work and awaits termination instead of abandoning live executor threads after the first failure.",
    misconception: "ExecutorService automatically shuts down when submitted tasks finish, and Future.get always returns a value promptly.",
    correction: "Own the executor lifecycle explicitly: bound work and waiting, inspect task failure, request cancellation when needed, and shut down or close the executor.",
    checkpoint: "executor lifecycle",
  },
  "java.concurrency.shared-state": {
    model: "A Java data race occurs when threads access shared mutable state without the required ordering; compound actions need one synchronization or atomicity strategy that preserves the invariant.",
    boundary: "volatile gives visibility and ordering but not atomicity for read-modify-write, synchronized locks by monitor identity, concurrent collections protect documented operations, and callbacks under locks can deadlock.",
    scenarioA: "Two threads increment a shared int and lose updates, so the design confines counts per task and combines results after join.",
    scenarioB: "An AtomicInteger makes one counter increment atomic, while a multi-field account transfer still uses a lock around the complete invariant.",
    misconception: "Declaring a counter volatile makes counter++ atomic and therefore protects every invariant that includes the counter.",
    correction: "volatile does not make compound actions atomic; confine mutable state, use an appropriate atomic operation, or synchronize the entire invariant transition.",
    checkpoint: "compound actions atomic",
  },
  "java.concurrency.virtual": {
    model: "Java virtual threads make large numbers of mostly blocking tasks affordable while preserving the thread-per-task style; they do not create more CPU execution capacity.",
    boundary: "CPU-bound work still needs bounded parallelism, scarce external resources need limits, pinning or thread-local usage can affect scale, cancellation remains cooperative, and task lifetime needs structure.",
    scenarioA: "Each independent network request runs in a virtual thread while a semaphore limits the database connections they may occupy.",
    scenarioB: "A CPU-heavy image transform uses a bounded executor sized for processors instead of launching thousands of virtual threads.",
    misconception: "Virtual threads make CPU-bound code run in parallel without limits and remove the need for timeouts, cancellation, or resource bounds.",
    correction: "Use virtual threads for numerous blocking tasks, but still bound scarce resources and use CPU-appropriate parallelism for compute-bound work.",
    checkpoint: "blocking tasks",
  },
  "python.toolchain.repl": {
    model: "The Python REPL evaluates one interactive statement or expression at a time in persistent session state, making it useful for bounded observation before behavior is preserved in a script and test.",
    boundary: "The display hook shows expression representations differently from print, prior imports and bindings persist, multiline input follows interactive rules, and a successful scratch session is not a reproducible program.",
    scenarioA: "The learner evaluates 7 // 3 and repr of a Unicode string, records the observed values, then moves the verified behavior into a named function and test.",
    scenarioB: "A snippet fails after restarting because it depended on an earlier import, revealing the missing dependency before the idea enters saved source.",
    misconception: "REPL expression output is produced by print and any successful interactive sequence can be rerun as a complete script unchanged.",
    correction: "Use the REPL for a bounded observation, distinguish display-hook output from print, then preserve explicit imports, state, inputs, and assertions in saved code.",
    checkpoint: "bounded observation",
  },
  "python.toolchain.script": {
    model: "A Python script is parsed with indentation defining suites and executes top-level statements in order; an if __name__ == '__main__' guard separates importable definitions from command entry behavior.",
    boundary: "The guard does not create a function scope, importing executes unguarded top-level code once per module object, whitespace mixing can fail, and direct versus module launch changes package context.",
    scenarioA: "A file defines main(), keeps helpers importable, and calls main only under the conventional name guard so tests can import it without running the command.",
    scenarioB: "A module with an unguarded network call performs that call during import, so the side effect is moved behind an explicit function and entry guard.",
    misconception: "Python ignores indentation once code is syntactically valid and importing a script never executes its top-level statements.",
    correction: "Indentation is part of Python block syntax, and import executes top-level code; keep reusable definitions at module level and put command effects behind an explicit main guard.",
    checkpoint: "main guard",
  },
  "python.toolchain.environment": {
    model: "A Python process has a concrete interpreter version, executable path, arguments, working directory, import path, and environment; all can change observable script behavior.",
    boundary: "Activating a virtual environment mainly changes command lookup, relative paths resolve from the process working directory, PYTHONPATH can shadow modules, and editor-selected interpreters may differ from the terminal.",
    scenarioA: "The learner prints sys.executable, sys.version, sys.argv, and Path.cwd() to explain why an editor run finds a dependency that a shell run does not.",
    scenarioB: "A local file named json.py shadows the standard-library module, so inspecting module.__file__ reveals the search-path collision.",
    misconception: "A .py file always runs with the interpreter beside it and relative files resolve from the script's own directory.",
    correction: "Diagnose the actual process context: verify sys.executable, version, arguments, working directory, and import path before changing code or dependencies.",
    checkpoint: "sys.executable",
  },
  "python.toolchain.traceback": {
    model: "Python separates syntax diagnostics from exceptions and logic failures; a traceback shows the active call chain ending with the exception type and message, while chained causes preserve translated failure context.",
    boundary: "The last application frame is not always the root cause, handlers can alter chaining, one bad parse location can follow an earlier token error, and a normal exit can still produce an incorrect result.",
    scenarioA: "A ValueError traceback is read from its final type backward through application frames until the invalid conversion input is identified and tested.",
    scenarioB: "A caught JSON error is raised as a domain ConfigurationError using raise ... from ..., preserving both the useful abstraction and original cause.",
    misconception: "The first line of a traceback names the faulty source line and every Python bug raises an exception.",
    correction: "Classify syntax, exceptional runtime, and logic failures; read the exception type and relevant application frames, preserve causal chaining, and verify the repaired contract.",
    checkpoint: "causal chaining",
  },
  "python.values.scalars": {
    model: "Python names bind to objects; core scalar values include arbitrary-precision integers, finite-precision floats, booleans, None, and immutable Unicode strings, each with distinct equality and truth rules.",
    boundary: "bool is an int subclass, float cannot exactly represent many decimals, NaN has unusual equality, None is a singleton absence marker, and truthiness does not mean semantic validity.",
    scenarioA: "A missing optional value is checked with is None, a money amount uses Decimal at the boundary, and a count remains int without assuming a fixed machine width.",
    scenarioB: "An empty string is false but valid input for one domain, so code checks the actual contract instead of rejecting every falsey value.",
    misconception: "Python floats store decimal values exactly and any falsey value is equivalent to None.",
    correction: "Choose the scalar whose semantics match the domain, use is None for absence, and treat floating precision and truthiness as explicit contract decisions.",
    checkpoint: "is None",
  },
  "python.values.expressions": {
    model: "Python expressions follow documented precedence, short-circuit Boolean evaluation, rich comparison protocols, membership rules, and chained comparisons that evaluate a middle operand once.",
    boundary: "is tests identity rather than value, and/or return an operand rather than a forced bool, user-defined comparisons can return special values, and precedence does not replace clarity.",
    scenarioA: "A range check uses 0 <= index < len(values), while two equal strings are compared with == rather than relying on interning identity.",
    scenarioB: "A fallback expression uses name or 'guest' only when every falsey name should trigger the fallback; otherwise an explicit None test preserves empty text.",
    misconception: "is is a faster spelling of == and and/or always return True or False.",
    correction: "Use == for value equality and is for singleton identity such as None; trace short-circuit expressions because and and or return selected operands.",
    checkpoint: "selected operands",
  },
  "python.control.selection": {
    model: "Python if/elif/else evaluates truth conditions in order, while match applies structural patterns, guards, and captures to supported data shapes rather than acting as a generic switch.",
    boundary: "A capture pattern can shadow a constant name, guards run only after pattern success, sequence/string patterns differ, wildcard placement matters, and incomplete numeric boundaries leave gaps.",
    scenarioA: "A temperature classifier tests exact thresholds with an elif chain and has a documented branch for out-of-domain sensor values.",
    scenarioB: "A match statement destructures tagged command tuples, uses literals for command names, and keeps a final wildcard for malformed shapes.",
    misconception: "Every bare name in a match case compares against an existing variable or constant value.",
    correction: "Treat bare names in patterns as captures unless they are qualified value patterns; choose match for structural decomposition and test every selection boundary.",
    checkpoint: "bare names in patterns",
  },
  "python.control.iteration": {
    model: "Python for loops request values from an iterable, while loops repeat from a condition; correct loops define progress, termination, and behavior for empty input without needless manual indexing.",
    boundary: "range excludes its stop, mutating a container during iteration can skip or duplicate work, loop else has no-break semantics, and an exhausted iterator cannot restart itself.",
    scenarioA: "A for loop sums values directly and enumerate supplies indices only when both position and value are part of the output.",
    scenarioB: "A while loop reads until a sentinel or end of input and updates state on every error path so invalid data cannot trap execution.",
    misconception: "Python for always increments an integer index and range includes both endpoints.",
    correction: "A for loop consumes an iterable, and range excludes its stop; select direct iteration first and prove while-loop progress toward termination.",
    checkpoint: "range excludes its stop",
  },
  "python.collections.list-tuple": {
    model: "Python lists are mutable sequences, tuples are immutable sequence values often used for fixed records, and slicing creates a shallow sequence result with normalized bounds.",
    boundary: "A tuple can contain mutable objects, slice copies retain nested aliases, negative indices wrap within bounds, repeated-list construction can duplicate one inner reference, and large slices allocate.",
    scenarioA: "A list stores editable readings, a tuple returns a fixed coordinate pair, and values[:] creates a shallow outer copy before a local reorder.",
    scenarioB: "A matrix is built with a comprehension instead of [[0] * cols] * rows so each row is a distinct list.",
    misconception: "Tuple contents are deeply immutable and slicing a nested list recursively copies every contained value.",
    correction: "List mutation and tuple immutability apply to the outer sequence; slices are shallow copies, so nested mutable objects may remain shared.",
    checkpoint: "shallow copies",
  },
  "python.collections.dict-set": {
    model: "A dict maps hashable keys to values and preserves insertion order, while a set stores unique hashable elements for membership and set algebra without a sorted-order promise.",
    boundary: "Keys need stable equality and hashing, a missing subscript raises KeyError, set iteration order is not an API contract, mutable containers are unhashable, and dict order is not sorting.",
    scenarioA: "A frequency table uses dict.get to update counts, while a set removes duplicate identifiers before a separate sorted presentation step.",
    scenarioB: "A tuple of immutable fields is used as a composite key, but a list is rejected because mutation would make hashing unstable.",
    misconception: "Sets and dictionaries sort their contents automatically and any Python object can be used safely as a key.",
    correction: "Use stable hashable keys, distinguish insertion order from sorted order, and handle missing-key behavior deliberately with indexing, get, or setdefault.",
    checkpoint: "stable hashable keys",
  },
  "python.collections.aliasing": {
    model: "Python assignment copies a reference binding rather than an object; shallow copying duplicates one container shell, while nested values remain shared unless copied or rebuilt intentionally.",
    boundary: "Immutable values can be safely shared, deepcopy may copy too much or fail on resources, default arguments persist across calls, and in-place methods differ from rebinding.",
    scenarioA: "After b = a, b.append changes the one shared list; b = list(a) creates a separate outer list but still aliases nested dictionaries.",
    scenarioB: "A nested configuration is rebuilt field by field because an indiscriminate deepcopy would duplicate identity-bearing services incorrectly.",
    misconception: "Assigning one list to another name creates an independent list, and list.copy recursively detaches nested values.",
    correction: "Trace object identity and aliases explicitly: assignment shares the object and a shallow copy duplicates only the outer container.",
    checkpoint: "outer container",
  },
  "python.collections.text": {
    model: "Python str values are immutable Unicode text; splitting, joining, formatting, normalization, case handling, and encoding each solve a distinct boundary problem.",
    boundary: "User-perceived graphemes can span code points, casefold differs from lower, normalization forms change comparison, split without an argument treats whitespace specially, and bytes require an encoding boundary.",
    scenarioA: "A report builds rows with join and f-strings, then encodes UTF-8 only at the file or network boundary.",
    scenarioB: "A case-insensitive identifier comparison normalizes and casefolds according to its documented policy instead of assuming lower handles every script.",
    misconception: "One Python character is always one displayed glyph and calling lower makes arbitrary Unicode text safely comparable.",
    correction: "Treat str as Unicode code points, define normalization and case policy for the domain, and encode or decode explicitly only at byte boundaries.",
    checkpoint: "byte boundaries",
  },
  "python.functions.contracts": {
    model: "A Python function contract states accepted inputs, returned value, observable effects, and failure behavior; annotations and docstrings communicate the contract but runtime code and tests enforce it.",
    boundary: "A missing return produces None, annotations are not automatic validators, mutable inputs can be aliased, exceptions form part of the contract, and broad side effects hinder testing.",
    scenarioA: "A normalize_score function documents an inclusive numeric range, returns a float, raises ValueError outside it, and has normal plus boundary tests.",
    scenarioB: "A function that sorts a caller list is renamed and documented as mutating, or changed to return a new sorted list so its effect is not hidden.",
    misconception: "A return annotation forces Python to return that type and a docstring makes invalid calls impossible.",
    correction: "Annotations and docstrings describe the contract; implementation checks, narrow effects, and deterministic tests provide runtime evidence.",
    checkpoint: "describe the contract",
  },
  "python.functions.parameters": {
    model: "Python binds arguments to positional-only, positional-or-keyword, variadic, keyword-only, and defaulted parameters according to the signature before the function body executes.",
    boundary: "Default expressions run once at definition, *args is a tuple, **kwargs is a dict, duplicate bindings fail, and changing a public parameter name can break keyword callers.",
    scenarioA: "A function uses None as a default and creates a new list per call, while a keyword-only timeout prevents an unclear positional boolean or number.",
    scenarioB: "A logging wrapper forwards *args and **kwargs exactly once and does not silently consume a caller keyword intended for the wrapped function.",
    misconception: "Default list expressions run for each call, so appending to a default cannot affect a later invocation.",
    correction: "Default expressions are evaluated once at function definition; use an immutable sentinel such as None and create per-call mutable state inside the body.",
    checkpoint: "evaluated once",
  },
  "python.functions.scope-closures": {
    model: "Python resolves names through local, enclosing, global, and built-in scopes; closures retain references to enclosing cells, with nonlocal or global required for rebinding those outer names.",
    boundary: "Assignment makes a name local unless declared, loop-created closures can share one late-bound cell, mutable captured objects change without nonlocal, and global state couples tests.",
    scenarioA: "A make_counter closure uses nonlocal count to rebind its enclosing integer and gives each factory call an independent cell.",
    scenarioB: "Callbacks created in a loop bind the current value through a default argument rather than all reading the final loop variable later.",
    misconception: "A closure copies every captured value when it is created, so later changes to the enclosing binding cannot affect it.",
    correction: "Closures retain enclosing bindings and usually use late lookup; bind a snapshot deliberately when needed and use nonlocal only for explicit enclosing rebinding.",
    checkpoint: "enclosing bindings",
  },
  "python.functions.recursion": {
    model: "A recursive Python function solves a smaller instance, reaches an explicit base case, and combines returned results while consuming call-stack depth.",
    boundary: "Python does not guarantee tail-call elimination, recursion depth is limited, cycles need visited state, exponential recurrence can repeat work, and iterative forms may be clearer.",
    scenarioA: "A factorial function rejects negative input, returns 1 at zero, and recurs with n - 1 so every valid call moves toward the base case.",
    scenarioB: "A deep linked structure is traversed iteratively to avoid recursion limits, while a small tree exercise keeps recursion because its shape matches the definition.",
    misconception: "Any function that calls itself will eventually stop, and tail recursion uses constant stack space in Python.",
    correction: "State the base case and a strictly smaller progress measure, and choose iteration when depth can exceed Python's recursion limit.",
    checkpoint: "progress measure",
  },
  "python.modules.imports": {
    model: "Import locates a module through the import system, creates and executes its module object on first load, caches it in sys.modules, and binds selected names in the importer.",
    boundary: "Circular imports can observe partial initialization, wildcard imports obscure APIs, local names can shadow packages, reload does not rebuild every external reference, and top-level effects run during import.",
    scenarioA: "A calculation module keeps definitions at top level without command effects, and a CLI imports its public function explicitly.",
    scenarioB: "Two modules move a shared protocol into a third module to remove a circular import that read a not-yet-defined name.",
    misconception: "Import merely pastes definitions and never executes module code, so circular imports cannot expose incomplete state.",
    correction: "Import executes a module once into a cached module object; keep top-level effects minimal and redesign cycles that depend on partially initialized names.",
    checkpoint: "cached module object",
  },
  "python.modules.packages": {
    model: "A Python package organizes importable modules under a qualified namespace and exposes a deliberate public API while keeping implementation modules replaceable.",
    boundary: "Import packages differ from distribution packages, relative imports depend on package context, __init__ execution can create cycles, namespace packages differ, and underscore naming is convention rather than access control.",
    scenarioA: "A package re-exports one stable parse function from __init__.py while callers do not depend on its internal _tokens module.",
    scenarioB: "The application launches with python -m package.cli so relative imports have a package context instead of running the nested file directly.",
    misconception: "A directory with Python files is automatically the same thing as an installable distribution and relative imports work from any launch command.",
    correction: "Distinguish import package from distribution package, define a small public namespace, and launch modules with a valid package context.",
    checkpoint: "import package",
  },
  "python.modules.venv": {
    model: "A Python virtual environment selects an isolated interpreter prefix and site-packages location so project dependencies do not modify the base interpreter's package set.",
    boundary: "Activation only adjusts shell command lookup, the environment is not generally portable by copying, system packages can be exposed by option, and dependency declarations still need versions and platform context.",
    scenarioA: "The learner creates .venv, invokes that environment's python -m pip, records requirements, and confirms sys.prefix differs from sys.base_prefix.",
    scenarioB: "An editor is configured to the same .venv interpreter as the terminal after imports differ despite an activated shell.",
    misconception: "Activating a virtual environment changes Python globally and guarantees every editor, task, and subprocess uses it.",
    correction: "A virtual environment is selected by its interpreter path; activation is a shell convenience, so verify the executable used by every tool.",
    checkpoint: "interpreter path",
  },
  "python.modules.pyproject": {
    model: "pyproject.toml records build-system requirements and project metadata, while a conventional source/test layout and declared command entry point make a package buildable and invocable reproducibly.",
    boundary: "Metadata does not lock every application dependency, build backends differ, editable installs can hide packaging mistakes, package discovery needs configuration, and generated artifacts need clean-build checks.",
    scenarioA: "A src-layout project declares its build backend, project name/version/dependencies, and a console script that calls package.cli:main.",
    scenarioB: "A wheel is built in an isolated clean environment and installed into a fresh venv before the CLI is tested, exposing a missing package-data declaration.",
    misconception: "Adding any pyproject.toml automatically discovers every module, locks all dependencies, and proves the built wheel contains the working tree.",
    correction: "Treat pyproject metadata and backend configuration as a build contract, then inspect and test the built artifact in a fresh environment.",
    checkpoint: "build contract",
  },
  "python.errors.exceptions": {
    model: "Python exceptions propagate through frames until a matching except clause; responsible boundaries catch specific failures they can recover from, translate, or enrich while preserving the original cause.",
    boundary: "except Exception excludes some control exceptions but is still broad, finally always runs during unwinding, else separates success-only work, and handlers can accidentally mask a second failure.",
    scenarioA: "A configuration boundary catches JSONDecodeError and raises ConfigurationError from the original exception with the affected safe path.",
    scenarioB: "A narrow ValueError handler covers user parsing but lets an unrelated programming TypeError propagate to the application error policy.",
    misconception: "A bare except around a whole function is robust because it prevents all crashes and lets execution continue.",
    correction: "Catch specific exceptions at a responsible boundary, keep the try block narrow, preserve causal context, and recover only when a valid next state exists.",
    checkpoint: "keep the try block narrow",
  },
  "python.errors.custom": {
    model: "A custom Python exception names a domain failure that callers can handle distinctly, normally inherits from Exception, and carries safe structured context without replacing ordinary result alternatives.",
    boundary: "Too many exception types burden callers, messages are not stable machine APIs, secrets must not enter attributes, exception chaining matters, and expected absence may be better represented explicitly.",
    scenarioA: "A parse_order function raises InvalidOrderError with a safe field name and chains the underlying ValueError for diagnostics.",
    scenarioB: "A lookup returns None for documented optional absence but raises RepositoryUnavailable when it cannot determine whether data exists.",
    misconception: "Every validation branch deserves a separate custom exception, and callers should parse exception message text to decide recovery.",
    correction: "Define a custom exception only for a useful caller-visible failure category, expose stable safe attributes, and preserve the original cause with chaining.",
    checkpoint: "failure category",
  },
  "python.io.files-json": {
    model: "Python file persistence uses pathlib paths, explicit text encoding, context-managed I/O, and schema-aware JSON validation with documented handling for missing, malformed, partial, or forbidden data.",
    boundary: "Relative paths use the process working directory, JSON types do not enforce a domain schema, writes can be partial, ensure_ascii is a representation option, and untrusted sizes or nesting need bounds.",
    scenarioA: "A loader reads UTF-8 through Path.open, catches missing and decode failures separately, and validates required keys and value types before constructing domain data.",
    scenarioB: "A save writes a temporary sibling then replaces the target under a documented policy rather than assuming one text write is crash-atomic.",
    misconception: "json.load validates application fields and open automatically chooses UTF-8 and the script directory.",
    correction: "Resolve an explicit Path base, specify encoding, validate the decoded JSON shape, and define missing, malformed, size, and replacement behavior.",
    checkpoint: "validate the decoded JSON shape",
  },
  "python.io.context": {
    model: "A context manager's enter and exit protocol brackets resource use so cleanup runs on normal completion and exception unwinding; with binds the enter result, not necessarily the manager itself.",
    boundary: "__exit__ can suppress an exception by returning true, cleanup can fail, ownership determines who closes, multiple contexts unwind in reverse order, and async resources use a separate protocol.",
    scenarioA: "A file is opened with a with statement and is closed even when parsing raises halfway through the suite.",
    scenarioB: "A custom transaction context rolls back on an exception, commits on success, and returns false so unexpected exceptions keep propagating.",
    misconception: "with is only shorthand for close at the final line and every __exit__ return value re-raises exceptions.",
    correction: "Use with to guarantee protocol-driven cleanup during all exits, and return false from __exit__ unless the manager deliberately and safely suppresses the exception.",
    checkpoint: "protocol-driven cleanup",
  },
  "python.objects.class": {
    model: "A Python class defines behavior and shared class attributes, while each instance normally stores its own attributes; methods receive the instance explicitly as self and should preserve invariants.",
    boundary: "Attribute access can invoke descriptors, class mutable values are shared, privacy is conventional, __slots__ changes storage rather than access control, and direct assignment can bypass ad-hoc validation.",
    scenarioA: "A Counter initializes self.value per instance and exposes increment without storing the mutable count as one class attribute shared by every object.",
    scenarioB: "A class-level immutable unit label is shared intentionally, while each reading list is created inside __init__.",
    misconception: "An empty list declared in a class body becomes a separate list automatically for each new instance.",
    correction: "Class attributes are shared through the class; create per-instance mutable state on self during initialization and preserve invariants through focused methods.",
    checkpoint: "per-instance mutable state",
  },
  "python.objects.dataclass": {
    model: "A Python data class generates selected initialization, representation, and comparison methods from annotated fields, making transparent value models concise while leaving validation and mutability policy explicit.",
    boundary: "Data classes are not runtime type validators, mutable defaults need default_factory, frozen is not deep immutability, ordering needs coherent fields, and identity-rich behavior may suit a regular class.",
    scenarioA: "A frozen Point dataclass stores two floats and validates finiteness in __post_init__, providing transparent field-based equality.",
    scenarioB: "A list field uses field(default_factory=list) so each instance owns a distinct collection.",
    misconception: "@dataclass validates annotations and creates a fresh copy of any default list for every instance.",
    correction: "Dataclass annotations drive generated methods rather than runtime validation; use default_factory for per-instance mutable defaults and validate invariants explicitly.",
    checkpoint: "default_factory",
  },
  "python.objects.inheritance": {
    model: "Python inheritance should represent substitutable behavior with cooperative super calls, while composition delegates work without exposing an unnecessary subtype relationship.",
    boundary: "Multiple inheritance uses method resolution order, super means next in that order rather than a named parent, signatures and invariants must remain compatible, and fragile base state can couple subclasses.",
    scenarioA: "Two mixins use cooperative super with compatible signatures so every initializer in the MRO participates exactly once.",
    scenarioB: "A Stack owns a deque rather than inheriting from it, preventing callers from using queue operations that violate the stack contract.",
    misconception: "super always calls one fixed parent class and inheritance is the best reuse mechanism whenever methods overlap.",
    correction: "Use inheritance only for substitutable behavior and follow the method resolution order cooperatively; prefer composition when reuse does not require a subtype.",
    checkpoint: "method resolution order",
  },
  "python.objects.protocols": {
    model: "Python special methods let a type participate in representation, equality, hashing, length, containment, and iteration protocols, with each method required to honor the corresponding language contract.",
    boundary: "__repr__ should be unambiguous and safe, __eq__ may return NotImplemented, equal hashable objects need equal hashes, __len__ affects truthiness, and protocol methods should avoid surprising side effects.",
    scenarioA: "A Coordinate implements a safe repr and value equality, returns NotImplemented for unrelated types, and remains immutable before defining hash behavior.",
    scenarioB: "A container's __iter__ returns a fresh iterator each call rather than returning one permanently exhausted iterator object.",
    misconception: "Returning False from __eq__ for every unknown type is always correct and defining __eq__ leaves inherited hashing valid automatically.",
    correction: "Honor each data-model protocol: return NotImplemented for unsupported equality, align equality with hashing, and keep representation and iteration predictable.",
    checkpoint: "return NotImplemented",
  },
  "python.iteration.comprehensions": {
    model: "Python comprehensions build list, set, or dict results from an iterable with expression and filter clauses whose nesting order follows the equivalent explicit loops.",
    boundary: "Comprehensions allocate their result, nested clauses can become unreadable, side effects obscure intent, assignment-expression scope needs care, and generator expressions are the lazy alternative.",
    scenarioA: "A dict comprehension maps valid names to normalized lengths with one readable filter, replacing a three-line append/update loop.",
    scenarioB: "A complex transformation with error handling remains an explicit loop because compressing it would hide branches and diagnostics.",
    misconception: "A comprehension is always faster and more memory-efficient than a loop, regardless of result size or complexity.",
    correction: "Use a comprehension for a bounded readable transformation; choose an explicit loop for complex effects and a generator expression when lazy consumption is required.",
    checkpoint: "bounded readable transformation",
  },
  "python.iteration.iterator": {
    model: "An iterable can produce an iterator, while an iterator is a stateful one-pass object whose __next__ yields values until it raises StopIteration.",
    boundary: "iter(iterator) normally returns itself, exhausted iterators stay exhausted, multiple iterators may or may not be independent, mutation can invalidate traversal, and StopIteration has special generator rules.",
    scenarioA: "A custom Countdown iterable returns a new iterator for each for loop, letting two traversals progress independently.",
    scenarioB: "Calling list on a generator iterator consumes it, so a second list call is empty and the source must be recreated for another pass.",
    misconception: "Iterable and iterator are interchangeable, and calling iter on an exhausted iterator restarts it.",
    correction: "An iterable supplies iterators; an iterator carries one-pass state and remains exhausted after StopIteration unless a new iterator is created from a reusable source.",
    checkpoint: "one-pass state",
  },
  "python.iteration.generator": {
    model: "A generator function suspends at yield and resumes with preserved local state, producing a lazy one-pass iterator whose work occurs only as values are requested.",
    boundary: "Construction does not run the body, exceptions appear during consumption, resources need close/finally care, infinite generators need bounds, and reuse requires creating a new generator.",
    scenarioA: "A chunks generator yields bounded slices one at a time and is tested for empty input, exact division, and a final partial chunk.",
    scenarioB: "A file-line generator owns its file inside a generator context and the consumer uses a bounded loop so cleanup is deterministic on early exit.",
    misconception: "Calling a generator function executes it immediately and the returned generator can be iterated repeatedly from the beginning.",
    correction: "A generator body runs lazily during one-pass consumption and preserves suspended state; create a new generator for another traversal and close owned resources deliberately.",
    checkpoint: "one-pass consumption",
  },
  "python.iteration.decorator": {
    model: "A function decorator receives a callable and returns a replacement callable, usually forwarding arbitrary arguments and preserving metadata with functools.wraps.",
    boundary: "Decoration normally occurs at definition/import time, wrapper signatures and descriptors matter, state can be shared across calls, async/generator functions need compatible wrappers, and order changes composition.",
    scenarioA: "A timing decorator uses @wraps, accepts *args and **kwargs, returns the wrapped result, and records only safe duration metadata.",
    scenarioB: "Two decorators are applied in documented order, and a test proves exceptions and return values pass through unchanged.",
    misconception: "A decorator runs only when the function is called and functools.wraps automatically forwards arguments and results.",
    correction: "Decoration replaces the callable at definition time; the wrapper must explicitly forward arguments, result, and failure behavior, while functools.wraps preserves metadata.",
    checkpoint: "preserves metadata",
  },
  "python.quality.typing": {
    model: "Python type hints describe interfaces for static tools and readers using unions, parameterized collections, protocols, and type variables, but do not generally enforce values at runtime.",
    boundary: "Any disables checking, variance affects generic compatibility, forward references and runtime introspection differ, casts make assertions without conversion, and external data still needs validation.",
    scenarioA: "A function accepts Iterable[str] and returns dict[str, int], while a Protocol describes the one write method a collaborator must provide.",
    scenarioB: "JSON data is validated at runtime before being treated as a typed domain object; adding a cast alone does not change or check it.",
    misconception: "Annotations reject wrong values automatically at runtime and typing.cast converts an object into the requested type.",
    correction: "Type hints guide static analysis but are not runtime enforcement; validate untrusted values explicitly and use cast only to inform the checker.",
    checkpoint: "not runtime enforcement",
  },
  "python.quality.unittest": {
    model: "Python automated tests isolate fixtures, call observable contracts, and assert normal, boundary, and failure behavior; mocks belong at genuine external or nondeterministic boundaries.",
    boundary: "Test order should not carry state, patch targets must match lookup location, broad mocks can reproduce implementation rather than behavior, and coverage measures execution rather than assertion quality.",
    scenarioA: "A table of subtests covers empty, normal, Unicode, and malformed cases, while assertRaises checks the exact domain failure.",
    scenarioB: "A clock collaborator is injected and controlled, but the test asserts the returned expiration policy rather than private call sequence.",
    misconception: "More mocks always make a unit test better isolated and high coverage proves all contracts are tested.",
    correction: "Assert public behavior with deterministic fixtures, isolate true external boundaries, and derive cases from equivalence classes, boundaries, and failures.",
    checkpoint: "public behavior",
  },
  "python.quality.logging": {
    model: "Python logging emits severity-appropriate structured operational events through configured handlers, keeping diagnostics separate from user output and excluding secrets or excessive personal data.",
    boundary: "String interpolation can happen before filtering, handlers can duplicate messages, exception logging may expose inputs, library code should not own global configuration, and logs are not control flow.",
    scenarioA: "A service logs a safe request id, operation, and failure category with logger.exception while the user receives a bounded message.",
    scenarioB: "An API token and full payload are excluded or redacted even during debug logging, and a test asserts the secret never enters captured logs.",
    misconception: "Debug level permits passwords, tokens, or raw learner data because production normally filters those records.",
    correction: "Never place secrets in log arguments, use structured safe context and appropriate severity, and configure handlers at the application boundary.",
    checkpoint: "Never place secrets",
  },
  "python.quality.project": {
    model: "A Python project is completed through reproducible setup, a package and command boundary, typed contracts, deterministic tests, safe logging, debugger-guided diagnosis, and documented verification evidence.",
    boundary: "A local editable install can hide packaging gaps, debugger state can change timing, platform paths vary, optional dependencies need policy, and a passing happy path is not portfolio-ready evidence.",
    scenarioA: "A fresh virtual environment installs the built wheel, runs the CLI's normal and failure cases, executes tests, and records exact commands in the project README.",
    scenarioB: "A breakpoint finds one invalid state transition, the fix gains a regression test, and logging records safe context without leaking input secrets.",
    misconception: "A project is complete once it runs from the developer's source directory and produces the expected output for one sample.",
    correction: "Verify the built artifact from a fresh environment and demonstrate normal, boundary, and failure contracts with tests, safe diagnostics, and reproducible commands.",
    checkpoint: "fresh environment",
  },
  "python.concurrency.model": {
    model: "Concurrency allows tasks to make overlapping progress, parallelism performs work simultaneously, and the useful model depends on I/O waiting, CPU cost, latency, throughput, and shared-state constraints.",
    boundary: "The GIL and implementation details affect Python threads but do not remove races, processes add serialization cost, async requires cooperative nonblocking code, and more workers can reduce performance.",
    scenarioA: "Many independent network waits are classified as I/O-bound and can overlap, while one numerical loop is CPU-bound and measured before selecting processes.",
    scenarioB: "A responsive UI moves blocking work away from its event loop even when total throughput does not increase.",
    misconception: "Concurrency and parallelism mean the same thing, and adding threads always makes any Python workload faster.",
    correction: "Classify waiting versus computation and the desired latency or throughput; choose concurrency for overlapping progress and parallel resources only when simultaneous work offsets coordination cost.",
    checkpoint: "overlapping progress",
  },
  "python.concurrency.async": {
    model: "An asyncio coroutine yields control at await points, tasks schedule coroutine progress on an event loop, and structured coordination must handle result, timeout, failure, and cancellation paths.",
    boundary: "Blocking calls freeze the event loop, creating a coroutine does not schedule it, cancellation is injected at suspension points, background tasks need strong references and observation, and shared state still races logically.",
    scenarioA: "Three bounded simulated I/O calls run as tasks under a timeout, results are gathered, and remaining tasks are cancelled and awaited on failure.",
    scenarioB: "A blocking library call is moved to an appropriate thread boundary rather than called directly inside an async function.",
    misconception: "Declaring async makes the function run in parallel immediately and every call inside it becomes nonblocking.",
    correction: "Calling async creates a coroutine; schedule or await it, keep blocking work off the event loop, and handle timeout plus cancellation cleanup explicitly.",
    checkpoint: "creates a coroutine",
  },
  "python.concurrency.threads-processes": {
    model: "Python threads share process memory and can overlap compatible waiting work, while processes isolate memory and can use multiple CPU cores at the cost of startup and data serialization.",
    boundary: "Threads still need synchronization, process arguments/results must be transferable, platform start methods differ, worker pools need shutdown, and small tasks can cost more to coordinate than run sequentially.",
    scenarioA: "A bounded thread pool overlaps independent HTTP waits, while a measured CPU transform uses a process pool with coarse tasks.",
    scenarioB: "The command keeps process-pool creation under a main guard so spawn-based platforms do not recursively create workers.",
    misconception: "Processes share ordinary mutable objects automatically, and threads cannot have races because of the interpreter lock.",
    correction: "Threads share mutable state and require coordination; processes use isolated memory and explicit communication, so choose after measuring workload and transfer costs.",
    checkpoint: "isolated memory",
  },
  "python.concurrency.safety": {
    model: "Concurrency safety protects complete invariants across shared-state transitions and guarantees cleanup during failure or cancellation, preferably through confinement, immutable messages, and structured ownership.",
    boundary: "A single operation's atomic implementation does not protect multi-step logic, locks can deadlock, cancellation can arrive at await points, finally blocks can also fail, and queues need shutdown/backpressure policy.",
    scenarioA: "A check-then-update balance operation is placed under one lock or owned by one task rather than relying on two individually safe dictionary operations.",
    scenarioB: "An async worker releases its semaphore in an async context/finally path when cancellation interrupts the awaited operation.",
    misconception: "Built-in collection operations make every multi-step shared-state algorithm atomic and cancellation can only occur between function calls.",
    correction: "Protect the entire invariant transition, minimize shared mutation, and place resource release in cancellation-safe context or finally paths.",
    checkpoint: "entire invariant transition",
  },
} as const satisfies Readonly<Record<string, JavaPythonTeachingSeed>>;
