import { createHash } from "node:crypto";
import { describe, expect, it } from "vitest";
import { validateRuntimeImageRecordText } from "../local-launcher.js";

const languages = ["c", "cpp", "java", "python", "javascript"] as const;

function publication(local = true) {
  const records = languages.map((language, index) => {
    const manifestDigest = `sha256:${String(index + 1).repeat(64)}`;
    return {
      language,
      reference: `registry.example.test/codestead-${language}@${manifestDigest}`,
      manifestDigest,
      configDigest: `sha256:${"abcde"[index]!.repeat(64)}`,
      rootDigest: manifestDigest,
    };
  });
  const payload = { schemaVersion: 1, release: "test-release", local, records };
  const recordId = createHash("sha256").update(JSON.stringify(payload)).digest("hex");
  const document = { schemaVersion: 1, recordId, release: payload.release, local, records };
  const envText = [
    "# Generated by runtime/manage-images.mjs record; do not hand-edit.",
    `# runtime-record-id=${recordId}`,
    ...records.map((record) => `RUNNER_IMAGE_${record.language.toUpperCase()}=${record.reference}`),
    "",
  ].join("\n");
  return { document, envText, jsonText: `${JSON.stringify(document, null, 2)}\n` };
}

describe("canonical runtime image publication consumer", () => {
  it("accepts the JSON commit marker only when its exact env projection is present", () => {
    const value = publication();
    expect(validateRuntimeImageRecordText(value)).toEqual(Object.fromEntries(
      value.document.records.map((record) => [
        `RUNNER_IMAGE_${record.language.toUpperCase()}`,
        record.reference,
      ]),
    ));
  });

  it("rejects stale, tampered, duplicate, and digest-conflated records", () => {
    const value = publication();
    expect(() => validateRuntimeImageRecordText({
      envText: value.envText.replace(value.document.recordId, "f".repeat(64)),
      jsonText: value.jsonText,
    })).toThrow(/environment projection|record id/i);

    expect(() => validateRuntimeImageRecordText({
      envText: value.envText,
      jsonText: value.jsonText.replace(value.document.recordId, "f".repeat(64)),
    })).toThrow(/record id/i);

    const duplicate = structuredClone(value.document);
    duplicate.records[1]!.language = "c";
    expect(() => validateRuntimeImageRecordText({
      envText: value.envText,
      jsonText: JSON.stringify(duplicate),
    })).toThrow(/language|canonical/i);

    const conflated = structuredClone(value.document);
    conflated.records[0]!.configDigest = conflated.records[0]!.manifestDigest;
    expect(() => validateRuntimeImageRecordText({
      envText: value.envText,
      jsonText: JSON.stringify(conflated),
    })).toThrow(/config digest|canonical/i);
  });

  it("rejects non-canonical fields and missing publication text", () => {
    const value = publication();
    const extra = { ...value.document, ignored: true };
    expect(() => validateRuntimeImageRecordText({
      envText: value.envText,
      jsonText: JSON.stringify(extra),
    })).toThrow(/schema|canonical/i);
    expect(() => validateRuntimeImageRecordText({ envText: "", jsonText: value.jsonText }))
      .toThrow(/environment projection/i);
    expect(() => validateRuntimeImageRecordText({ envText: value.envText, jsonText: "" }))
      .toThrow(/JSON|record/i);
  });
});
